### ISSUE TITLE
You have no weapons assigned to groups

### ISSUE THREAD

**Issue by MacXimus** [sstixrud/WeaponCore#100]
I have three weapons groups but they are not recognized by WeaponCore.
New game, WC loaded from start.

**Comment by sstixrud** [comment]
Need more information, cannot reproduce.

**Comment by MacXimus** [comment]
what additional information would be useful?

**Comment by MacXimus** [comment]
I deleted all weapon groups and recreated new ones (again, for the fourth time).

One of the previous groups was a mixed block type group (fixed gatlings and homing missiles) that was inop (see issue #99).  Perhaps the inop weapon group (had no mouse control option) was interfering with WC's ability to assign actions to groups?  Conjecture on my part.

I did not recreate this group type (based on issue #99 result) and they are working now.

I guess you can close this issue.
