### ISSUE TITLE
Grid can only target projectiles if the player is nearby

### ISSUE THREAD

**Issue by mexpex** [sstixrud/WeaponCore#105]
https://youtu.be/ilwqZDzjJbM
Grid not targeting projectiles, player ~3.5km away
at 0:20, player teleport to grid and it starts to target incoming projectiles

**Comment by mexpex** [comment]
Improved description
Grid A fires missiles at grid B that is a few km away. The player is nearby A.
The issue: The anti missile weapon placed on B will not engage incoming missiles(first part of video)
As soon as the player teleport to/nearby B the weapons engage the incoming missiles from grid A (post 0:20 in video)

**Comment by sstixrud** [comment]
Fixed
