### ISSUE TITLE
Strange issue started today

### ISSUE THREAD

**Issue by spacednconfuzed** [sstixrud/WeaponCore#107]
Keep getting CTD on my DS today , I have tried my main world and a completely blank world , have the weaponcore weapons and also Rival AI and the couple of NPC mods that use it.

Randomly I get the following and CTD (Server stays up so its clent side)

Exception occured: System.NullReferenceException: Object reference not set to an instance of an object.
   at WeaponCore.Platform.Weapon.StartReload(Boolean reset)
   at WeaponCore.Platform.Weapon.ReloadClient()
   at ParallelTasks.Parallel.RunCallbacks()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)

Examples of the errors on the log are as follows :

04-10-20_16-01-13-530 - Invalid Packet: GridAiUiMidUpdate Occured
04-10-20_16-01-13-531 - Invalid Packet: GridAiUiMidUpdate Entity: 91249553321787090 Added
04-10-20_16-01-13-544 - Invalid Packet: GridOverRidesSync Occured
04-10-20_16-01-13-545 - Invalid Packet: GridOverRidesSync Entity: 91249553321787090 Added
04-10-20_16-01-13-547 - Invalid Packet: GridFocusListSync Occured
04-10-20_16-01-13-547 - Invalid Packet: GridFocusListSync Entity: 91249553321787090 Added
04-10-20_16-01-14-113 - Invalid Packet: Invalid Entity: 91249553321787090 Reproccessed Successfully, Error Cause: myGrid is null: True ent.MarkedForClose: 
04-10-20_16-01-14-122 - Invalid Packet: Invalid Entity: 91249553321787090 Reproccessed Successfully, Error Cause: 
04-10-20_16-01-14-692 - Invalid Packet: Invalid Entity: 91249553321787090 Reproccessed Successfully, Error Cause: targetPacket is null ent.MarkedForClose:  myGrid is null

04-10-20_16-09-13-962 - Invalid Packet: GridAiUiMidUpdate Occured
04-10-20_16-09-13-962 - Invalid Packet: GridAiUiMidUpdate Entity: 102693410092748834 Added
04-10-20_16-09-13-962 - Invalid Packet: GridOverRidesSync Occured
04-10-20_16-09-13-962 - Invalid Packet: GridOverRidesSync Entity: 102693410092748834 Added
04-10-20_16-09-13-962 - Invalid Packet: GridFocusListSync Occured
04-10-20_16-09-13-962 - Invalid Packet: GridFocusListSync Entity: 102693410092748834 Added

This is for two separate crashes .... Is this weaponcore or is it something NPC based that is causing this ?

**Comment by blitz2190** [comment]
the first is an actual error that should be fixed in the next update, the second is not an error "Invalid Packet: " is jsut logging network packets that need to be Reprocessed when not all the grids have streamed in yet (when you join a game, or come into sync distance)

**Comment by sstixrud** [comment]
Fixed.
