### ISSUE TITLE
Let trails "stick" to a beam

### ISSUE THREAD

**Issue by TheWizardLizard** [sstixrud/WeaponCore#109]
Since the only way to make a laser fade out currently is to apply a trail to it, it results in this unintended side effect while moving the laser across a target.

[Video](http://protogen.ga/p/1MncrAGaLA.mp4)

![image](https://user-images.githubusercontent.com/17933206/79044729-dbd9f900-7bd4-11ea-8066-f2d9225b3855.png)

This could probably be fixed by allowing a trail to act similarly to a laser, as in it always points forward.

**Comment by sstixrud** [comment]
fixed
