### ISSUE TITLE
NPCs not shooting

### ISSUE THREAD

**Issue by MrKiel** [sstixrud/WeaponCore#110]
[Star System - More Mods - Encounter - Debug.zip](https://github.com/sstixrud/WeaponCore/files/4465515/Star.System.-.More.Mods.-.Encounter.-.Debug.zip)

Hi,

I've been looking into the "NPCs not shooting" issue and it doesn't appear to be a lack of ammo causing the problem.

I have WeaponCore and Vanilla Replacement mods installed, as well as a few others.

I don't think it's a lack of ammo, because I just boarded an SPRT R.U.S.T Hauler, a vanilla encounter. When I checked the turrets, all had ammo. A few things I noticed, though:

- No turrets were firing when I encountered the ship. They aimed (and gatling barrels were spinning), but didn't shoot.
- On reloading the save, the interior turrets started firing.
- Gatling turrets would not fire. They aim and the barrels spin, but they don't shoot.
- If I grind down a gatling turret and weld it back to functional, it still tries to shoot me, but can't. Even after reloading the game.
- Turning the gatling turrets off, waiting a moment and then turning them back on, allows them to fire again. Unfortunately, despite owning it, the turret shot me.

So first I think there's possibly a misconfiguration of the turrets when they initially spawn, that may be solved by doing the scripting equivalent of turning them off and on again. It's not clear how a turret can shoot me once I've taken ownerhip of it; I don't think there's a way to blame that on vanilla mechanics - perhaps a setting in weaponcore that isn't being 'reset' when ownership is changed?

I've encountered this bug on a number of NPC ships (turrets track but don't shoot), this is the first time I've managed to investigate it a little further.

I saved the game at multiple points on this encounter. The attached should show the "Gatling turrets not shooting" behaviour. Try grinding/welding a Gatling turret, and then turning it off and on again.

**Comment by sstixrud** [comment]
You must use a weaponcore aware NPC mod.

**Comment by amezick** [comment]
Is there a place where a list of these mods is kept?  Does that include the Modular Encounters?
