### ISSUE TITLE
Feature request: Sound played on cycling ammo and UI indicator for which ammo type is selected

### ISSUE THREAD

**Issue by OwendB1** [sstixrud/WeaponCore#115]
It would be nice to see these features introduced as they could make it easier for the user to know which ammo type has been loaded. 

Just an idea but it might be nice to not be able to use ammo cycling when only one type of ammo is available and if one type is only available it switches automatically to that type when trying to fire. 

Maybe indicative sound lines like "can not switch ammo because only one type available" and "switched ammo succesfully" could be added?

**Comment by TheWizardLizard** [comment]
Closed due to inclusion into megathread
