### ISSUE TITLE
Feature Request: Beam fade on end

### ISSUE THREAD

**Issue by mexpex** [sstixrud/WeaponCore#117]
Request
When a weapon using beams stops firing the beam will fade. If possible the fade duration would be a config variable but a hard coded one would probably cover most cases.
EndFade = True/false
EndFadeDuration = 0

Reason
The current implementation works for beams with a static duration. such as atlas laser or the wortho beam. But it wont work visually in cases when you have beams that fire with a random duration, like kills its target after 1 sec and moves to the next, that one takes 5sec.

**Comment by sstixrud** [comment]
Added the ability to use delayCeaseFire instead, the alternative described above would be very difficult to implement because drawing stops occurring when weapon is no longer firing.
