### ISSUE TITLE
Missiles and Torpedoes completely ignoring Mouse Shoot

### ISSUE THREAD

**Issue by AtomicHawk** [sstixrud/WeaponCore#118]
![20200413182602_1](https://user-images.githubusercontent.com/44002608/79168170-35018280-7db7-11ea-9939-b3baf58835b2.jpg)
![20200413182603_1](https://user-images.githubusercontent.com/44002608/79168171-359a1900-7db7-11ea-9cff-18588c519af1.jpg)
[debugdevelop.log](https://github.com/sstixrud/WeaponCore/files/4472223/debugdevelop.log)

This is an issue I've been having for a while now. Creative mode, single player, offline mode. Weapon groups set up correctly, and "Mouse Shoot" on/off for selected groups is on the hotbar as seen in the screenshots. All values in the MMB menu are default/unchanged. The main issue is that the missiles and torpedoes fire continuously regardless of whether or not Mouse Shoot is on or off. Screenshots show them firing with it off. Even when it's on, clicking the mouse does absolutely nothing. The only way to start/stop the missiles and torpedoes from firing is turning the blocks on/off.

The second issue is that they continue to fire even when nothing is targeted (as seen in the screenshots again). On top of that, they explode after going ~50m straight out (see screenshot; this is not an issue when there is an active target).

**Comment by sstixrud** [comment]
Issue should be fixed... reopen if not
