### ISSUE TITLE
Feature Request: Solid Background for MMC menu

### ISSUE THREAD

**Issue by Xeno1177** [sstixrud/WeaponCore#119]
Middle Mouse Click menu font color is invisible depending on background for those players with color deficiencies.  This makes the menu hard, if not impossible, to use under certain conditions.

Add a background to the text similar to what vanilla SE uses for ingame menus.  Would be great if it also used the background transparency game option for those players who want a completely opaque or transparent background.

![20200414124813_1](https://user-images.githubusercontent.com/49629363/79268736-1b604980-7e50-11ea-907f-70d18ae76714.jpg)
![
20200414124836_1](https://user-images.githubusercontent.com/49629363/79268742-1ef3d080-7e50-11ea-9dbb-74a8f26c34eb.jpg)

**Comment by TheWizardLizard** [comment]
Closed due to inclusion into megathread
