### ISSUE TITLE
sound effect for fire cut off early

### ISSUE THREAD

**Issue by AutoMcDonough** [sstixrud/WeaponCore#120]
When the gun stops shooting it kills the sound effect prematurely. The sound effect has an extra second or two to it. Would be ok if that was stopped in order to restart it for another shoot, but snapping it off as soon as bullets are out sounds very bad.

**Comment by TheWizardLizard** [comment]
I agree with this

**Comment by AutoMcDonough** [comment]
I've found that I can get around this issue by using per-shot sound effect, the early cutoff seems to be associated with a shared sound and burst fire.

**Comment by sstixrud** [comment]
Added feature to delay firestopdelay
