### ISSUE TITLE
Cannon firing sound plays when projectile impacts target, fragments.

### ISSUE THREAD

**Issue by AWG-935** [sstixrud/WeaponCore#121]
Video here:
[SoundBugMP4.zip](https://github.com/sstixrud/WeaponCore/files/4481681/SoundBugMP4.zip)

Edit:
Okay so sometimes it seems to fragments shells 3 times over, playing the OG firing sound for several fragments, getting real funky results

**Comment by sstixrud** [comment]
Need more info, this shouldnt happen.

**Comment by sstixrud** [comment]
@AWG-935 need more info on this.
