### ISSUE TITLE
Mouse Shoot Option in Groups Not Appearing

### ISSUE THREAD

**Issue by illyriah** [sstixrud/WeaponCore#125]
The toggle mouse shoot option never appears. 

I've tried a few different WeaponCore weapon mods, on top of having WeaponCore, but none work -- not even the vanilla weapons replacement mod or the GSF energy weapons pack. 

I've tried deleting all mods and redownloading them, integrity checks, and various settings. I have also tried making a new game with just WC and a weapons pack, twice, but to no avail. It's always missing. I've put it in single and multiplayer mode as well. 

I've also tried several different weapon configurations in the groups as well. Even groups with only 1 weapon in it don't work, or multiples of 1 weapon type.

![20200418133749_1](https://user-images.githubusercontent.com/6855048/79667740-b40e0680-817b-11ea-98dd-ebb8616ec1d2.jpg)
![20200418133754_1](https://user-images.githubusercontent.com/6855048/79667766-b53f3380-817b-11ea-8e7a-90759776c5f2.jpg)
![20200418133831_1](https://user-images.githubusercontent.com/6855048/79667787-b708f700-817b-11ea-9417-3a400dcc67bc.jpg)
![20200418133849_1](https://user-images.githubusercontent.com/6855048/79667809-b83a2400-817b-11ea-8d3d-2d9570559e27.jpg)
![20200418133853_1](https://user-images.githubusercontent.com/6855048/79667831-ba03e780-817b-11ea-98ed-91671f58344c.jpg)
![20200418133857_1](https://user-images.githubusercontent.com/6855048/79667843-bbcdab00-817b-11ea-93bf-6dbedda4b696.jpg)

**Comment by TheWizardLizard** [comment]
GSF Energy Weapons is out of date on its side. Report to author.
