### ISSUE TITLE
Simspeed dropping at 0 forever

### ISSUE THREAD

**Issue by noxstar42** [sstixrud/WeaponCore#127]
Playing in singleplayer. After some time in the game, the simulation speed drops to 0. No buttons respond, have to need close game via task manager.
[debugdevelop.log](https://github.com/sstixrud/WeaponCore/files/4498233/debugdevelop.log)
[SpaceEngineers.log](https://github.com/sstixrud/WeaponCore/files/4498480/SpaceEngineers.log)

**Comment by sstixrud** [comment]
log does not show any mod related sim issue.

**Comment by noxstar42** [comment]
@sstixrud I'm not sure it has anything to do with simulation speed, but the game behaves like it's going drops to 0. All because it looks like a simspeed drops to zero, the game freeze, but the animations, like hydrogen or ion thrusters tails works. The f11 interface immediately disappears when game freezes, so i cant see any info
