### ISSUE TITLE
Sorter based weaps sometimes don't pull ammo.

### ISSUE THREAD

**Issue by AutoMcDonough** [sstixrud/WeaponCore#128]
There's probably a lot of edge cases where they don't pull ammo automatically. One of them being when it is first placed on grid.

I think that it should at least TRY to pull ammo if it is empty and asked to shoot. This way that no matter what edge cases made it thru, this is a triggerable event where it needs bullets and doesn't have them.

**Comment by sstixrud** [comment]
reloading code rewritten please retest and submit again if still an issue
