### ISSUE TITLE
Turrets are stuck at 100 while asking for 0.0-0.0 - WC(87)

### ISSUE THREAD

**Issue by zasroman** [sstixrud/WeaponCore#131]
So, by request I am posting this report on the WC Gatling Turrets.

![New Bitmap Image (2)](https://user-images.githubusercontent.com/64328990/80288905-f42b3700-86ef-11ea-8371-1905e86b7cc6.jpg)
![New Bitmap Image](https://user-images.githubusercontent.com/64328990/80288910-fab9ae80-86ef-11ea-9b96-cad648f55a33.jpg)

1) new survival world with WC and WC vanilla replacement mods.
no other mods were present
2) 2 turrets were placed in the world with creative mode tools enabled with a reactor holding 1kg uranium (not 1k kg),  Both turrets reported as the Top image
3) creative mode tools were disabled and 1 turret was ground down for parts
4) another turret was placed and welded to completion; bottom image

Why and Results:

In a survival play-through I noticed that the turrets wouldn't fire at a few CORRUPT drone fighters, none were firing and looked like the bottom turret. 1 Save and rage quit after a turret was destroyed.
I loaded back the world and scrambled to build a replacement turret and noticed that the intact turret was firing as the newly built one wasn't. My rover was destroyed :(

The top image shows a turret that is acting properly for the moment:  Step two turret
The bottom image shows a turret with its faculties seemingly absent:  Step four turret

[debug.log](https://github.com/sstixrud/WeaponCore/files/4533894/debug.log)

**Comment by sstixrud** [comment]
Will be fixed in next patch
