### ISSUE TITLE
Weapongroupcontrol with Mouse Freezes

### ISSUE THREAD

**Issue by Abisius** [sstixrud/WeaponCore#132]
noticed problem when docking grids that both have weaponcore groups together.
docking 2 armed grids with weapongroups on them together with a connector, go into the weaponcontrolmenu with the mouse and change the settings of a group, when you then undock them it breaks the wc menu so that it is no longer possible to change settings over the move buttons because you cant go futhert than the first page and cant scroll through the groups and it can only be fixed with a reload of the world

it happened to me in singleplayer

**Comment by Captain-Inferno** [comment]
Same Here it also happened to Captain Jack on his stream

**Comment by sstixrud** [comment]
Fixed
