### ISSUE TITLE
Turret Targeting on Ai Grids has hickups

### ISSUE THREAD

**Issue by Abisius** [sstixrud/WeaponCore#133]
Noticed a problem with the turret targeting for non standard relation factions, so for example friendly space pirates, has some hickups.
i had it ocuring that my turrets did first shoot on a friendly space pirate grid only to stop some seconds later finding out theyre error, the diplomatic state changed after the world was loaded.
also they need around 10-15 sec to start firing on a faction that was friendly at the tiem of world loading but had become an enemy in the meantime
if the diplomatic state dont changes since load of the world the target idnetification works fine.

and othe rthing is that sometimes once some blocks of a grid out of the firing arc the grid doesnt get targetet at all, still investigating and trying to reproduce it reliably.

happening in singleplayer

**Comment by Captain-Inferno** [comment]
Same Here

**Comment by Abisius** [comment]
just made a screenshot of oen case of not targeting, manual firing lets me hit both ships, butt he turrets dont shoot from 
![20200426232503_1](https://user-images.githubusercontent.com/64340427/80320268-cd672080-8815-11ea-8422-eba581a411e8.jpg)
alone

**Comment by sstixrud** [comment]
@Abisius please get me that world.

**Comment by Abisius** [comment]
here comes the worldupload, changed a bit since i made the screenshot cause i have build further on the base.
made a extrasave ove rsave as to upload it cause steam doesnt wanted me to upload it with its backups and the 106mb size due to oversize (why is that oversized?).
https://steamcommunity.com/sharedfiles/filedetails/?id=2077337578

**Comment by sstixrud** [comment]
I am not seeing an issue.  I suggest you setup the world exactly as it needs to be to exhibit the issue so I dont have to search for it

**Comment by Abisius** [comment]
will take a save and make a new upload once i have the ship hovering above my base without beeing shot up again, might take a while.

**Comment by sstixrud** [comment]
Should be fixed.
