### ISSUE TITLE
Everything works but the guns shooting

### ISSUE THREAD

**Issue by VanillaSoup** [sstixrud/WeaponCore#137]
As the title says, everything will happen, but no bullets shot. No matter what setting i have it on, or how I am telling the weapon to shoot, it will slave and a muzzle flash will appear but with no physical bullet leaving the barrel

**Comment by sstixrud** [comment]
Create a fresh world (Easy earth )with no other mods, add just  Vanilla replacement WC mod.  Add an enemy grid nearby, then post your log files here.
