### ISSUE TITLE
Toggle Click To Fire Disappears

### ISSUE THREAD

**Issue by Toobyular** [sstixrud/WeaponCore#138]
Occasionally the "Toggle Click To Fire" option disappears entirely from a server (MP). Usually restarting the server helps, but not always. Here are two screenshots of the issue. The first screenshot is when the bug presents itself. The second was the exact same save file with same exact mods, but after a server restart. I've attached my last three log files. Sorry it wasn't just one but I don't know which one has the error? 

https://steamuserimages-a.akamaihd.net/ugc/1001431857112028412/0783F8CB75819AC39CFC96BBA0E4121388131F36/

https://steamuserimages-a.akamaihd.net/ugc/1001431857112048633/FEB28D46C9AB04D676E4D97B6C8B13D15947571A/

[stats-04-27-20_22-07-04.log](https://github.com/sstixrud/WeaponCore/files/4543708/stats-04-27-20_22-07-04.log)
[stats-04-27-20_22-51-28.log](https://github.com/sstixrud/WeaponCore/files/4543709/stats-04-27-20_22-51-28.log)
[stats-04-27-20_23-01-48.log](https://github.com/sstixrud/WeaponCore/files/4543711/stats-04-27-20_23-01-48.log)

**Comment by Toobyular** [comment]
Just loaded server/MP save file back up and toggle click to fire was gone. Here is the log file from that exact instance just now.

[stats-04-27-20_23-23-23.log](https://github.com/sstixrud/WeaponCore/files/4543744/stats-04-27-20_23-23-23.log)

**Comment by sstixrud** [comment]
You need to include your debug.log, not stats.log.  Also is this a dedicated MP server or player hosted?

**Comment by sstixrud** [comment]
@Toobyular

**Comment by Toobyular** [comment]
> 
> 
> You need to include your debug.log, not stats.log. Also is this a dedicated MP server or player hosted?

Where do I find that? Also, player hosted

**Comment by Abisius** [comment]
> 
> 
> > You need to include your debug.log, not stats.log. Also is this a dedicated MP server or player hosted?
> 
> Where do I find that? Also, player hosted

debug.log is in
C:\Users\Username\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore
so basically in the same folder than the stats.log

**Comment by Toobyular** [comment]
Here are the last three from last night. Next time the error happens I will make sure to try to immediately grab a debug log for it

[debug-04-28-20_01-36-34.log](https://github.com/sstixrud/WeaponCore/files/4548605/debug-04-28-20_01-36-34.log)
[debug-04-28-20_01-38-06.log](https://github.com/sstixrud/WeaponCore/files/4548606/debug-04-28-20_01-38-06.log)
[debug-04-28-20_01-40-12.log](https://github.com/sstixrud/WeaponCore/files/4548607/debug-04-28-20_01-40-12.log)

**Comment by Toobyular** [comment]
That didn't take long, heh. Don't know if you need the time stamped one or anything else, so here is a time stamped one and the "debug" file as well.

[debug-04-28-20_14-42-15.log](https://github.com/sstixrud/WeaponCore/files/4548741/debug-04-28-20_14-42-15.log)
[debug.log](https://github.com/sstixrud/WeaponCore/files/4548744/debug.log)

**Comment by Toobyular** [comment]
Upon further testing it appears that the option for Click to Fire can disappear for some grids and not others on a server.

**Comment by sstixrud** [comment]
is it happening for all players, just the host, or all players but the host?

**Comment by blitz2190** [comment]
could you also please provide a world file with this happening so I can replicate it.

**Comment by Toobyular** [comment]
You looking for a zipped folder of the entire save file, or one of the files inside of it in particular?

I don't know if it happens for anyone else, but I can try to test that tomorrow. Currently I self host and it happens to me frequently. Had all WC weapons stop working a few times tonight too, so maybe my files will help that bug seeking process as well

**Comment by Abisius** [comment]
a world save is in every case a whole folder, you can use the steam upload funciton and then a workshoplink or zip up the save folder and upload it as an alternative way

**Comment by Toobyular** [comment]
Here ya go then, zipped it up

https://easyupload.io/7d45tp

**Comment by Toobyular** [comment]
Here is a smaller save file, with fewer mods, where the error keeps happening.

I most often notice the bug with my small grid mk-1 batteries, but I've had the bug occur with all sorts of click to fire type weapons

https://easyupload.io/xhs8s3

**Comment by blitz2190** [comment]
should be fixed with https://github.com/sstixrud/WeaponCore/commit/f441ebed00f2f4e258b4ae701f5d6fb1a1976f56

**Comment by Toobyular** [comment]
Wow, awesome! Thank you so so much!
