### ISSUE TITLE
Click to fire causes disconnected grids to fire as well

### ISSUE THREAD

**Issue by BruceLeedleLeedleLeedleLee** [sstixrud/WeaponCore#139]
If i have two mechs, both with WC guns, both with click to fire toggled on, leftclicking often leads to the guns firing, even when not in the mech

**Comment by sstixrud** [comment]
@BruceLeedleLeedleLeedleLee is this fixed?

**Comment by BruceLeedleLeedleLeedleLee** [comment]
No, ill make a video to show the issue more precisely.
https://streamable.com/a5fhjv
the mod used is worthos gau 8

**Comment by sstixrud** [comment]
Thanks.

**Comment by blitz2190** [comment]
https://github.com/sstixrud/WeaponCore/commit/8ee0cf19dee605fa2ab7af8c3187e0dd3a22204b
