### ISSUE TITLE
Projectiles being set off above voxels.

### ISSUE THREAD

**Issue by JohnBeana123** [sstixrud/WeaponCore#140]
So I have a ground vehicle with a cannon on, The projectiles that are fired are colliding with the voxels but they are a few metres off the ground. If I aim higher or have a much higher vehicle the issue is resolved so it's definitely the voxels causing it. it's making the guns for ground battles completely unusable as the shells just instantly collide as soon as they are fired.

**Comment by sstixrud** [comment]
Fixed
