### ISSUE TITLE
GUID issue on my server

### ISSUE THREAD

**Issue by PantACRO4life** [sstixrud/WeaponCore#142]
Every time it save it does that

![image](https://user-images.githubusercontent.com/6643071/80672550-21bf0a00-8a7b-11ea-9d35-2749cb11e994.png)

the issue came from that files SessionFields.cs 
  internal readonly Guid CompMIdGuid = new Guid("75BBB4F5-4FB9-4230-BEEF-BB79C9811504");

**Comment by sstixrud** [comment]
We are aware of the issue and looking into the cause.

**Comment by sstixrud** [comment]
fixed in next update.
