### ISSUE TITLE
Game lockup with beam hitting voxels

### ISSUE THREAD

**Issue by TheWizardLizard** [sstixrud/WeaponCore#145]
[Video](http://protogen.ga/p/xD8nESXgqu.mp4)

Offending code: https://github.com/sstixrud/WeaponCore/blob/fdda18ee2ceca8f79c414703cfab4480ff87524f/Data/Scripts/WeaponCore/Session/SessionDamageMgr.cs#L524-L527

**Comment by sstixrud** [comment]
fixed

**Comment by TheWizardLizard** [comment]
Fixed with https://github.com/sstixrud/WeaponCore/commit/1726d8896d5c485940e76320cceb335b3805fbf2
