### ISSUE TITLE
Weapons ignore rotation/elevation setting set in config

### ISSUE THREAD

**Issue by mexpex** [sstixrud/WeaponCore#146]
Weapon of issue is of LargeMissileTurret type
WC ignores the  limits put into min/max elevation and rotation as well as the rates.
AI will still work within the limits but a user will be able to move the turret at high rotation rates and without az/el limits

**Comment by blitz2190** [comment]
https://github.com/sstixrud/WeaponCore/commit/ed88b986d1262b6575ff68e1a6aa8ff35da4617e
