### ISSUE TITLE
Energy units display in terminal

### ISSUE THREAD

**Issue by gottschalk729** [sstixrud/WeaponCore#147]
Units aren't properly displayed in WeaponCore compatible weapons. Charge values with dimension of energy are listed as "MW," a unit of power. The should instead be displayed as "MWhr" or "MWs" at the very least. The change can be made in "Data/Scripts/WeaponCore/WeaponComp/CompEvents.cs". "State.Value.CurrentCharge" has units of "MWs". If you wanted to display it in "MWhr", the energy unit Keen has chosen, That value would just need to be divided by 3600 before being converted to string. The total required energy should also be changed to an appropriate unit.

**Comment by Wortho27** [comment]
+1 to wanting this fixed

**Comment by sstixrud** [comment]
fixed

**Comment by Wortho27** [comment]
current draw should be in MW not MWs
everything else is correct
