### ISSUE TITLE
Config Option: LockOnFocus should not automatically fire on target acquisition 

### ISSUE THREAD

**Issue by TheWizardLizard** [sstixrud/WeaponCore#150]
Currently, LockOnFocus will fire the moment the user scrolls to lock a target, i would like functionality near this but without the auto fire, giving the user complete manual control to toggle fire / use mouse click fire.

https://github.com/sstixrud/WeaponCore/blob/01eecee5ef1db250311892a48987a542e88844e5/Data/Scripts/WeaponCore/Session/SessionUpdate.cs#L241-L256

**Comment by OwendB1** [comment]
I need this badly xD

**Comment by TheWizardLizard** [comment]
Closed due to inclusion into megathread
