### ISSUE TITLE
[Suggestion] Acceleration stages

### ISSUE THREAD

**Issue by lAimBotl** [sstixrud/WeaponCore#151]
Example: 
stage 1: duration, max speed, acceleration (max speed, incase you want to make it slower somewhere)
stage 2: duration, max speed, acceleration
into infinity possibly? idk lol.
or
startup acceleration duration
startup acceleration

(Base acceleration would start after startup acceleration time is over. )

or
if you want you could base it off tracking
"tracking accel/speed"

Obviously not high priority, but would look cool with some missile launcher type weapons.

**Comment by TheWizardLizard** [comment]
This may be achievable by shrapnelling your first stage into a faster stage, and so on. At least that is how Mexpex does it with his torpedoes when they get close to a target

**Comment by sstixrud** [comment]
Yes the above is the proper way to do this, far more flexible than other possible solutions.
