### ISSUE TITLE
(Bug) *UN*merging of grids partially breaks WC on merged grids

### ISSUE THREAD

**Issue by Toobyular** [sstixrud/WeaponCore#153]
**Describe the bug:**
After un-merging and then re-merging grids some weapons, when fired, will not display any effects or play any sounds, though they still draw power (usually)

**List Steps To Reproduce:**
>Paste in merged grid(s)
>Un-merge grids
>~~Re-merge grids~~
>Try to fire weapons from both grids

^you do not have to re-merge the grids to have the bug appear

**Describe Expected behavior:**
Weapons should fire properly upon re-merging of grids

**Ship BP where you can easily reproduce bug**
https://steamcommunity.com/sharedfiles/filedetails/?id=2092700488

Additional steps/info posted in description of ship bp :)

<3 you all

**Comment by Toobyular** [comment]
This also happens in survival on dedicated survival servers when cutting a small grid ship free of the grid you built it on. 

As in building a projector/rotor construction BP thing and then cutting the new ship free from the larger grid.  

Toggle click to fire won't fire any guns until there is a server restart, though turning shoot on/off to on will still fire the guns.

**Comment by Toobyular** [comment]
Update - Toggle click to fire works sporadically for some other viewers, though not consistently. Only way I've found to consistently have click to fire/static weapons work after unmerging a grid is to perform a server restart.

Will be testing on a second dedicated server later tonight to see if it is any different from the last dedicated server.

**Comment by sstixrud** [comment]
Should be fixed
