### ISSUE TITLE
(Bug) Shields fail at under 60% grid power use

### ISSUE THREAD

**Issue by Toobyular** [sstixrud/WeaponCore#154]
**Describe the bug:**
Hey Darkstar, this is about the shield failing bug. 

As a reminder the shields on my ship are failing when grid power use is at around 60% or lower when I have the "Ignore Battery Power" box UNchecked. If I check the box then the shields no longer fail. Make sure you're in survival. I had the bug present in self hosted MP.

Here is the ship BP
https://steamcommunity.com/sharedfiles/filedetails/?id=2093698813

**List Steps To Reproduce:**
Hop in *lower* cockpit > Press # 1 > Shields will fail

**Describe Expected behavior:**
That shields don't fail at this power draw level

**Comment by blitz2190** [comment]
not a weapon core bug
