### ISSUE TITLE
(Bug) Cannot switch ammo types on MCRN PDC Turret

### ISSUE THREAD

**Issue by Toobyular** [sstixrud/WeaponCore#155]
**Describe the bug:**
The "MCRN PDC Cycle Ammo" option is absent from the game. I have tried this on both self hosted MP and on a dedicated server hosted on another machine. I have also had friend's on their own PC's replicate this error.

**List Steps To Reproduce:**
Dragging individual PDC's or the group to the hotbar simply does not ever give the option to cycle ammo types.

**Describe Expected behavior:**
Being able to cycle ammo type from the default depleted uranium rounds to the vanilla NATO containers. I would *love* a toggle button in the PDC weapon's control panel to just manually change ammo types, if that is possible.

Attached are the log files Nuke previously requested from me, sorry it took me so long to properly report this issue on your GitHub page. I can also demonstrate this, or any other of my reported bugs, on stream if you like.

[log files.zip](https://github.com/sstixrud/WeaponCore/files/4631309/log.files.zip)

**Comment by Blaylock1988** [comment]
I'm testing this right now and the ammo switching seems to work fine for me on local/offline.

**Comment by sstixrud** [comment]
This issue is due to an incompatibility between MWI and PDC.  Make sure PDC is further down on the mod list
