### ISSUE TITLE
Weaponcore weapons malfunctioning

### ISSUE THREAD

**Issue by CrysisRevelation** [sstixrud/WeaponCore#156]
I'm not sure why, but half of my weapon mods (Core or otherwise) think they are conveyor sorters and a quarter of the remainder of the weaponcore mods straight up won't fire but they will aim at targets. Here is my mod list;

https://gist.github.com/af721486bb73e8375a4019e476e67847

[Long list moved to gist -Wizard]

![20200516010028_1](https://user-images.githubusercontent.com/65436518/82111353-b2037d00-9712-11ea-9246-93e1e999a390.jpg)

What exactly am I doing wrong? I really want these mods to succeed

**Comment by killerjerick** [comment]
I had a similar mod, I fixed it by making weapons core top of my mod list

**Comment by CrysisRevelation** [comment]
> I had a similar mod, I fixed it by making weapons core top of my mod list

It is at the top. the mod list builder scrambled the mods when I copied the load order.

**Comment by sstixrud** [comment]
CrysisRevelation do me a favor and follow the steam page instructions for how to clear out mod data and redownload.  You might have a stale mod file, keen and steam are horrible about this.
