### ISSUE TITLE
(Bug) Gun will not cause damage

### ISSUE THREAD

**Issue by nclmredtea** [sstixrud/WeaponCore#157]
We have a problem in a WeaponCore accessory module(AWG WeaponCore Pack)! After a period of multiplayer combat, the gun can't cause damage to the opponent! And the other side says I didn't fire!The same is true for recreating an archive.

**Comment by TheWizardLizard** [comment]
Please adhere to the issue posting guidelines.

**Comment by TheWizardLizard** [comment]
Closed due to low overall quality of issue and lack of information
