### ISSUE TITLE
(Bug) Turrets insist upon targeting meteors

### ISSUE THREAD

**Issue by Toobyular** [sstixrud/WeaponCore#158]
**Describe the bug:**
All turrets, at least on smol grid, insist upon shooting at meteors. I've got my turrets grouped and I've told some groups to not shoot at meteors, but they all shoot at them anyways. I've never told these turrets to shoot at meteors, but they're shooting at them by default as soon as they are built. Tested on multiple dedicated MP servers. Don't get me wrong, I'm glad they're shooting at meteors by default, but they are also not listening to me when I tell them not to.

**List Steps To Reproduce:**
Build smol grid turret, watch it shoot meteor. 95% certain this happens with large grid as well, but haven't tested that today.

**Describe Expected behavior:**
I would think I could keep my guns from targeting meteors if I wanted because some ammunition is crazy expensive.

**Comment by blitz2190** [comment]
fixed with https://github.com/sstixrud/WeaponCore/commit/56de588d1920f6924e46ee559fce49e8a5173406
