### ISSUE TITLE
(Bug) Sometimes MCRN PDC Turrets no longer display firing effects

### ISSUE THREAD

**Issue by Toobyular** [sstixrud/WeaponCore#159]
**Describe the bug:**
Sometimes the PDC turrets will be firing, and we can hear them, but we don't see the bullets leaving the guns.

**List Steps To Reproduce:**
Don't know what steps to reproduce yet, but will update bug report as I discover more. Might also effect more guns than just PDC.

**Comment by sstixrud** [comment]
I believe this is fixed as well
