### ISSUE TITLE
(Bug) Fragments not doing damage in most cases.

### ISSUE THREAD

**Issue by AWG-935** [sstixrud/WeaponCore#160]
**Is this a multiplayer or singleplayer bug?**
Both

**Describe the bug:**
Fragments aren't doing damage in some cases. Unknown cause.

**List Steps To Reproduce:**

Use various weapons in the linked world, on the targets in front of the test stands. They should be able to penetrate the marked amount of heavy armour then fragment, destroying at least some of the light armour behind them, yet most do not.

**Describe Expected behavior:**
Fragments are meant to be able to damage the armour behind the targets, yet do not after penetrating the armour (on DS). On local, the shells do not appear capable of penetrating their given damage worth's of armour.

**(Optional) Additional content/log files/etc:**
https://cdn.discordapp.com/attachments/566615816913682432/712775776788807790/AWG_WCP_Test_Range.zip

**Comment by sstixrud** [comment]
fixed
