### ISSUE TITLE
(Bug) Travel sound plays instead of impact sound on hit

### ISSUE THREAD

**Issue by AWG-935** [sstixrud/WeaponCore#161]
## Is this a multiplayer or singleplayer bug?
Both

## Describe the bug:
When an impact sound is set alongside a looping travel sound, on impact the projectile plays the travel sound but with the impact sound definitions. As in, with the impact sound volume settings or pitch variance. 

## Steps To Reproduce:
Set up a travel and impact sound, then shoot something within the range of the impact sound.

## Expected behavior:
It is meant to play the impact sound on impact, and will instead play the travel sound for a split second.

### (Optional) Screenshots or videos:
https://cdn.discordapp.com/attachments/566615816913682432/713106404642127872/Space_Engineers_2020.05.21_-_20.09.34.01.mp4

**Comment by sstixrud** [comment]
fixed
