### ISSUE TITLE
(Suggestion / Enhancement) Priority for Faction rep based targeting

### ISSUE THREAD

**Issue by OwendB1** [sstixrud/WeaponCore#165]
**Is your feature request related to a problem? Please describe:**
Yes, we sometimes have issues with ships not targeting correctly because of the player based reputation system.

**Describe the solution or feature you'd like:**
Have it so when a player is within a faction it uses the faction's rep as a priority over player reputation. If the player is without a faction only then use the player reputation to decide whether to shoot or not.

**Comment by sstixrud** [comment]
No plans at this time.  For now I will replicate keens (broken) faction system in the hopes they fix it.
