### ISSUE TITLE
(Bug) Weapons stop working when a large number of players and factions are in one location

### ISSUE THREAD

**Issue by Isadorious** [sstixrud/WeaponCore#166]
## Is this a multiplayer or singleplayer bug?
Multiplayer (Torch Server)

## Describe the bug:
Weapons don't fire and the WeaponCore UI stops working, this also includes the click to shoot option in the G menu. A relog did fix these issues, I've attached the Keen and Torch logs from the server as well as my client log. This happened with around 15 players from 6 different factions within 5 km of each other. Most players were in their own ships. There was some manual adjustment of player reputation using admin tools, to ensure the players didn't shoot each other unintentionally. Estimation of around 200 guns in this area, but it could be more. The server is using MWI, Battle Cannons and Turrets & Vanilla Replacement WC mods. 

## Steps To Reproduce:
1. Get a large number of factions to jump to the same area in a server, with weapons off
2. Modify players reputation with each other to ensure they don't target each other unintentionally
3. Allow players to turn on their weapons and engage with enemy factions
4. WeaponCore UI no longer appears and weapons are unresponsive to all control

## Expected behavior:
Guns and WeaponCore UI work properly without requiring a relog. 

### (Optional) Additional content/log files/etc:

[SpaceEngineers_20200530_205443137.log](https://github.com/sstixrud/WeaponCore/files/4707420/SpaceEngineers_20200530_205443137.log)
[Torch-2020-05-30.log](https://github.com/sstixrud/WeaponCore/files/4707421/Torch-2020-05-30.log)
[Keen-2020-05-30.log](https://github.com/sstixrud/WeaponCore/files/4707422/Keen-2020-05-30.log)

**Comment by sstixrud** [comment]
@Isadorious I need the logs from the Storage/WeaponCore folder, ideally both the server and a client one.

**Comment by Isadorious** [comment]
My bad, here are the client and server WeaponCore logs from when this bug happened

[WeaponCore 30 May Client Logs.zip](https://github.com/sstixrud/WeaponCore/files/4708339/WeaponCore.30.May.Client.Logs.zip)
[WeaponCore 30th May Server Logs.zip](https://github.com/sstixrud/WeaponCore/files/4708340/WeaponCore.30th.May.Server.Logs.zip)

**Comment by sstixrud** [comment]
This should now be fixed
