### ISSUE TITLE
(Bug) AutoTurrets didnt autofire after set to group and change settings

### ISSUE THREAD

**Issue by shukari** [sstixrud/WeaponCore#167]
## Is this a multiplayer or singleplayer bug?
both

## Describe the bug:
AutoTurrets like gatlings dont fire at its own if you set it to a group and change some settings.

EDIT: **_I THINK I FOUND THE CAUSE: If it is set to UNOWNED/NEUTRAL/FRIENDLY = TRUE it doesnt fire if they are all false it fires_**
video to the bug: https://youtu.be/CW5rCTXT7P0

EDIT2: If the enemy has no weapon it also never fires? is this normal? I spawned a welder ship and change owner to space pirates the ai turrets never fire but if i place a gatling they fire?!?!
That means if this ship is equiped with a grinder it will be ignored and can grind you without protection: https://youtu.be/Mt-L5y0CVy8

## Steps To Reproduce:
1. if a autoturret (gatling or modded) is freshly build then it fires, like in vanilla at enemy grids
2. set it at a group and then change some group settings (weaponcore ui)
    - i changed fire at unowned/metor/bio/ etc.
3. now it only fires if you focus a target (i changed the focus setting multiply times)
4. deleting the group / turn the gatling of and on / unpower the hole grid doesnt help
5. the turret now only fires at focus targets

## Expected behavior:
The AutoTurret should fire like in vanilla if i didnt set it to "FOCUS TARGET"

### Screenshots or videos:
- video of the steps to reproduce: https://youtu.be/BcChMLyZBRU
- video of the problem: https://youtu.be/CW5rCTXT7P0

### Additional content/log files/etc:
- [LogsStorage.zip](https://github.com/sstixrud/WeaponCore/files/4722735/LogsStorage.zip)
- [1918681825.sbm_WeaponCore.zip](https://github.com/sstixrud/WeaponCore/files/4723081/1918681825.sbm_WeaponCore.zip)

**Comment by sstixrud** [comment]
@shukari I am not able to repeat this problem are you still seeing it?

**Comment by sstixrud** [comment]
Cannot reproduce, might be fixed, if not fixed please reopen.
