### ISSUE TITLE
(Bug) Weapons continue to fire after all targets are gone

### ISSUE THREAD

**Issue by nukeguard** [sstixrud/WeaponCore#168]
(git weapon core on public branch)

Seems to only happen with the obelisk (sorter turret, 5 of them)

will start firing as soon as you enter cockpit without a target after it has destroyed the previous target
![image](https://user-images.githubusercontent.com/30876973/83708350-17e47580-a5ea-11ea-9636-c95c06430969.png)
just fires straight from idle position

I assume this also makes the particles to not stop playing
https://streamable.com/5rwakl

near the end is where you can see it continue to fire, but most of video is showing shooting when no target, maybe it's target filtering and it just fires because the rest of the weapons are, but at the end the others stopped and obelisk just continues on.

**Comment by sstixrud** [comment]
fixed
