### ISSUE TITLE
(Suggestion / Enhancement) Noise played or looped on target lock/focus

### ISSUE THREAD

**Issue by AWG-935** [sstixrud/WeaponCore#170]
**Is your feature request related to a problem? Please describe:**
It can be difficult for some to tell if the weapon is locked onto a target, this allows for it to be certain

**Describe the solution or feature you'd like:**
A sound to play or loop, stated in the weapon's config file

Example: (Volume warning)
https://youtu.be/GUJcc7AswFk?t=11

**Comment by TheWizardLizard** [comment]
Closed due to inclusion into megathread
