### ISSUE TITLE
(FATAL) Crash System.NullReferenceException

### ISSUE THREAD

**Issue by Akanixon** [sstixrud/WeaponCore#171]
## Is this a multiplayer or singleplayer bug?
multiplayer

## Describe the bug:

> 13:23:51.2996 [FATAL]  Initializer: System.NullReferenceException: Object reference not set to an instance of an object.
> at WeaponCore.Support.GridAi.CheckAmmoInventory(MyInventoryBase inventory, MyPhysicalInventoryItem item, MyFixedPoint amount)
>    at System.Action3.Invoke(T1 arg1, T2 arg2, T3 arg3)
>    at System.DelegateExtensions.InvokeIfNotNull[T1,T2,T3](Action3 handler, T1 arg1, T2 arg2, T3 arg3)
>    at Sandbox.Game.MyInventory.AddItemsToNewStack(MyFixedPoint amount, MyFixedPoint maxStack, MyObjectBuilder_PhysicalObject objectBuilder, Nullable 1 itemId, Int32 index)
>    at Sandbox.Game.MyInventory.AddItemsInternal(MyFixedPoint amount, MyObjectBuilder_PhysicalObject objectBuilder, Nullable1 itemId, Int32 index)
>    at Sandbox.Game.MyInventory.TransferItemsInternal(MyInventory src, MyInventory dst, UInt32 srcItemId, Boolean spawn, Int32 destItemIndex, MyFixedPoint amount)
>    at Sandbox.Game.MyInventory.Transfer(MyInventory src, MyInventory dst, UInt32 srcItemId, Int32 dstIdx, Nullable 1 amount, Boolean spawn)
>    at Sandbox.Game.MyInventory.TransferOrRemove(MyInventory src, Nullable 1 amount, MyDefinitionId contentId, MyItemFlags flags, MyInventory dst, Boolean spawn, Boolean onlyWhole)
>    at Sandbox.Game.GameSystems.MyGridConveyorSystem.PullAllRequest(IMyConveyorEndpointBlock start, MyInventory destinationInventory, Int64 playerId, MyInventoryConstraint requestedTypeIds, Nullable 1 maxAmount, Boolean pullFullBottles)
>    at Sandbox.Game.Entities.MyConveyorSorter.UpdateBeforeSimulation100()
>    at Sandbox.Game.Entities.MyParallelEntityUpdateOrchestrator.UpdateBeforeSimulation100()
>    at Sandbox.Game.Entities.MyParallelEntityUpdateOrchestrator.DispatchBeforeSimulation()
>    at Sandbox.Game.Entities.MyEntities.UpdateBeforeSimulation()
>    at Sandbox.Game.World.MySector.UpdateBeforeSimulation()
>    at Sandbox.Game.World.MySession.UpdateComponents()
>    at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
>    at Sandbox.MySandboxGame.Update()
>    at Sandbox.Engine.Platform.Game.UpdateInternal()
>    at Sandbox.Engine.Platform.Game.RunSingleFrame()
>    at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
>    at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
>    at Sandbox.Engine.Platform.Game.RunLoop()
>    at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
>    at Torch.VRageGame.DoStart() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 246
>    at Torch.VRageGame.Run() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 125
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart()

## Steps To Reproduce:
happens randomly

### (Optional) Screenshots or videos:
(remove if not used)

### (Optional) Additional content/log files/etc:
(remove if not used)

**Comment by sstixrud** [comment]
should be fixed.
