### ISSUE TITLE
(Bug) Massive target lead error on gatlings after reloading

### ISSUE THREAD

**Issue by Blaylock1988** [sstixrud/WeaponCore#172]
## Is this a multiplayer or singleplayer bug?
Singleplayer (have not tested on multi or DS)

## Describe the bug:
Gatling type weapons such as Vanilla Gatling replacement and MCRN PDC have incredibly large error when resuming fire after reload on an accelerating ship. Some turrets will be firing correctly at the same time as other turrets that finished reloading with incorrect trajectory. This happened even when shooting at a station.

## Steps To Reproduce:
Put vanilla gatling replacement on ship. Fly fast around a target. Watch turrets fire, reload, and fire again with massive target lead error.

## Expected behavior:
Turrets should maintain correct firing trajectory regardless of reload or ship movement.

### (Optional) Screenshots or videos:

![image](https://user-images.githubusercontent.com/62247634/84208662-3f23c280-aa82-11ea-9592-4a0478d484f6.png)

https://youtu.be/HJUmqK5Jdu0

**Comment by sstixrud** [comment]
@Blaylock1988 can u confirm this is still an issue with most recently build?

**Comment by Blaylock1988** [comment]
Will check and report back this evening.

**Comment by Blaylock1988** [comment]
Issue is still there, appears unchanged.

**Comment by sstixrud** [comment]
fixed
