### ISSUE TITLE
(Suggestion / Enhancement) Grid Type Targeting Options

### ISSUE THREAD

**Issue by Isadorious** [sstixrud/WeaponCore#173]
**Is your feature request related to a problem? Please describe:**
There are some situations in which we find WeaponCore has to be switched out for the Keen targeting system which allows targeting of specific grid types and characters. This has been a bit of a problem when recording parts of Colony LOST as we place drones in close proximity to grids that act as set-pieces and all we want the drones to do is target players rather than the grids around them. 

**Describe the solution or feature you'd like:**
Something similar to Keen's granular targeting options where you can select if a gun should target small grids, large grids, station grids, characters etc

**Additional context:**

**Comment by TheWizardLizard** [comment]
Closed due to inclusion into megathread
