### ISSUE TITLE
(Bug) 

### ISSUE THREAD

**Issue by GalaxyGamerYT** [sstixrud/WeaponCore#175]
## Is this a multiplayer or singleplayer bug?
Multiplayer

## Describe the bug:
Turrets are turning themselves on, spawning ammo and targeting friendlies.

## Steps To Reproduce:
2 factions at peace, turrets on and no ammo in ship.

## Expected behavior:
turns on, spawns ammo and shoots other faction.

**Comment by sstixrud** [comment]
Should be fixed, please confirm.

**Comment by GalaxyGamerYT** [comment]
I can confirm it is fixed thx
