### ISSUE TITLE
(Suggestion / Enhancement) Reloading Time Left Indicator

### ISSUE THREAD

**Issue by BarryTGash** [sstixrud/WeaponCore#176]
**Is your feature request related to a problem? Please describe:**
n/a

**Describe the solution or feature you'd like:**

I'd like to see a visual cue that provides information on the time remaining for a weapon to complete reloading. This is less important for fast reloading weapons but for some of the slower weapons (upwards of 30 seconds to reload) this indicator would be extremely useful.

**Additional context:**

The visual cue could take any number of forms, from a countdown timer to a graphical indicator (similar to a loading bar marking progress to completion). If provided per group rather than per weapon, I'd probably suggest the indicator tracks the slowest reloading weapon in the group although I'd not expect many people to group dissimilar weapons in the same group anyway.

**Comment by TheWizardLizard** [comment]
Closed due to inclusion into megathread
