### ISSUE TITLE
(Suggestion / Enhancement) Third explosion type for modders, based off Explosive, but with a chance to break off blocks, similar to the jump drive explosion mod

### ISSUE THREAD

**Issue by Wortho27** [sstixrud/WeaponCore#177]
For modders, currently explosion types are either Explosive or radiant, or the AoE affects. I propose a third explosion type, (ExplosiveShrapnel ? needs a good name). This would function similarly to the Explosive damage type, but for every block that would explode, there is a chance to seperate it from the grid and fling it away from the explosion origin (see, explosive jump drive mod). This chance could either be hardcoded, or put as a 0 to 1 chance in a variable, where 0 would not change Explosive functionality, and 1 would fling away every block that would have exploded. (A value of 1 probably isn't a good idea). With this variable, you could probably do without adding the third type, and this value would control if blocks fly off or not during the process. I'm not sure how feasable this is to do however

**Comment by TheWizardLizard** [comment]
Closed due to inclusion into megathread
