### ISSUE TITLE
(Suggestion / Enhancement) Self-Damage on Shoot

### ISSUE THREAD

**Issue by AWG-935** [sstixrud/WeaponCore#178]
**Describe the feature you'd like:**
Allow for a config option that sets a damage to the weapon block per fire event, or even better, a value to ammunition to do so.

This would allow for "one and done" weapons that destroy or remove themselves in firing or after a set number of shots. 

This allows for a greater range of weapons from mine blocks using WeaponCore to ammunition that is more powerful than others, but wears down the weapon over time, making it more expensive to use.

**Comment by sstixrud** [comment]
complete
