### ISSUE TITLE
block limiter fails, and allows additional placement; crashes if added block is deleted(Bug) 

### ISSUE THREAD

**Issue by ConstyCarlos** [sstixrud/WeaponCore#179]
## Is this a multiplayer or singleplayer bug?

tested in SP

## Describe the bug:

 limit checker breaks, and allows you to place more blocks
but if you delete those blocks, the game crashes

## Steps To Reproduce:

(tested with AWG's Missile Tube contained in AWG's Weaponcore Pack)
place missile tubes on subgrid
place additional tubes on another grid
limit checker fails and allows you to place more of the tubes
deleting the added tubes crashes SE

## Expected behavior:

block placement limited; disallows you to place more of said block

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:
https://cdn.discordapp.com/attachments/566615816913682432/723981784941068388/debug.log
https://cdn.discordapp.com/attachments/566615816913682432/723981779777618021/stats.log
https://cdn.discordapp.com/attachments/566615816913682432/723981790636671066/perf.log

https://streamable.com/a1qqr6 - clip of crash

**Comment by sstixrud** [comment]
fixed
