### ISSUE TITLE
Fragmentation/Shrapnel phasing through voxels (Bug) 

### ISSUE THREAD

**Issue by ConstyCarlos** [sstixrud/WeaponCore#180]
## Is this a multiplayer or singleplayer bug?
tested in SP

## Describe the bug:
shrapnel/fragmentation from projectile phases through voxels (shrapnel with effects will not do their designated effect)

## Steps To Reproduce:
easiest: AWG's 1Pdr set to SM (smoke) shells, fire said weapon
else: any projectile with shrapnel effect 

## Expected behavior:
shrapnel hits voxel
![20200622150654_1](https://user-images.githubusercontent.com/47006058/85261094-4c877680-b49e-11ea-98dc-cc7472db00dd.jpg)
![20200622150746_1](https://user-images.githubusercontent.com/47006058/85261098-4e513a00-b49e-11ea-843e-b1f3b2871677.jpg)

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:

**Comment by sstixrud** [comment]
fixed
