### ISSUE TITLE
(Suggestion / Enhancement) - Weapon Sequencer

### ISSUE THREAD

**Issue by cgkiwi777** [sstixrud/WeaponCore#181]
**Is your feature request related to a problem? Please describe:**
WeaponCore weapon groups are difficult/unable to be sequenced (timing and firing order).
Whip's has a weapon salvo script, but he has told me it doesn't work with WeaponCore.

**Describe the solution or feature you'd like:**
A block, script, or mod feature that allows players to set firing sequences/timing of WeaponCore weapon groups, similar in capability to Whip's Weapon Salvo Script.

**Additional context:**
Whips Weapon Salvo Script:
https://steamcommunity.com/sharedfiles/filedetails/?id=1221921128
Thanks for the awesome mod!

**Comment by TheWizardLizard** [comment]
Closed due to inclusion into megathread
