### ISSUE TITLE
(Suggestion / Enhancement) Orientation Matrix for PB API

### ISSUE THREAD

**Issue by Blaylock1988** [sstixrud/WeaponCore#182]
**Is your feature request related to a problem? Please describe:**
No

**Describe the solution or feature you'd like:**
Provide target grid orientation matrix through PB API.

**Additional context:**
Normally this is accomplished through raycast, but forcing the weapon script (and user) to keep using raycast targeting on top of WC is a severe hindrance.

**Comment by TheWizardLizard** [comment]
Closed due to inclusion into megathread
