### ISSUE TITLE
Group Config Does not Update Groups

### ISSUE THREAD

**Issue by martin951** [sstixrud/WeaponCore#183]
## Is this a multiplayer or singleplayer bug?

Singleplayer

## Describe the bug:

Middle mouse button menu does not update created groups. I have to reload the world.

## Steps To Reproduce:

Get in your ship and define new group. It won't update.. reload world.. woala.

I don't know what else to write or how else to put it, it's pretty straight forward.

**Comment by martin951** [comment]
I really don't know how else to put it, it's really simple.

**Comment by sstixrud** [comment]
@martin951 please test the new 1.3 beta version and let me know if this fixed.

**Comment by sstixrud** [comment]
fixed
