### ISSUE TITLE
(Bug) Weapon does not target or fire

### ISSUE THREAD

**Issue by hades200082** [sstixrud/WeaponCore#186]
## Is this a multiplayer or singleplayer bug?
Single player

## Describe the bug:
I placed a Magnetic Coil Cannon on a test platform with a target ship set to Space Pirate faction and the turret did not target or fire at the enemy ship.

The enemy ship was target locked and had turrets. Hud showed a threat score of 3 - Battleship class.

Removing the turret and replacing it with creative tools got it working.

Debug log file showed the following error:

```
07-12-20_10-39-20-918 - Exception in RemoveAmmo: System.NullReferenceException: Object reference not set to an instance of an object.
   at VRage.Game.MyObjectBuilderExtensions.GetId(MyObjectBuilder_Base self)
   at Sandbox.Game.MyInventory.AddItems(MyFixedPoint amount, MyObjectBuilder_Base objectBuilder, Nullable`1 itemId, Int32 index)
   at Sandbox.Game.MyInventory.Add(IMyInventoryItem item, MyFixedPoint amount)
   at WeaponCore.Session.RemoveAmmo() - False - False - False
```

But the timestamp on that error was earlier than my test so not sure if it's related.

## Steps To Reproduce:

Have not been able to reproduce so far.

## Expected behavior:
Turrets should target and fire at hostile ships as per vanilla turrets if no other settings are configured.

The main issue is that in a survival game with others it may not be a simple task to remove and replce the weapon, especially if AwwScrap is in the mod list.

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:
[wc-logs.zip](https://github.com/sstixrud/WeaponCore/files/4908328/wc-logs.zip)

**Comment by TheWizardLizard** [comment]
Please fill in the name field when you post future issues.

**Comment by sstixrud** [comment]
This issue may be fixed, reopen if still an issue.
