### ISSUE TITLE
Small Bugs Thread - Your issue does not need its own thread!

### ISSUE THREAD

**Issue by AtlasTheProto** [sstixrud/WeaponCore#188]
# PUT YOUR SMALL ISSUES HERE

This thread will be home to the smaller, simpler bugs in WeaponCore, stuff like "it doesnt work" should probably be put in here.

If you believe your bug is of higher priority, go ahead and make an issue of your own.

### If the title is just "(Bug)" it will be closed immediately

Above all...
# LEAVE LOGS!!!

**Comment by Majikmonster** [comment]
I'm not sure if this counts as a "small" bug, but here you go.

HUD elements missing:
https://github.com/sstixrud/WeaponCore/issues/204#issue-686463916

This also prevents me from using tracking projectiles like missiles and torpedoes..

**Comment by TheWizardLizard** [comment]
ideally this thread should be a replacement for you making a post in the first place

**Comment by Majikmonster** [comment]
HUD elements still missing after following all steps in bug report guide. Twice.
These are the HUD elements that are missing, and also the blue-red target circle.
![1989583682_preview_targetting](https://user-images.githubusercontent.com/51390907/92006327-94ceda80-ed12-11ea-84d0-0b9d0fc481f5.png)

- Running WeaponCore 15(7) in singleplayer

Is there something missing from the howto guide regarding this, like you have to have in-game signals set to fully visible on world load or some other obscure setting?

Here are the logs:
[Majikmonster_logs_1918681825_WeaponCore-09-02-20.zip](https://github.com/sstixrud/WeaponCore/files/5163321/Majikmonster_logs_1918681825_WeaponCore-09-02-20.zip)

**Comment by sstixrud** [comment]
@Majikmonster those will only show up if you mouse wheel through targets and there are enemy targets nearby.

**Comment by Majikmonster** [comment]
My HUD issues remain the same.

I tried all the mouse wheel functions. Clicking, scrolling, even side-to-side action. First there was only one enemy grid, then I added another. I kept going with different types of blueprints both mobile and stations. I tried targeting using cockpits, control seats, and remote controls. I tried being in different factions in the world all hostile to the grids I wanted to target. I tried all combinations of antennas and beacons and system block amalgamations that might be considered a ship just to try and get the mod to recognize a class or mere existence of a grid with or without weapons. 1st person and 3rd person. Nothing except the crosshair and its functions seems to work.

This latest attempt was tested with Weapon Core 1.5(15). All enemy grids were no more than 1.5km away, and were indeed registered to a hostile faction. No indication that any target was available at all no matter how many or what type of enemy grid it was, no matter how much I used the mouse wheel, no matter how many times I reloaded the game or wiped my mod caches and followed the troubleshooting instructions, and has not worked at any capacity throughout all versions of the mod I've tested.

Is there a command or something I can use to debug the mod? Right now I'm getting 0 feedback as to if or how the HUD or targeting works in game, so I have no clue why things like those icons don't appear or why target selection doesn't happen. I'm stumped.

**Comment by sstixrud** [comment]
Majikmonster I am not sure why you are having this problem.  Try creating a new world with just Vanilla Replacement WC mod and no other mods and see if you still have this problem.  If so create a video of your experience and what you are trying to do and share it here.   I have no heard of anyone else having this problem.

**Comment by Majikmonster** [comment]
Apparently it's just Steam sucking so bad at downloading files correctly that it takes almost a dozen tries to get it to actually work. Clearing the mod caches causes all my other mods to throw cascades of errors, but it seems to have fixed WC and not borked a few others. I guess we can chalk this up to "Steam is bad and it should feel bad". Sorry for the dead-end "bug" report.

**Comment by sstixrud** [comment]
glad its working, often times when clearing mod cache results in that behavior you need to have steam check your game file integrity.

**Comment by AutoMcDonough** [comment]
EMP effect seems to be happening randomly on the whole target grid, not on the blocks closest to where the weapon hits.

**Comment by Kolez** [comment]
Automatic targeting problem from steam comments - After last update 1.6(1) most of my turrets stop automatically targeting enemies when they come into the weapon range. Sometimes they don't even start shooting until i change something in the weapon setting or use aim - then they immediately start firing. That causing a lot of problems in our base when defending against enemies. I'm adding link to my backup save from dedicated server. Let me know is you need more information
https://1drv.ms/u/s!Ar5r9XDmGF1hgsN6-UjGPUybLR1Bkw?e=lMOuzK

**Comment by ChubbyPitbull** [comment]
I ran into the same issues as Kolez on my single player save. My turrets always work perfectly if I manually select targets, but a base left to itself often won't fire until the enemy is in very close range if at all. Not sure if related, but it seems like a lot of times enemy grids will get disabeld and go out of line of sight of the turrets, but still within range, and turrets may get "stuck" tracking these grids even if they're not aiming at them.

Here is a save where I was salvaging a CORRUPT drone within ~1 km of my base, and 3 CORRUPT SALVAGE drones were able to come right up to me with no shots fired from the base. Base is armed with an XB3 Pulse and XB3 Beam laser from Mexpex's WeaponCore pack (4km max range), several PDX Lasers from MA WeaponCore WeaponPack (3.5km max range), 300mm Auto Cannons from BCAT WeaponCore (2.2km max range), and 30mm Aden guns from BCAT WeaponCore (1km max range).

https://drive.google.com/file/d/1MWdiSVj8rbZ8XESTPOAmBxETrF1mn35K/view?usp=sharing

**Comment by Kolez** [comment]
If you have any idea what could causing that i should try to suspend that mod and test it or if there is any way how to provide more accurate logs/debug files let me know.  Just little funny, few days back the turrets was such hungry for kills that they don't stop before nothing :D  (same mods , same server) -> https://www.youtube.com/watch?v=P8K3QPHYhAk

**Comment by Kolez** [comment]
Now after i cleaned the save folder/re-download all mod  - > updated version of WC to 1.6(2) the turrets started working as intended... I have not clue what was the problem, mods are same as before just redownloaded. I hope it was just misfunction in 1.6(1) ... :?  I'll see and let you know in case i encounter same problems again.

**Comment by Abisius** [comment]
i noticed that there is a slight problem that form time to time causes weapons to fire through allied ships, even docked ones that are docked to the same grid from that the weapon is firing.
most time this happens is with guided weapons.
atm i am trying to get it reliably replicated to provide a log that isnt from a 4 hour playtime.

**Comment by Abisius** [comment]
so it seams as if i found a way to reproduce it, the weapons dont fire if a block compeltly blocks theyre line of sight but fire if the line of sight is only partially blocked which then in return causes the block to get hit with the shot the weapon fires.
tried it with the vanilla replacement and some other weapons so far.
easiest to use for the reprodution is to place a wind turbing in the way of the shot.

![20201130224256_1](https://user-images.githubusercontent.com/64340427/100669727-1eb43100-335e-11eb-8824-ca1c5493eec8.jpg)
![20201130224254_1](https://user-images.githubusercontent.com/64340427/100669728-1fe55e00-335e-11eb-9cbe-d60a0075565d.jpg)

[debugdevelop.log](https://github.com/sstixrud/WeaponCore/files/5618882/debugdevelop.log)
