### ISSUE TITLE
(Bug) "Toggle Click To Fire" not working.

### ISSUE THREAD

**Issue by 1hexon** [sstixrud/WeaponCore#190]
## Is this a multiplayer or singleplayer bug?
singleplayer.

## Describe the bug:
no weapon will fire with "Toggle Click To Fire", but will fire using "Shoot once", "Shoot On/Off".
turrets will fire when controlled

## Steps To Reproduce:
fresh world, load WC and Vanilla Replacement, make grid(small or large), place power source, control block, any weapon.
hotbar said weapon(s) in controlblock. 

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:

**Comment by sstixrud** [comment]
fixed
