### ISSUE TITLE
(Bug) Clients weapons in local MP won't fire after one shot (with each ammo).

### ISSUE THREAD

**Issue by JohnBeana123** [sstixrud/WeaponCore#191]
## Is this a multiplayer or singleplayer bug?

This happens to clients in a local host world.

## Describe the bug:
Upon firing a gun, all seems well. However when you try and fire again it does no recoil, particles, damage or show the tracer. The only thing that appears is the reloading text at the top right. If you try firing yet again it still won't work; however upon switching to a different ammo you can then fire another shot, and then it breaks again. Switch to another ammo, works for one shot then stops again. Etc etc

## Steps To Reproduce:

Fire gun as client, should be fine, fire again and it wont work. Switch to a different ammo and fire and you'll see that it works again for one shot then breaks again after reloading.

## Expected behavior:

Guns should be able to fire more than one shot

### User Error Report (if Weapon-Specific) and log files

Happened hours ago and I don't have any friends available to test with at this time. I'll be sure to get a log file when I am next testing and reply here with it.

**Comment by sstixrud** [comment]
This issue is now fixed.
