### ISSUE TITLE
(Bug) 

### ISSUE THREAD

**Issue by kieliananpuna** [sstixrud/WeaponCore#192]
## Is this a multiplayer or singleplayer bug?

Both

## Describe the bug:

When the "WeaponCore - Replace Vanilla Weapons - MP!!!" by NukeGaurd is installed the mouse sensitivity while manually controlling the gatling turret is significantly reduced. This effects all gatling turrets in the game.

## Steps To Reproduce:
Install both Weapon Core and the vanilla weapon replacement mod
Manually control turret
Move mouse around

## Expected behavior:
Turret sensitivity will be lower than compared to base game turret sensitivity

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:

[1918681825.sbm_WeaponCore.zip](https://github.com/sstixrud/WeaponCore/files/4969337/1918681825.sbm_WeaponCore.zip)

**Comment by nukeguard** [comment]
I may be able to fix this, they are really slow to turn in manual control

**Comment by nukeguard** [comment]
fixed manual control speed
