### ISSUE TITLE
Server issue with weaponcore

### ISSUE THREAD

**Issue by umb694** [sstixrud/WeaponCore#196]
## Is this a multiplayer or singleplayer bug?
Multiplayer, private server 

New ip: 186.233.186.214:29314
Name: Adventureland

Steam name: UMB694

## Describe the bug:
Weaponcore doesnt function. New groups dont work, old groups show in group selection. Weapons fire without notice or visual, unable to control manual turrets, some turrets dont function at all. 

## Steps To Reproduce:
In game, multiple players experiencing the same exact bugs. Enemies dont work as well. Unable to generate a report on the vanilla weapons.

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:
[debug.log](https://github.com/sstixrud/WeaponCore/files/5013709/debug.log)
[net.log](https://github.com/sstixrud/WeaponCore/files/5013711/net.log)
[perf.log](https://github.com/sstixrud/WeaponCore/files/5013712/perf.log)
[stats.log](https://github.com/sstixrud/WeaponCore/files/5013713/stats.log)
[stats (server).log](https://github.com/sstixrud/WeaponCore/files/5013721/stats.server.log)
[stats-08-02-20_19-04-37.log](https://github.com/sstixrud/WeaponCore/files/5013724/stats-08-02-20_19-04-37.log)

**Comment by sstixrud** [comment]
This issue should now be fixed.
