### ISSUE TITLE
Player gets kicked while connecting

### ISSUE THREAD

**Issue by Akanixon** [sstixrud/WeaponCore#197]
## Is this a multiplayer or singleplayer bug?
multiplayer

## Describe the bug:
Player gets kicked while connecting to the server with the following error:
[ERROR]  Keen: System.InvalidCastException: Unable to cast object of type 'WeaponCore.Packet' to type 'WeaponCore.FocusPacket'.

## Steps To Reproduce:
Randomly appears on grids that had no problems before

## Expected behaviour:
User get kicked while connecting

### User Error Report (if Weapon-Specific) and log files
Zip up that folder and link it here:
[1918681825.sbm_WeaponCore.zip](https://github.com/sstixrud/WeaponCore/files/5020694/1918681825.sbm_WeaponCore.zip)

**Comment by sstixrud** [comment]
Should be fixed.
