### ISSUE TITLE
Wilky926 Crash report

### ISSUE THREAD

**Issue by Wilky926** [sstixrud/WeaponCore#198]
## Is this a multiplayer or singleplayer bug?
Multiplayer, Dedicated server on Nitrado

## Describe the bug:
The Tellion Dual Battery's have no option to fire, only control.  On clicking to control them it immediately crashes to dekstop 

## Steps To Reproduce:
as above.

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:
[SpaceEngineers_20200816_144219899.zip](https://github.com/sstixrud/WeaponCore/files/5082545/SpaceEngineers_20200816_144219899.zip)

**Comment by sstixrud** [comment]
This is confirmed to be with the MWI weapon packet, it is being worked on.  Closing ticket.
