### ISSUE TITLE
Minimum Arming Distance

### ISSUE THREAD

**Issue by Beesoldier** [sstixrud/WeaponCore#199]
Say you fire a missile but there is something in the way of the trajectory towards the target, say a weapons-door for example is closed, you dont want it to do full damage of course, only arm when its a certain distance away

Solution: Projectile that is set to DetonateOnEnd also has the option of not spawning shrapnel otherwise.

Personally i want to make a set of futuristic cannons that only do full damage at a certain distance because they are considered sniper weapons, the player has to use other weapons to defend himself up close

**Comment by sstixrud** [comment]
Added MinArmingTime, this affects both DetonationOnEnd spawning of shrapnel.
