### ISSUE TITLE
Enhancement to the way PullField area effect works to make it more consistent

### ISSUE THREAD

**Issue by Qarannia** [sstixrud/WeaponCore#200]
**Is your feature request related to a problem? Please describe:**
It's not a problem as such, more a suggestion for an improvement to an existing feature. Currently the PullField area effect requires a value for AreaEffectDamage. This appears to have variable results depending on the size and speed of the ship being pulled. A large ship will not be affected at all by a pull field with low AreaEffectDamage and at the opposite end a small ship with a large pull field applied to it will be flung past the centre of the field and out at high speed.

**Describe the solution or feature you'd like:**
My suggestion is for a "self-adapting" pull field that gets the mass, thrust, or whatever grid variable it counters, of the grid and then pulls the grid to the centre of the field and holds it in place. The value in AreaEffectDamage could be used as an upper limit of the force that the pull field would apply to the grid. This would allow weapon modders to decide how powerful the weapon should be at its max / how many projectiles would be needed. Need to stop a larger ship? Fire more weapons.

**Additional context:**
This could also be applied to something like a tractor beam, if it would be possible to use WeaponCore to have a turret spawn a pull field around a ship and then move it to a location x metres from the turret. NukeGuard's excellent Tractor Beam mod does something like this but the field strength needs to be set manually which is almost impossible because you have to guess the mass of the grid that you're pulling. And if you're salvaging then the grid mass would change dynamically as well.

**Comment by sstixrud** [comment]
AreaEffect will not act like a multiplier of the target mass.  i.e. a value of 1 will apply a force equal to the resting mass of the target.
