### ISSUE TITLE
Possible mod incompatability

### ISSUE THREAD

**Issue by T-Roox** [sstixrud/WeaponCore#201]
## Is this a multiplayer or singleplayer bug?
it is a singleplayer bug

## Describe the bug:
I originally reported this to Wizard, the creator of the Atlas Superlaser. They asked me some questions, and they said they reported it to you. But basically, nothing about weaponcore is working, the hud, middle mouse button, nothing. Im sending this report to see if it would be helpful to have my mod list.

## Steps To Reproduce:
I'm not really sure of the steps, but I guess it would be to install a certain mod in my mod list

## Expected behavior:
It just, doesnt work, nothing about it.

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`
[1918681825.sbm_WeaponCore.zip](https://github.com/sstixrud/WeaponCore/files/5104311/1918681825.sbm_WeaponCore.zip)
[1918681825.sbm_WeaponCore.zip](https://github.com/sstixrud/WeaponCore/files/5104320/1918681825.sbm_WeaponCore.zip)

Zip up that folder and link it here:

**Comment by Kolez** [comment]
Automatic targeting problem from steam comments -  After last update 1.6(1) most of my  turrets stop automatically targeting enemies when they come  into the weapon range. Sometimes they don't even start shooting until i change something in the weapon setting or use aim - then they immediately start firing. That causing a lot of problems in our base when defending against enemies.   I'm adding link to my backup save from dedicated server.  Let me know is you need more information
https://1drv.ms/u/s!Ar5r9XDmGF1hgukIHjJc75x40xy1FQ?e=W90A1h
