### ISSUE TITLE
Multi Turret Manual aim getting stuck.

### ISSUE THREAD

**Issue by pilfit** [sstixrud/WeaponCore#202]
## Is this a multiplayer or singleplayer bug?
Both

## Describe the bug:
When using a multi turret (this is probably limited to multiturrets that use designators) with manual aim or target painter when the turret reaches the mouse aiming point it will stop moving and not move again until manual aiming is turned off. this was tested with Northwind 250mm railgun turret.

## Steps To Reproduce:
Place a 250mm Turret and enter manual control for it.

## Expected behavior: 
when the turret reaches the mouse aim marker it will stop, no matter where you move the mouse the turret will not move.

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:

**Comment by sstixrud** [comment]
fixed
