### ISSUE TITLE
Continuous energy turrets getting stuck in overload.

### ISSUE THREAD

**Issue by pilfit** [sstixrud/WeaponCore#203]
## Is this a multiplayer or singleplayer bug?
Both

## Describe the bug:
When a continuous laser energy turret is firing at a target and the powergrid overloads (not enough power for the turret) the turret will get stuck constantly trying to draw that power if it looses the target (target is destroyed, moves out of range, deleted, or turret looses LOS) the turret will be stuck drawing power and this rate and keeping the powergrid in overload until either the turret is turned off and back on or extra power is added to the grid to get it out of overload.

## Steps To Reproduce:
place a laser turret such a Nuke's Octobeam laser on a grid that does not have enough power to fire it, select a target and let it start trying to shoot at it, rotate the ship so it looses LOS for the turret. here is a world already setup for this. https://steamcommunity.com/sharedfiles/filedetails/?id=2203518150

## Expected behavior:
The grid will be stuck in power overload because the weapon will be trying to draw to much power, it will never leave this state no matter how much power the turret draws it cant reach a fully charged state.

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:

**Comment by sstixrud** [comment]
fixed
