### ISSUE TITLE
HUD elements missing

### ISSUE THREAD

**Issue by Majikmonster** [sstixrud/WeaponCore#204]
## Is this a multiplayer or singleplayer bug?

Singleplayer

## Describe the bug:

The HUD icons and selected target ring supposedly in the mod (shown in the user guide and attached media on Steam) do not appear at all

## Steps To Reproduce:

- Load fresh world with Weapon Core 1.5 and WeaponCore Vanilla Weapon Replacer mods only
- Paste 2 grids of opposing factions, or 2 same grids and transfer one to opposing faction
- Enter friendly cockpit or control seat
- Use Alt to attempt selecting target in 1st person, or use Ctrl to attempt selecting target in 3rd person
- Use scroll wheel to attempt cycling targets

## Expected behavior:

- HUD icons appear in top of screen with target data as shown in example media
- Target circle on selected grid while controlling armed grid as shown in example media

### non Weapon-Specific log files

[Majikmonster_WC_1.5(0)_2020-8-26_logs.zip](https://github.com/sstixrud/WeaponCore/files/5131162/Majikmonster_WC_1.5.0._2020-8-26_logs.zip)

**Comment by Majikmonster** [comment]
Also, because the HUD target selection doesn't work, I cannot use tracking projectiles like missiles or torpedoes.

**Comment by sstixrud** [comment]
This works fine, I suspect you have a corrupted mod download.  Please follow instructions on steam page for cleaning mods.
