### ISSUE TITLE
Animation(?) setting subparts of grid in exact same spot not matter where they are placed on the grid (including muzzle empties)

### ISSUE THREAD

**Issue by lAimBotl** [sstixrud/WeaponCore#205]
## Is this a multiplayer or singleplayer bug?
Single player

## Describe the bug:
Animating doors end up going in a specific (wrong) spot? and it also seems to pull the muzzles/projectile origins too (the gun shoots out of the door/doors for some reason)
Probably easier to show with pictures . . .

how it "should" look:
![launcher](https://user-images.githubusercontent.com/10777735/92316528-80653900-efc3-11ea-8a38-53f1fa0cfce1.png)

how it looks when placed:
![launcherplaced](https://user-images.githubusercontent.com/10777735/92316529-83f8c000-efc3-11ea-9662-757fe9041645.png)

how it looks when multiple on the same grid are placed(all doors are inside each other somehow? but the blocks are not inside each other):
![6Launchers](https://user-images.githubusercontent.com/10777735/92316530-86f3b080-efc3-11ea-9fdd-af1285d7aa3a.png)

If I comment out the "Animations = SLMissileLauncherAnimation," the door goes back on the model properly. (and also fires out of the weapon properly)

## Steps To Reproduce:
Idk too much, so I will just drop the files.(should be all the stuff for a "working" mod, with the blend for the weapon in question.)
[ECT Zip.zip](https://github.com/sstixrud/WeaponCore/files/5178995/ECT.Zip.zip)

(Sorry if it is just me being a noob lol)

## Expected behavior:
Even if I messed up the animations, they all wouldn't fail in the exact same spots right? since the main block is in a different spot.
I would expect them to be a block apart from each other at least, unless I did some witchcraft to somehow animate them into a exact spot every time in relation to the grid lol. (sperate grids have their own "spot" they set the doors at)

### User Error Report (if Weapon-Specific) and log files

Zip up that folder and link it here:[1918681825.sbm_WeaponCore.zip](https://github.com/sstixrud/WeaponCore/files/5178989/1918681825.sbm_WeaponCore.zip)

**Comment by sstixrud** [comment]
I suggest talking with MexPex on this.  I dont think this is a bug.

**Comment by lAimBotl** [comment]
hm, well he didn't find anything, I guess I can do a few more things to narrow it down more. . .
