### ISSUE TITLE
Push/Pull fields appear to push along world coords instead of local Ewar center coords

### ISSUE THREAD

**Issue by Blaylock1988** [sstixrud/WeaponCore#210]
## Is this a multiplayer or singleplayer bug?
Singleplayer (but probably also multiplayer)

## Describe the bug:
PushField and PullField appear to apply force along some axis other than the vector from the center of the field.
Push and pull do seem to have opposite forces at least.

ALSO,

PushField and PullField Ewar field terminates the instant a player, or the originating grid (if fired very close) comes in contact with the field. This does not happen to AnchorField nor JumpNullField.

## Steps To Reproduce:
Use this mod https://steamcommunity.com/sharedfiles/filedetails/?id=2220387797. Place a "Webber Turret". Fly ship or grid in range for it to shoot. Observe turret firing from multiple angles how grids do not push directly to or away from Ewar field center.

## Expected behavior:
PushField and PullField should apply force only in a vector that intersects the Ewar field center point.

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:
No errors from WC.

**Comment by sstixrud** [comment]
fixed
