### ISSUE TITLE
Block-based shrapnel for explosions

### ISSUE THREAD

**Issue by Wortho27** [sstixrud/WeaponCore#213]
**Describe the solution or feature you'd like:**

block based shrapnel for explosions:
- this would be a new float variable from 0 to 1, 1 being a 100% chance that a given block within an explosion is affected
- on an explosion event, get every block that was affected, and roll for a chance that this block is sent flying out from the explosion site
- this of this like the custom jump drive explosion mod, where blocks are sent flying out rather than destroyed
- would be most useful for large explosion

example use case:
big nuke style explosion, set this variable to 0.1. 10% of the blocks caught in this explosion would be [detached]/[removed and respawned] while sent flying away from the explosion site at some force

**Additional context:**
issue discussed with darkstar through discord, it was brought up months ago but lost in the works

**Comment by sstixrud** [comment]
This is now possible with phantoms or warhead settings.
