### ISSUE TITLE
Weapons with multiple ammo defs still show ammo cycle button even if only 1 ammo is HardPointUsable

### ISSUE THREAD

**Issue by TheWizardLizard** [sstixrud/WeaponCore#214]
Here is a test file, it has 7 ammos, only 1 ammo (the parent ammo in the pattern) has `HardPointUsable =true`
The cycle button is selectable in the toolbar, and it does actually cycle the ammo, not respecting `HardPointUsable` bool.

[20mmTurret.zip](https://github.com/sstixrud/WeaponCore/files/5260858/20mmTurret.zip)

**Comment by sstixrud** [comment]
fixed
