### ISSUE TITLE
(Suggestion / Enhancement) API Control to Disable All TurretAI

### ISSUE THREAD

**Issue by MeridiusIX** [sstixrud/WeaponCore#217]
**Is your feature request related to a problem? Please describe:**
N/A

**Describe the solution or feature you'd like:**
A global API control that can enable or disable AI on all automatic turrets (ideally, for all blocks / not a per block basis) - requiring players to control/fire them manually.

**Additional context:**
I would like to be able to add WeaponCore support for another mod I curate:
https://steamcommunity.com/sharedfiles/filedetails/?id=1914609249
While not a hugely popular mod, it does seem to be liked by PvP communities that try to manage battles with turret spam.

**Comment by sstixrud** [comment]
added
