### ISSUE TITLE
DistantSound Sounds loop forever

### ISSUE THREAD

**Issue by Blaylock1988** [sstixrud/WeaponCore#219]
## Is this a multiplayer or singleplayer bug?
Both

## Describe the bug:
A sound played by a weapon that has a DistantSound attributed to it does not stop the DistantSound which causes it to play forever if it is a loop.

## Steps To Reproduce:
Fire any WC gun that has a DistantSound Sound loop

## Expected behavior:
DistantSound Sounds should be stopped whenever its parent Sound is stopped.

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:

**Comment by sstixrud** [comment]
fixed
