### ISSUE TITLE
Feature request for long range artillery superweapon

### ISSUE THREAD

**Issue by AutoMcDonough** [sstixrud/WeaponCore#224]
I am interested in a screen message that says something like "Artillery shot detected" and the bullet itself would show on screen as a signal or antenna/beacon. This info would show to anyone in range, which in most cases would be everyone on the server. (At least 100km).
If indiscriminately broadcasting to the whole server is easier then I'll take it. 
Basically, firing this thing will reveal your location, and everyone online will know that someone brought out the big guns. Theoretically to watch or join a battle involving very large ships.
If that signal is screaming towards your location then it will be a special kind of fear. 
![SE dino](https://user-images.githubusercontent.com/3020791/95282324-2d331000-0827-11eb-8dc9-624474f6dc97.PNG)

**Comment by sstixrud** [comment]
added
