### ISSUE TITLE
WeaponCore API Addition: Fire events and projectile tracking 

### ISSUE THREAD

**Issue by KlimeSE** [sstixrud/WeaponCore#225]
**Is your feature request related to a problem? Please describe:**
Its currently not possible to track when a WC weapon fires, either through Keen or the WC API. Its also not possible to get / set the position of a projectile though the API

**Describe the solution or feature you'd like:**
1) An event that triggers when a weapon fires. This event could either be subscribed to per gun, or as a general event that triggers when any gun fires

2) A way to access and track existing projectiles

**Additional context:**

**Comment by sstixrud** [comment]
Added
