### ISSUE TITLE
I would like a new animation movement type: Dampened Linear

### ISSUE THREAD

**Issue by AutoMcDonough** [sstixrud/WeaponCore#227]
The idea is this:
ExpoGrowth (accelleration)
Linear for 80-90% of the move
ExpoDecay (decelleration) to slow down and stop.

There are several issues when breaking an animation move out into these separate steps, the main one being that there is no logical way to match the speeds.
The knobs I have to tweak here are distance and time (ticks). Speed isn't one of them.
Matching ExpoGrowth to ExpoDecay works pretty well for moving some things, but it doesn't scale up that well because a lot of the time ends up at the slow ends while still retaining a high speed in the middle. And it is very difficult to line this speed up with a linear move. I tried to find a good result via trial and error for a few hours this afternoon and was not successful.. When the linear move ends and the expodeay begins, there is a change in speed, and even if I get this dialed in on one part, this is not a good process to follow for all the parts or if need to tweak the overall timing/speed.

A combined equation that is mostly linear but has an accel at the start and decel at the end would be ideal to use in these cases where the part is meant to appear very heavy.

**Comment by sstixrud** [comment]
use new external animation system
