### ISSUE TITLE
ExpoGrowth and ExpoDecay are not matched for rotation speed. Also the slow end needs nerfed.

### ISSUE THREAD

**Issue by AutoMcDonough** [sstixrud/WeaponCore#228]
1. As the title says, ExpoGrowth and ExpoDecay are not matched for rotation speed. They compliment eachother perfectly for movement, but when used in rotation you can see a large change in speed when ExpoGrowth ends and ExpoDecay starts. This had not become apparent to me with the more quickly moving parts (such as the tiger cannon reload), but when slowed down it is more obvious.

2. What I mean by "Slow end needs nerfed" is that when you scale the time of these equations up, a large amount of it is spent slogging through imperceptibly small movements. So if you double the time, it does not appear twice as slow. It seems more as if it is just a little slower with a large delay at the end. (or beginning).
I'd like to see the tail end if this where speed approaches zero to be culled in a bit more. Perhaps consider if these movements are less than 0.5% or even 0.1% of the total then we have achieved the deceleration.

When testing this, putting a ExpoDecay in front of a matched ExpoGrowth going the other way should appear as if the part slows to a stop then reverses direction. Currently it appears to slow to a stop, wait for several seconds, then accelerate going the other way. If this is tweaked just right then it should be possible to get a smooth movement without the appearance of wait delay.

This video shows both issues:
https://www.youtube.com/watch?v=enJ39pOXleM&feature=emb_logo

Issue 1 is seen on the breech door opening and closing, Issue 2 is seen on the other part movements. Nearly all of them using Expo moves, only the shell movement is linear.

**Comment by sstixrud** [comment]
fixed
