### ISSUE TITLE
Programming block code editor ui broken -> update at 10/13/2020 at 11:13p

### ISSUE THREAD

**Issue by shivachirr** [sstixrud/WeaponCore#229]
## Describe the bug: after the update at 10/13/2020 at 11:13pm it appears the entire code editor in programming blocks are broken as the button ui no longer responds. i cant do anything but type in it out of the screen i have to alt-f4 the game to get out of it but all programming still runs. as far as i can tell the entire programming ui  buttons are no longer responding. still looking into this but it was pretty sudden change and your mod was the only one was updated in the time frame this starter. 

Note -  i do have alot of mods on my server but no mods alter or add to the programming blocks editor or how it functions or adds new ones. only thing i have is the control binding mod but that uses the general CP ui and works fine

edit -> i just tested with a Client MP and SP with only weaponcore mod loaded and one weaponcore capable mod( the obelisk) and still both instances the editor ui is broken

### User Error Report (if Weapon-Specific) and log files
no weapon issue found. something with the programming block broke with the update at 10/13/2020 at 11:13pm will provoid se logs 

Zip up that folder and link it here: 

Weapon core folder -> https://drive.google.com/file/d/1d_EqVUAtozZd-w5h4jLEpFsooYL2QDHx/view?usp=sharing
SE log -> https://drive.google.com/file/d/1nqgyOSGsznhyCsPqYIPMtEEAw_tYSvXA/view?usp=sharing

[1918681825.sbm_WeaponCore.zip](https://github.com/sstixrud/WeaponCore/files/5375459/1918681825.sbm_WeaponCore.zip)
[SpaceEngineers_20201013_231236391.zip](https://github.com/sstixrud/WeaponCore/files/5375461/SpaceEngineers_20201013_231236391.zip)

**Comment by sstixrud** [comment]
Not seeing this behavior.
