### ISSUE TITLE
WeaponCore weapons fire sporadically with certain weapon scripts

### ISSUE THREAD

**Issue by Starwaster** [sstixrud/WeaponCore#230]
## Is this a multiplayer or singleplayer bug?

Both

## Describe the bug:

Several PMW weapon scripts (DDS or Whip's Turret slaving script) toggle weapons on with something like 'weapon.SetValue("Shoot", toggleWeapons)' where toggleWeapons is a boolean. In stock Space Engineers, the weapon starts firing and continues firing until it the above is called with a false value or otherwise shut down through the UI.

However, with Weapon Core, the guns will fire once and then stop firing until the script signals them to fire again.

## Expected behavior:

The weapons should continue firing when triggered by the script. Note that this happens with weapon.SetValue("Shoot", true/false) and not with weapon.ApplyAction("Shoot_On") - if that one is used, the weapons stay on

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:

**Comment by sstixrud** [comment]
What api call are you using? ToggleWeaponFire should behave as you expect.

**Comment by Starwaster** [comment]
But that's a Weapon Core specific function?

What about the old stock functions? That's what the various weapon scripts out there are still using. Shouldn't the stock functions continue to behave as before? It's definitely possible for WC to work with them so as not to break existing scripts. 

As I mentioned, it DOES work with one and not the other.

**Comment by sstixrud** [comment]
@Starwaster the stock functions are not and cannot be supported.  They do not work properly.  If you want this functionality you need to use the WC API.
