### ISSUE TITLE
NullArgumentException

### ISSUE THREAD

**Issue by PlutoniumVase** [sstixrud/WeaponCore#231]
## Is this a multiplayer or singleplayer bug?
Both. The bug is in your code

## Describe the bug:
ApiBackend.cs row 234 you call the method GetTopMostParent on object that returns NULL in 3 out of 4 cases which leads to NullReferenceException

## Steps To Reproduce:
Call method GetTurretTargetTypes(IMyTerminalBlock weaponBlock, ICollection<string> collection, int weaponId = 0) with an argument of weaponBlock Turret targeting FakeTarget or Projectile

## Expected behavior:
Returns default struct

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:

**Comment by sstixrud** [comment]
Fixed
