### ISSUE TITLE
Mod not working at all, a lot of errors in f11

### ISSUE THREAD

**Issue by dertommie** [sstixrud/WeaponCore#235]
## Is this a multiplayer or singleplayer bug?

Singleplayer

## Describe the bug:

Mod is not working and spits out bugs

https://pastebin.com/SwrwDy50

Log from F11 on pastebin, im using the current version, mod is on top of the load order

**Comment by sstixrud** [comment]
This is not a bug.  You have a corrupt download or mod conflict.  Follow the directions on the steam page.
