### ISSUE TITLE
Using Push/Pull/Hold field with beams breaks SE sound

### ISSUE THREAD

**Issue by Qarannia** [sstixrud/WeaponCore#236]
## Is this a multiplayer or singleplayer bug?

Experienced and reported by other users in SP and MP, creative and survival

## Describe the bug:

When using a WC weapon that uses the Push/Pull/Hold feature, in this case a beam weapon, it breaks all the sound in SE. The sound is no longer playing but there will be occasional crackles / pops / hisses in the background as though the audio is trying to play. The WC weapon in question has no audio files so it's not a case of a corrupted audio file. Reloading the world fixes the audio again.

## Steps To Reproduce:

Use the Star Trek Stasis Beam mod in a world causes the game audio to stop working until world reload. The time taken for this to happens appears to be random.

## Expected behavior:

The mod should play its normal sound (removed a while back to see if it was mod audio causing the bug) and SE sound should continue as normal.

### User Error Report (if Weap
[1918681825.sbm_WeaponCore.zip](https://github.com/sstixrud/WeaponCore/files/5577191/1918681825.sbm_WeaponCore.zip)
[1918681825.sbm_WeaponCore.zip](https://github.com/sstixrud/WeaponCore/files/5577192/1918681825.sbm_WeaponCore.zip)

on-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:

**Comment by sstixrud** [comment]
please confirm this is still an issue

**Comment by Qarannia** [comment]
I think it's been fixed with WC2. I haven't had any complaints since releasing the new version.

**Comment by sstixrud** [comment]
fixed
