### ISSUE TITLE
Gatling gun sound bug

### ISSUE THREAD

**Issue by NightRaiderXd** [sstixrud/WeaponCore#237]
## Is this a multiplayer or singleplayer bug?

both

## Describe the bug:

makes a loud static noise

## Expected behavior:
to be a normal gatling gun noise

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:

**Comment by sstixrud** [comment]
might be fixed.
