### ISSUE TITLE
WC behaves badly with safe zones

### ISSUE THREAD

**Issue by Zyrixion** [sstixrud/WeaponCore#239]
## Is this a multiplayer or singleplayer bug?
Found in MP, likely both.

## Describe the bug:
Weapon Core turrets in (at minimum, Admin-spawned) safe zones with Shoot or Damage enabled, but not both, track enemies but fail to fire.

## Steps To Reproduce:
Create safe zone, place any WC turret, let it try to shoot an enemy.

## Expected behavior:
Having Shoot enabled in safe zone settings should, in fact, enable shooting.

**Comment by sstixrud** [comment]
This is expected with the current safecode logic.  We do not currently fully replicate vanilla behavior.
