### ISSUE TITLE
Need Menu Hint Key for forcing selected group settings.

### ISSUE THREAD

**Issue by sstixrud** [sstixrud/WeaponCore#24]

**Comment by nukeguard** [comment]
how do you force group settings, and what key is it?

**Comment by sstixrud** [comment]
from the initial menu you would cycle through the groups, stopping on the one you want to apply and hold CTRL-LEFTMOUSECLICK.  As soon as you hold control the groupname would change color and a second, more detailed hint should pop up explaining you are about to apply the current group settings to all weapons in that group.

**Comment by nukeguard** [comment]
oh ok, so an icon that says APPLY GROUP SETTINGS and below that Ctrl + LMB

**Comment by sstixrud** [comment]
roger that.

**Comment by nukeguard** [comment]
All icons updated to new style, proceeding to work on the apply group settings textures

**Comment by nukeguard** [comment]
textures completed for apply group settings, may need revisions, but closing for now
