### ISSUE TITLE
WeaponCore weapons refuse to use conveyors

### ISSUE THREAD

**Issue by Kyubiko-Kurama** [sstixrud/WeaponCore#242]
## Is this a multiplayer or singleplayer bug?
Multiplayer, but I have experienced it once in Singleplayer.

## Describe the bug:
Conveyors work with the weapons properly until a ship is copy-pasted into the world. After that, weapons won't draw ammo from containers, no matter what i do.

## Steps To Reproduce:
1. Use blueprints to paste in a ship (this only causes the glitch 1/2 of the time).
2. Copy and then paste the ship.

.
## Expected behavior:

WeaponCore weapons will no longer draw ammo from a conveyor system.

**Comment by sstixrud** [comment]
fixed
