### ISSUE TITLE
Northwinds Mod

### ISSUE THREAD

**Issue by ken2020-art** [sstixrud/WeaponCore#244]
## Is this a multiplayer or singleplayer bug?
Singleplayer

## Describe the bug:
I guess when i fight enemies and i hit any of their blocks that is related to power generation like reactor or battery

## Steps To Reproduce:
just fight any npc ships or spawned ships wait and until your weapons hit the blocks related to power

## Expected behavior:
the game starts to get stuttery if thats a word and a few seconds later the game will crash it happened 10 time already 
This is my first time reporting bugs thank you for your efforts in giving us players a great mod to enjoy the game best of luck

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:
[Space Engineers.zip](https://github.com/sstixrud/WeaponCore/files/5738494/Space.Engineers.zip)

**Comment by sstixrud** [comment]
This is not weaponcore or northwind related.
