### ISSUE TITLE
EMP area totally broken

### ISSUE THREAD

**Issue by AutoMcDonough** [sstixrud/WeaponCore#245]
The block which get disabled is randomly anywhere on grid, seems more like farthest from impact area than nearest.
![image](https://user-images.githubusercontent.com/3020791/103469644-7404a900-4d35-11eb-8792-0c815e7e688d.png)

In my case the area is set to 7.5 and the affected block appears to be a connector ~30m away

**Comment by AutoMcDonough** [comment]
Also if I delete the EMP weapon, the target never recovers.

**Comment by Beesoldier** [comment]
fix pls

**Comment by sstixrud** [comment]
fixed
