### ISSUE TITLE
PB API GetSortedThreats returns targets with type = unknown sometimes

### ISSUE THREAD

**Issue by SgtMook** [sstixrud/WeaponCore#246]
## Is this a multiplayer or singleplayer bug?
Both

## Describe the bug:
When at long range, GetSortedThreats returns DetectedEntityInfo with type=unknown. Seems to resolve when shooter grid is closer to target.

## Steps To Reproduce:

1. Install weapons and PB on grid, I used a mix of gat and rocket turrets from vanilla replacements
2. Paste enemy grid between 1 km and 1.5 km away
3. In PB, print details of the DetectedEntityInfo returned
4. Observe that the DetectedEntityInfo has type=unknown

## Expected behavior:
DetectedEntityInfo has type smallgrid or largegrid respectively

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:

**Comment by sstixrud** [comment]
expected behavior

**Comment by keleios** [comment]
Err....ok? Another problem with this particular issue is that it will report friendly grids as enemies erroneously.

**Comment by sstixrud** [comment]
It is expected behavior because that is the default value for DetectedEntityInfo when no type is found for the entity.  Enemy is also the default relation.  What is the entity name and entityID returned when you see this condition?

**Comment by sstixrud** [comment]
@keleios I did find an issue with relations and it will be fixed in the next release.

**Comment by keleios** [comment]
Issue confirmed fixed as of 30!
