### ISSUE TITLE
anti missile weapons act oddly in gravity.

### ISSUE THREAD

**Issue by pilfit** [sstixrud/WeaponCore#247]
## Is this a multiplayer or singleplayer bug?
Sp

## Describe the bug:
on planets (I could not get it to happen in space) anti projectile weapons will instantly hit the projectile they are shooting at, destroying the projectile long before the shots reach it and ignoring accuracy settings. it looks almost like it is firing a laser at it.

## Steps To Reproduce:
download test world https://www.dropbox.com/s/04xm62btvihqldi/Another%20Darkstar%20world%2C%20AMS%20bug.zip?dl=0
download latest version of NW beta from git https://github.com/pilfit/NorthWind_Weapons_beta (You NEED this, new turret is what I am testing with)

in world get in the cockpit on the station and press the toggle shoot on button on the hot bar for the turret.
use spectator cam (F8) to watch what is happening. the projectiles will be intercepted with a beam long before the bullets reach it.

## Expected behavior:
Expected behavior is no magic beam zapping missiles and shells out of the air!

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:

**Comment by sstixrud** [comment]
fixed
