### ISSUE TITLE
Controller/game pad support.

### ISSUE THREAD

**Issue by rocketait** [sstixrud/WeaponCore#249]
**Is your feature request related to a problem? Please describe:**
yes, the mod has removed base game functionality when using a controller.  If using a controller and the mod you can not fire a turret (controlled or with toggled click to fire) or normal weapons (unless you toggle shoot/ shoot once). Also there is no way to target or in general control weapons with this mod.

**Describe the solution or feature you'd like:**
Either check for the action, most mods seem to support the controllers without any changes as they check for what action they are trying to do. or just check at least for the right analog stick and not just the mouse input? or some other solution.  

digi's control module's mod is a nice tool for testing what controller inputs are doing what, and good example code for how to easily read controller inputs if that approach was taken.

```C#                    
if(MyAPIGateway.Input.IsJoystickLastUsed && InputHandler.gamepadBindings.ContainsKey(control.GetGameControlEnum()))
  {
      var gamepadInput = InputHandler.gamepadBindings[control.GetGameControlEnum()];

      if(xboxChars && InputHandler.xboxCodes.ContainsKey(o))
          combined.Add(InputHandler.xboxCodes[o].ToString());
      else
          combined.Add(InputHandler.inputNames[gamepadInput]);
  }
```

**Comment by sstixrud** [comment]
I am unlikely to add this myself due to time constraints and other priorities.   If someone else wants to add this I am open to a PR request.
