### ISSUE TITLE
Weaponcore Turrets shoot through walls or obstacles

### ISSUE THREAD

**Issue by Mlzu** [sstixrud/WeaponCore#251]
## Is this a multiplayer or singleplayer bug?

- Multiplayer DS

## Describe the bug:

- Weaponcore Weapons shoot or try to shoot through walls and Voxels

## Steps To Reproduce:

- [Video, should be easier to understand and follow](https://www.youtube.com/watch?v=Qu_V4DbGYGk&feature=youtu.be)

## Expected behavior:

- Turrets should know that there is an obstacle, therefore they should not shoot.
   Same for Faction Grids or friendly Grids.

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here: 
 - [Logs-Debug](https://www.mediafire.com/file/r6oiy412axmde0v/1918681825.sbm_WeaponCore.7z/file)

**Comment by sstixrud** [comment]
should be fixed
