### ISSUE TITLE
Crosshair toggle in first person

### ISSUE THREAD

**Issue by Beesoldier** [sstixrud/WeaponCore#252]
i want to use the third person crosshair toggle in first person and in camera view

it actually used to work for camera view for a while and i enjoyed it

my vehicles usually have the cockpit in the hull and i look outside via cameras, also zooming makes leading manually guided missiles and selecting targets much easier, third person crosshair is not an option because theres no third person in my scenarios

**Comment by mkaito** [comment]
I play without third person camera, and rely heavily on external cameras on my combat ships. I also use the Camera Pan mod. Being able to use the crosshair in the camera would be pretty nice.

**Comment by sstixrud** [comment]
This has been added
