### ISSUE TITLE
Dedicated server shoot through building  + bullet spawns at the wrong point for interior turrets.

### ISSUE THREAD

**Issue by skppiy4000** [sstixrud/WeaponCore#253]
## Is this a multiplayer or singleplayer bug?

Multiplayer Dedicated Server

## Describe the bug:

turrets seem to shoot friendly buildings if a enemy is behind it + positioning issues with small turrets on dedicated servers, damaging multiple ships and anything in the way.

## Steps To Reproduce:

create dedicated server, have turrets on, they aim and will shoot through friendly buildings to hit animals and players.

## Expected behavior:

For them to target but respect your own vehicles being in the way and not trying to shoot through them.

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:
[WeaponcoreLogs.zip](https://github.com/sstixrud/WeaponCore/files/5899087/WeaponcoreLogs.zip)

[Recreation.zip](https://github.com/sstixrud/WeaponCore/files/5899086/Recreation.zip)

**Comment by sstixrud** [comment]
Should be fixed

**Comment by skppiy4000** [comment]
Unfortunately it is not fixed, bullet spawns for interior turrets has been
fixed.
