### ISSUE TITLE
Turret stops firing on dedicated server.

### ISSUE THREAD

**Issue by skppiy4000** [sstixrud/WeaponCore#254]
## Is this a multiplayer or singleplayer bug?

Multiplayer (haven't tested in SP)

## Describe the bug:

Large gatling turrets from replacement mods not shooting down meteors or even firing at all sometimes at random

## Steps To Reproduce:

Place gatling turret have a dedicated server run for a while eventually at random it will stop reacting at all, I only even noticed this because large turrets weren't targeting meteors.

## Expected behavior:

Turret to shoot at targets regardless of time

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:

[WeaponCore.zip](https://github.com/sstixrud/WeaponCore/files/5903405/WeaponCore.zip)

**Comment by skppiy4000** [comment]
Also noticed that turrets will not target meteors at all.

**Comment by sstixrud** [comment]
They are shooting meteors fine for me.

**Comment by JesseWTF** [comment]
Also an issue I've been having, this seems to happen after the Dedicated server's been running for a couple(3-4) hours, other than that nothing else to go on really as the logs don't seem to indicate anything being wrong with the turrets themselves.

**Comment by JesseWTF** [comment]
I've decided to reinstall WeaponCore both on the client and the server but the issue still seems to come up after a few hours of gameplay, so I've gathered some debug logs with the guns in question in the hopes that this is an issue that can get solved.

@sstixrud Could you take another look?

[WeaponCore.zip](https://github.com/sstixrud/WeaponCore/files/5998377/WeaponCore.zip)
