### ISSUE TITLE
Fixed Weapon Barrels not rotating

### ISSUE THREAD

**Issue by Ash-LikeSnow** [sstixrud/WeaponCore#255]
## Is this a multiplayer or singleplayer bug?

Both

## Describe the bug:

Barrels of fixed weapons of type SmallGatlingGun fail to rotate.

## Steps To Reproduce:

Load empty world with Vanilla Replacement mod; place and fire small gatling gun.

## Expected behavior:

Barrel should rotate; it does not.

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:
[1918681825.sbm_WeaponCore.zip](https://github.com/sstixrud/WeaponCore/files/5939068/1918681825.sbm_WeaponCore.zip)

**Comment by sstixrud** [comment]
Is this fixed?

**Comment by Ash-LikeSnow** [comment]
Negative.

**Comment by sstixrud** [comment]
fixed
