### ISSUE TITLE
(Suggestion / Enhancement) PB Api access to current selected target

### ISSUE THREAD

**Issue by glennfu** [sstixrud/WeaponCore#256]
**Is your feature request related to a problem? Please describe:**
Currently you can list all targets, sorted by threat, but you don’t know which the system is currently focused on. 

**Describe the solution or feature you'd like:**
It would be great if we can get/set the current target vis the api. 

**Additional context:**
Right now I’m displaying information about my target on an LCD which is really helpful and neat but I can only guess the target when one is close and the rest are far. When multiple targets are close things break down since I don’t have access to this info. Having the ability to set the target would also be amazing for adding some combat intelligence to my scripts.

**Comment by Allen-Wrench** [comment]
You can set the target using SetAiFocus(), and also get the current target using GetAiFocus().

**Comment by glennfu** [comment]
Ahh you're right! I couldn't get that to work but I realized you have to pass it the `EntityId` of a weapon to make it work. I was expecting something more "global" since you only get 1 target reticle on your hud. Thank you!
