### ISSUE TITLE
None looping barrel particle bug

### ISSUE THREAD

**Issue by pilfit** [sstixrud/WeaponCore#258]
## Is this a multiplayer or singleplayer bug?
Both

## Describe the bug:
None looping barrel particle effects only work in space on the empty world, some other world types and anywhere near a planet and the particle effects stop working.

## Steps To Reproduce:
world included, turn shoot on for the weapon on the ship and fly toward the moon, when you start getting closer the barrel particles will stop showing. Uses Northwind Beta GIT version.

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:
World File https://www.dropbox.com/s/8cmcue4p3g1mr6f/PlanetParticle%20Bug%20world.zip?dl=0
Northwind Beta git https://github.com/pilfit/NorthWind_Weapons_beta

**Comment by sstixrud** [comment]
fixed
