### ISSUE TITLE
[Feature Request] Damaging Voxel

### ISSUE THREAD

**Issue by KuroshiShirone** [sstixrud/WeaponCore#26]
It would extraordinary if you could add API to make a certain type of voxel damage grids in its proximity, for Magma and similar destructive Planet materials

**Comment by sstixrud** [comment]
I can see us adding the API capability for another mod to invoke/uninvoke an area effect damage field when requested by another by another MOD via api, but I don't see adding this logic to voxels themselves.

**Comment by KuroshiShirone** [comment]
That would already be more than I would have ever hoped for. If you could
implement this at some point that would be greatly appreciated

**Comment by TheWizardLizard** [comment]
Closed due to inclusion into megathread
