### ISSUE TITLE
WeaponCore Weapons Shoot Through Player

### ISSUE THREAD

**Issue by Final57** [sstixrud/WeaponCore#260]
## Is this a multiplayer or singleplayer bug?
- Reproduced in a creative singleplayer world
- Occurs in local hosted, and dedicated server hosted worlds

## Describe the bug:
When a viable target grid is within range of a given weapon turret, and that target grid is obscured from the turret by voxel material, the turret will turn to fire at the target if a player (the owner) passes through the direct line between the turret and the target.

## Steps To Reproduce:
- Create a grid with a turret (and ammunition if necessary)
- Create a target grid with targetable blocks (decoys, cockpits, batteries, antenna were tested) within range of the turret grid
- Place an asteroid between the turret grid and the target grid
- Change the target grid ownership to space pirates
- As a targetable player (owner of the turret grid) approach the line between the turret and the target grid
- Once lined up the turret should turn to fire on the player attempting to fire at the target

## Expected behavior:
- The player will be shot
- The first time in a session you pass across this targeting line, you will note a combat log entry for an interaction with the target grid
- There will not be a log entry describing the turret grid targeting the player

### User Error Report (if Weapon-Specific) and log files
Provided test world and have included related logs from last testing session.  
Steps for using the test world if player is not spawned in at the med bay.
- Join WeaponCore test faction
- Spawn at med bay
- Copy GPS co-ordinates from LCD with reproduction steps
- Approach GPS location
- Get shot

Zip up that folder and link it here:
[WeaponCore Test - Final57 20210219.zip](https://github.com/sstixrud/WeaponCore/files/6012348/WeaponCore.Test.-.Final57.20210219.zip)

**Comment by sstixrud** [comment]
fixed
