### ISSUE TITLE
 Turrets shoot through friendly grids to attack target

### ISSUE THREAD

**Issue by davidfroth** [sstixrud/WeaponCore#261]
## Is this a multiplayer or singleplayer bug?

Both singleplayer and dedicated server

## Describe the bug:

Turrets will shoot through friendly grid to attack enemy grid.  Turret shoots slowly when friendly grid is in line of sight, hitting the friendly grid.  When friendly grid is no longer in line of sight the turret shoots at normal fire rate

Used fresh install of WeaponCore after clearing mod cache.  Using only WeaponCore and Replace Vanilla Weapons.  Problem persists with all other WeaponCore mods I've tried.  Every weapon I've tried exhibits similar behavior.  

## Steps To Reproduce:
  
- Create a grid with a turret 
- Create a target grid with target-able blocks (antenna etc)
- Change the target grid ownership to space pirates
- Create target-able friendly grid (antenna etc) and place in line of sight of turret and enemy gird
- The turret will attempt to shoot through friendly gird to attach enemy 

Simple demonstrating issue attached

## Expected behavior:

Turrets do not shoot friendly grid.

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:
https://1drv.ms/u/s!Am4hVYl5yRLEhKMvpgu7YPPRCD0JWA?e=s2hMpY

**Comment by sstixrud** [comment]
fixed
