### ISSUE TITLE
Ammo eating bug with Defense Shields.

### ISSUE THREAD

**Issue by pilfit** [sstixrud/WeaponCore#262]
## Is this a multiplayer or singleplayer bug?
Both

## Describe the bug:
when shields are installed on a grid some fixed hybrid weapons will eat all the ammo in the cargo system when trying to reload, failing to reload and deleting large amounts of ammo.

## Steps To Reproduce:
Download the world file, use with NW Beta local copy. In world place the ammo in your inventory into the cargo container on the ship in front of you. Ammo will all vanish. Ammo to use, 75mm Railgun ammo.
World. https://www.dropbox.com/s/dqgv7dmwchxb53s/AmmoEatersBugtestWorld.zip?dl=0
Mod. https://github.com/pilfit/NorthWind_Weapons_beta You should already have this, it has not be updated.

## Expected behavior:
Gun reloads using only 1 ammo item.

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:

**Comment by sstixrud** [comment]
Known issue with overloaded powered grids and hybrid ammo.  Will fix in 2.0

**Comment by sstixrud** [comment]
Should be fixed.  Reopen if not fixed.
