### ISSUE TITLE
Add buildinfo integration for displaying stats

### ISSUE THREAD

**Issue by amezick** [sstixrud/WeaponCore#263]
**Is your feature request related to a problem? Please describe:**
I can't see weapon stats in game.  I am especially interested in accuracy or shot spread.

**Describe the solution or feature you'd like:**
I would like these stats to show up in the build info mod as they do for non-weapons core weapons.

**Additional context:**

WeaponCore:
![image](https://user-images.githubusercontent.com/870916/109520628-72780880-7a7a-11eb-8b33-0ed1eeb463c1.png)

Non WeaponCore:
![image](https://user-images.githubusercontent.com/870916/109520772-950a2180-7a7a-11eb-9f63-6b2cddbcc8a0.png)

**Comment by sstixrud** [comment]
This request need to go to the mod author of buildinfo
