### ISSUE TITLE
Add info about ammo Health as it relates to Beams, and EWAR

### ISSUE THREAD

**Issue by Blaylock1988** [sstixrud/WeaponCore#264]
## Please link to the page with an error:
https://github.com/sstixrud/WeaponCore/wiki/Ammo-Initial-Setup#health
https://github.com/sstixrud/WeaponCore/wiki/Ammo-AreaEffect#ewarfields

## Where is the issue, and what should be changed?
- Clarify Health on Beam ammos is not considered smart ammo.
- Clarify Health is the number of times an Area Effect is applied per hit. This is also the number of duration stacks added per second (because EWAR stacks are added per second and not per tick).
- Clarify that most EWAR effects (like JumpNull, EMP, AnchorField, NavField) ***MUST*** have Health on the ammo to function properly

**Comment by LordKreeg** [comment]
https://github.com/sstixrud/WeaponCore/wiki/Ammo-Properties
New Page.
