### ISSUE TITLE
Beam weapon doesnt fire when aimed at grid on planet

### ISSUE THREAD

**Issue by Beesoldier** [sstixrud/WeaponCore#265]
## Is this a multiplayer or singleplayer bug?

singleplayer, havent tried in mp

## Describe the bug:

shooting at a grid in planet gravity with a beam weapon will prevent it from firing if its aimed at the grid from the start of fire

here is a world to test, just my online mod and WC
[BTWC Beam testing.zip](https://github.com/sstixrud/WeaponCore/files/6097776/BTWC.Beam.testing.zip)

found nothing in the storage/ weaponcore logs but can provide if needed

cheers

**Comment by Beesoldier** [comment]
just wanna leave this here as well as on discord, so it doesnt get lost: Auto's MA PCD and Gimbal Laser have the same issue

**Comment by sstixrud** [comment]
Please retest and reopen if issue still exists.
