### ISSUE TITLE
Add HealthHitModifier description to Damage Scales

### ISSUE THREAD

**Issue by Blaylock1988** [sstixrud/WeaponCore#267]
## Please link to the page with an error:
https://github.com/sstixrud/WeaponCore/wiki/Ammo-DamageScales#damage-scales

## Where is the issue, and what should be changed?
HealthHitModifier is missing and should be added.

**Comment by LordKreeg** [comment]
Greetings, that Page is in re-works.
Shall be addressed

**Comment by LordKreeg** [comment]
https://github.com/sstixrud/WeaponCore/wiki/Ammo-Properties
New Page Complete
