### ISSUE TITLE
WC_Range property isn't multiplied by targeting range.

### ISSUE THREAD

**Issue by mleise** [sstixrud/WeaponCore#268]
## Is this a multiplayer or singleplayer bug?
Singleplayer

## Describe the bug:
The WC_Range terminal property has range 0 to 1 with 0.1 increments. When increasing it, the weapon range will be clamped to 1m.

## Steps To Reproduce:
Place a weapon on a grid, assign "Increase WC_Range" to an action bar slot and trigger it, then check the targeting range in the terminal.

## Expected behavior:
WC_Range scales with the weapon targeting range, so if that range is 4500m we'd get steps for 0m, 450m, 900m, ..., 4500m.

**Comment by sstixrud** [comment]
Range was not intended as an action, limited to terminal controls
