### ISSUE TITLE
Weapons do not fire in creative test world 

### ISSUE THREAD

**Issue by xgnstoneless** [sstixrud/WeaponCore#269]
## Is this a multiplayer or singleplayer bug?
Singleplayer

## Describe the bug:
When I load a fresh world after following all the other 8 steps to debug all I can get are the weapons to stare at each other and not fire. Missile launchers will stare at each other and not fire. They are tracking targets but not engaging. Gatling guns are doing the same thing except they will fire 1 round then stop. I am not getting the option to click to fire when grouping weapons. Its basically like nothing with the weapons have changed and they are vanilla but now they are just 100% broken. Its worth noting I have also tried to control the turrets to get them to manually fire with no luck. I also attached the screen shot of the image that the ingame error log was spitting out.

## Steps To Reproduce:
I followed all the steps deleted appworkshop 244850, deleted all numbered folders inside 244850, deleted all folders in \storage. I loaded a fresh empty creative world on SE 1.196 created 2 simple station like stated with just the Weapon core mod and the vanilla replacement weapons installed only on the SE mod menu. 

## Expected behavior:
I expected the mod to boot up and both stations to start shooting the crap outta each other instead they just track each other. the stations are hostile to each other and like I stated sometimes the Gatling gun will fire a single round into the small reactor so they are trying to shoot each other but for some reason cant.

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:
[WeaponCore - Replace Vanilla WeaponsInit.zip](https://github.com/sstixrud/WeaponCore/files/6139116/WeaponCore.-.Replace.Vanilla.WeaponsInit.zip)
![20210315001112_1](https://user-images.githubusercontent.com/80666401/111109615-1c4e9f00-8529-11eb-8c09-cab02fd901bc.jpg)

**Comment by mleise** [comment]
Yep, I never reported this, but it's a thing.

**Comment by sstixrud** [comment]
Please include the WeaponCore debug.log.  you only included the vanilla replacement log.

**Comment by sstixrud** [comment]
No logs included, closing bug
