### ISSUE TITLE
On Dedicated server after a few hours all WC weapons stop working

### ISSUE THREAD

**Issue by CaptNeo** [sstixrud/WeaponCore#270]
## Is this a multiplayer or singleplayer bug?
Dedicated Server

## Describe the bug:
was running a world that had these same mods I have now running well for almost a day when all the WC weapons stopped working. 

## Steps To Reproduce:
started a new world with a fresh new install of the server software and all the mods, ensuring to also clear out the saves.

## Expected behavior:
hoped that some old configs that were deleted in the cleanse were the former problem, and when the server booted clean all seemed to work well. after playing on the server for a few hours I ended my play for the day, then when I logged back in today the problem of no weapons firing returned again, one oddity i find is every so often on a vanilla turret or gun you can get a single shot but when you can seems very random.

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:
[Storage.zip](https://github.com/sstixrud/WeaponCore/files/6219612/Storage.zip)

**Comment by sstixrud** [comment]
You have either corrupted weapon mod downloads or a mod conflict.  Follow the bug reporting steps on the steam page to correct your issue.
