### ISSUE TITLE
Shield shunting causes crashes

### ISSUE THREAD

**Issue by TrueTurnIP** [sstixrud/WeaponCore#271]
## Is this a multiplayer or singleplayer bug?

singleplayer TT5 world

## Describe the bug:

turning shield shunting on and then toggling any of the options results in a crash to desktop.
## Steps To Reproduce:
compact shield emitter + a large ship control block on 3 large grid reactors with 1 regular cockpit and 1 shield emmiter. 

then turn on shunting and select any of the shunting options as on.

## Expected behavior:
crash to desktop

### User Error Report (if Weapon-Specific) and log files
[SpaceEngineers_20210405_134739249.log](https://github.com/sstixrud/WeaponCore/files/6258041/SpaceEngineers_20210405_134739249.log)

[1918681825.sbm_WeaponCore.zip](https://github.com/sstixrud/WeaponCore/files/6258049/1918681825.sbm_WeaponCore.zip)

**Comment by sstixrud** [comment]
Is this still an issue?

**Comment by TrueTurnIP** [comment]
yes, same thing happens I will try to repeat it again to get the logs and file again
