### ISSUE TITLE
Crash due to multi load of mods.

### ISSUE THREAD

**Issue by fat-rooster** [sstixrud/WeaponCore#272]
## Is this a multiplayer or singleplayer bug?

Both I assume. Steam modpack wierdness bug at the root I think.

## Describe the bug:

Weaponcore crashes when placing a weapon, or loading a weapon. Invalid state in preinit. Grimlock specifically in this case.

## Steps To Reproduce:

Deliberately load the same mod twice from different folders.

## Expected behavior:

Handling it gracefully, and recognising a mod update that has changed the modID.

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Added some logging into your handler function using threaded log, and it spat out this.
[debugdevelop.log.log](https://github.com/sstixrud/WeaponCore/files/6258474/debugdevelop.log.log)

**Comment by fat-rooster** [comment]
Played around a bit more with working out timings, and found something. Depending on load order, a mod's weapon definitions may be loaded before or after "ReallyStupidKeenShit" (which loops over weapon definitions). Could this cause weirdness?
[debugdevelop.log-04-05-21_18-34-38.log](https://github.com/sstixrud/WeaponCore/files/6259646/debugdevelop.log-04-05-21_18-34-38.log)

**Comment by sstixrud** [comment]
This is due to a steam dependency issue and starcore changing mods.  Not a WC bug
