### ISSUE TITLE
MuzzlePartId subpart vanishes on load for static weapon

### ISSUE THREAD

**Issue by 0x00002a** [sstixrud/WeaponCore#275]
## Is this a multiplayer or singleplayer bug?

Only encountered/tested it in SP but I would assume it also happens in MP

## Describe the bug:

If a subpart is set for `MuzzlePartId` but `AzimuthPartId` and `ElevationPartId` are "None", the subpart named in `MuzzlePartId` will vanish on world load. Disconnecting the block or deleting and replacing it fixes it (does not happen for new blocks).

Also this doesn't seem to be just visual, debug draw shows the model as having no dummies, looks like a CubeBlock. Terminal controls are also working and show WC stats, turning on "Shoot" causes it to fire a few rounds (with no visuals but audio) and then stop

## Steps To Reproduce:

1. Create a model with a subpart
2. Setup weaponcore for this model and set `MuzzlePartId` to the id of your subpart and `AzmuthPartId` and `ElevationPartId` to "None"
3. Open a world with the mod and weaponcore loaded and place the weapon
4. Reload the world in any way (quick load, quite out, restart game, etc)
5. You should see the subpart named in `MuzzlePartId` is missing from the model

## Expected behavior:

On world load it should work normally/same as when first placed

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:
[1918681825.sbm_WeaponCore.zip](https://github.com/sstixrud/WeaponCore/files/6326821/1918681825.sbm_WeaponCore.zip)

### Additional context

I realise this is possibly unsupported behaviour (static weapon with a MuzzlePartId), reason I want to use it is for the barrel spin animation and muzzle spin. 

Also, the CTRL-R laser goes straight through the block when its like this (the laser worked for another of my weapons)

**Comment by 0x00002a** [comment]
OK so an update on this: I tried recreating the spin using animations and got the same resault as above (including with the missing model dummies and it fixing on disconnect). Anmiation def: 
```cs
new PartAnimationSetDef
                {
                    SubpartId = Names("barrels"),
                    BarrelId = "Any",
                    StartupFireDelay = 0,
                    AnimationDelays = Delays(FiringDelay : 0, ReloadingDelay: 0, OverheatedDelay: 0, TrackingDelay: 0, LockedDelay: 0, OnDelay: 0, OffDelay: 0, BurstReloadDelay: 0, OutOfAmmoDelay: 0, PreFireDelay: 0),//Delay before animation starts
                    Reverse = Events(),
                    Loop = Events(),
                    EventMoveSets = new Dictionary<PartAnimationSetDef.EventTriggers, RelMove[]>
                    {
                        [Firing] = new[]
                        {
                            new RelMove
                            {
                                CenterEmpty = "BarrelsModel",
                                TicksToMove = 60,
                                MovementType = Linear,
                                RotAroundCenter = Transformation(0, 460, 360),
                            }
                        }
                    }
                }
```

**Comment by Mimic0445** [comment]
The barrel subpart will disappear if any of Min or Max Azimuth or Elevation != 0.
This leads to another bug however.
https://github.com/sstixrud/WeaponCore/issues/278

**Comment by sstixrud** [comment]
please confirm this is still an issue?

**Comment by sstixrud** [comment]
should be fixed
