### ISSUE TITLE
No damage if Azimuth and Elevation, Min and Max = 0 AND have slow Rate of Fire

### ISSUE THREAD

**Issue by Mimic0445** [sstixrud/WeaponCore#278]
## Is this a multiplayer or singleplayer bug?
Singleplayer

## Describe the bug:
When creating a weapon core weapon. In the weapon CS file,  Hardware section, If all Azimuth and Elevation, Min and Max values = 0. (in other words a fixed weapon) 7 bullets must hit a target in rapid succession in order to deal damage.
If fewer bullets hit the target or at a slow rate of fire e.g. RoF=60, no damage is dealt.

## Steps To Reproduce:
Load attached WC mod, and WC in game.
Test that the turret "Example Weapon Energy Gatling" deals no damage.
In "WeaponName_Example_1.cs" change MaxAzimuth = 1 (Line 78)
Test that the turret deals normal damage.

The other behavior I describe above can be seen by changing the ShotsInBurst (Line 106) to 7. (Turret deals full damage with Azi & Elev =0) Also by adjusting the RoF in the same section of code to affect the 7 bullet requirement.

## Expected behavior:
The weapon should deal damage normally if all Azimuth and Elevation, Min and Max = 0.

Zip:
[Weapon Thread_No DamageExample.zip](https://github.com/sstixrud/WeaponCore/files/6496092/Weapon.Thread_No.DamageExample.zip)

**Comment by Mimic0445** [comment]
Example Save with mod.
[Example mod and Save.zip](https://github.com/sstixrud/WeaponCore/files/6534572/Example.mod.and.Save.zip)

**Comment by sstixrud** [comment]
please confirm this is still an issue?

**Comment by sstixrud** [comment]
should be fixed
