### ISSUE TITLE
Multi-Turret Main Turret Inheriting Rotation Lock Limits from Secondary Turrets

### ISSUE THREAD

**Issue by LordKreeg** [sstixrud/WeaponCore#279]
## Is this a multiplayer or singleplayer bug?
Singleplayer Bug, Weapon System glitch: Causes Turret Unable to turn to extent, due to 2nd weapon' rotation limits.

## Describe the bug:
Rotation Range of Main Turret is locked, to secondary Turret's Rotation Range instead.
Increasing Rotation range of 2nd Turret, allows Main Turret to move more.

## Steps To Reproduce:
Press the Button, if the Turret does not turn right or left', with the main body, the Turret is not obeying its rotation limit, but instead is using the 2nd turret's rotation limit.

## Expected behavior:
Expected Behavior is the Turret turns to the right or left.

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:
[Test World Multi-Turret.zip](https://github.com/sstixrud/WeaponCore/files/6498449/Test.World.Multi-Turret.zip)

Load into world', Press the button, infront of the medical bay.
Watch for the Turret to Turn right or Left', if only the small top guns turn, the Turret is still wedged and unable to turn properly.

**Comment by Ash-LikeSnow** [comment]
Issue due to assignment of non-unique **WeaponName** to multiple weapons on the same platform.
