### ISSUE TITLE
possible bug, npc targeting player and not player owned grid

### ISSUE THREAD

**Issue by nukeguard** [sstixrud/WeaponCore#28]
HUNGARY 4 KABOB has Space Engineers Dec 22 @ 8:55am      
@nukeguard Any status update for npcs being able to shoot?

https://imgur.com/YSH4uX0

*edit*
They shoot me when Im in character but when Im in a cockpit they ignore me.
https://imgur.com/uV3Dbd0

**Comment by nukeguard** [comment]
I guess the blue grid is npc

**Comment by sstixrud** [comment]
Can you provide more info on the desired behavior?

**Comment by nukeguard** [comment]
well if npc weapons now shoot at you, that would be fixed

If that guy was enemy to the turrets and the ship he got into isn't that would explain the turret behavior in the second message

**Comment by sstixrud** [comment]
Fixed.
