### ISSUE TITLE
Shoots Unexpected Extra Burst

### ISSUE THREAD

**Issue by Mimic0445** [sstixrud/WeaponCore#280]
## Is this a multiplayer or singleplayer bug?
Singleplayer

## Describe the bug:
With:
DelayUntilFire != 0
DelayAfterBurst != 0
FireFullBurst = true

If you are using toggle click to fire from a cockpit and left click while the gun is "reloading" (during the delay after burst) the gun will immediately fire another full burst after the DelayAfterBurst timer ends.

Note, this also ignores the DelayUntilFire duration because that duration happens during the DelayAfterBurst duration.

## Steps To Reproduce:
Test attached example weapon to see behavior.

## Expected behavior:
The weapon should not fire after DelayAfterBurst timer ends if left click is pressed and released during DelayAfterBurst.

The behavior I think is most correct would be:
Require Left click to be clicked (or held) after DelayAfterBurst has ended and respect the DelayUntilFire by starting that count after the left click to fire has been accepted.

Zip Example Weapon:
[WeaponThread_ShootsUnexpectedExtraBurstExample.zip](https://github.com/sstixrud/WeaponCore/files/6504406/WeaponThread_ShootsUnexpectedExtraBurstExample.zip)

**Comment by sstixrud** [comment]
This should be fixed
