### ISSUE TITLE
Ability to synchronise multiple weapons on the same cubeblock.

### ISSUE THREAD

**Issue by Mimic0445** [sstixrud/WeaponCore#281]
**Is your feature request related to a problem? Please describe:**
I would like to have an easy way to synchronize multiple guns on the same block while maintaining firing delay offsets.

**Describe the solution or feature you'd like:**
Many potential solutions exist, two examples that would fit my use case are:

Sharing heat between weapons on the same block.
Wait for all weapons on this block to finish reloading before firing or starting DelayUntilFire.

**Comment by sstixrud** [comment]
This behavior is not going to be added.  however you can achieve some of this by using ammo patterns.
