### ISSUE TITLE
Programmable Block Backend API - Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by sisko-skunkworks** [sstixrud/WeaponCore#282]
## Is this a multiplayer or singleplayer bug?
Single player

## Describe the bug:
Made a script a few weeks back that was working fine for awhile. In the last week or so I've seen some crashes from the CanShootTarget and IsTargetAligned functions. Unfortunately the in-game stack trace isn't super helpful:

```
Caught exception during execution of script:Object reference not set to an instance of an object.
  at
WeaponCore.Api.ApiBackend.CanShootTarget(IMyTerminalBlock weaponBlock, IMyEntity targetEnt, Int32 weaponId)
...
```

If I wrap these calls in try/catches it fixes my issue, but figured I should report in case there's some underlying bug

```
    public bool CanShootTarget(IMyTerminalBlock weapon, long targetEnt, int weaponId) {
		try {
			return _canShootTarget?.Invoke(weapon, targetEnt, weaponId) ?? false;
		} catch {
			return false;
		}
	}
```

**Comment by sstixrud** [comment]
should be fixed
