### ISSUE TITLE
Gladius Laser Bug - Visual, Audio, HUD effects not registering.

### ISSUE THREAD

**Issue by XeroTheRenegade** [sstixrud/WeaponCore#284]
## Is this a multiplayer or singleplayer bug?

Multiplayer. Single player occasionally but harder to reproduce reliably.

## Describe the bug:

1. Set Gladius Lasers to shoot ON from toolbar, nothing happens. No heat generated in the top RH Hud as normal, no visual animations or sound effects.

2. Gladius lasers in combat show their visual effects for OTHERS, but not the USER, resulting in confusion on the turrets operating or not.

## Steps To Reproduce:

Paste in Ship
grab Gladius laser from G menu (SHOOT ON/OFF)
Toggle SHOOT ON
Nothing happens, no heat generated, no animation or sound.

## Expected behavior:

Weapon animation, sound & heat generation all appear as per usual.

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:
[1918681825.sbm_WeaponCore.zip](https://github.com/sstixrud/WeaponCore/files/6564255/1918681825.sbm_WeaponCore.zip)

**Comment by sstixrud** [comment]
Please retest and open new ticket if it is still happening.
