### ISSUE TITLE
(Suggestion / Enhancement) Engaged Target reticle

### ISSUE THREAD

**Issue by Blaylock1988** [sstixrud/WeaponCore#285]
**Is your feature request related to a problem? Please describe:**
Unrelated to any current problems.

**Describe the solution or feature you'd like:**
An additional target reticle type that simply shows if a grid is being targeted/engaged by any turret. See attached image mock up. Main feature is 1 single reticle centered on each targeted grid (even if multiple turrets are shooting at different blocks on said grid).

**Additional context:**
This is useful for situational awareness of what your grid's turrets are actually shooting at, rather than trying to follow ammo tracers especially for weapons that have a low fire rate. This can also be useful for when you _thought_ you were shooting at a grid but were actually shooting at one next to it.

Bonus features:
- config to scale the reticle with distance
- option for individual block target reticles within a certain distance

![image](https://user-images.githubusercontent.com/62247634/120906246-f9f28c00-c614-11eb-9304-391d0bd6c780.png)

**Comment by sstixrud** [comment]
not planned
