### ISSUE TITLE
Weaponcore Crashing

### ISSUE THREAD

**Issue by Dhaygood97** [sstixrud/WeaponCore#286]
## Is this a multiplayer or singleplayer bug?

Singleplayer bug

## Describe the bug:

after playing in a new single-player world after 30ish minutes weaponcore will crash. upon reloading the game weaponcore will crash immediately. Have tried unsubscribing and resubscribing from the mod as well as all weaponcore weapon mods I've been subscribed to and resubscribing to them. same results

## Steps To Reproduce:
1.Create new game with weaponcore
2.After fighting with npc's or after 30ish minutes weaponcore will crash.
3. after loading crashed game weapons will not

 function

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:
[1918681825.sbm_WeaponCore.zip](https://github.com/sstixrud/WeaponCore/files/6605019/1918681825.sbm_WeaponCore.zip)
[1918681825.sbm_WeaponCore.zip](https://github.com/sstixrud/WeaponCore/files/6605033/1918681825.sbm_WeaponCore.zip)

**Comment by sstixrud** [comment]
One of your weapon mods is corrupt/broken.
