### ISSUE TITLE
Power Requirement does not take reloadTime/burstdelay into consideration

### ISSUE THREAD

**Issue by mexpex** [sstixrud/WeaponCore#29]
An example of the issue:
I have a weapon that fires with a ROF of 1000 in burst of 8 with a 60tick pause(about 5.4 projectiles per second). That gives me about 2.3MW requirement
But, ingame i get a 7.3MW requirement. This is something i get if i calculate projectiles per second by using ROF/60 (16,7 PPS) instead of bringing in burst/reload in the mix.

**Comment by sstixrud** [comment]
Fixed.
