### ISSUE TITLE
(Suggestion / Enhancement) Allow GetWeaponTarget PB API to track incoming projectiles

### ISSUE THREAD

**Issue by sisko-skunkworks** [sstixrud/WeaponCore#292]
**Is your feature request related to a problem? Please describe:**
Right now the code returns an empty MyDetectedEntityInfo if the target is a projectile. It'd enable some neat use cases if it allowed tracking projectiles, e.g. displaying them on radars, etc.

**Describe the solution or feature you'd like:**
https://github.com/sstixrud/WeaponCore/blob/master/Data/Scripts/WeaponCore/Api/ApiBackend.cs#L645

Modify to return a non-null value for the entity, with the projectile position.
Perhaps with entity type Unknown or Missile?

**Additional context:**

**Comment by sstixrud** [comment]
This is not currently possible.
