### ISSUE TITLE
Torch Dedicated Server Error Message

### ISSUE THREAD

**Issue by xsubi** [sstixrud/WeaponCore#304]
### Did you encounter this issue in Multiplayer or Singleplayer?

Multiplayer (Dedicated Server)

### Issue Description

PDX Laser Artwork error message spam in server console

### Issue Reproduction

Tier 1 PDX lasers placed in game (working theory)   High numbers of these do cause server performance to begin degrading, so our solution was to remove the PDXs laser from grid builds.

![torch_pdx_artwork_error](https://user-images.githubusercontent.com/78401918/127069855-75f585e3-d83f-49f2-a038-33e49fd10c08.PNG)

### Expected Behavior

No error spam

### Checklist

- [X] I have submitted as much information as possible
- [X] I have given the issue an accurate title

**Comment by sstixrud** [comment]
Not a weaponcore issue
