### ISSUE TITLE
(Bug) Weapon limits can be circumvented by using merge blocks/rotors

### ISSUE THREAD

**Issue by BookBurner** [sstixrud/WeaponCore#307]
### Did you encounter this issue in Multiplayer or Singleplayer?

Singleplayer

### Issue Description

Weapon limits are applied when weapons are initialized, after they are they work, even when attached all to single grid.

Tested in singleplayer, local multiplayer

### Issue Reproduction

Build several weapons with say, limit one or two, build them separately.

Then merge block them to one grid. After they are initialized by weaponcore.
Same can be done by attaching them with a rotor after the weapon is initialized.

### Expected Behavior

This should probably not be possible.

### Checklist

- [X] I have submitted as much information as possible
- [X] I have given the issue an accurate title

**Comment by sstixrud** [comment]
should be fixed, reopen if still an issue.
