### ISSUE TITLE
(Bug) Vanilla Replacement gatling weapons not firing

### ISSUE THREAD

**Issue by osccal** [sstixrud/WeaponCore#310]
### Did you encounter this issue in Multiplayer or Singleplayer?

Multiplayer (Dedicated Server)

### Issue Description

Vanilla replacement gatling weapons, mainly using click to fire functionality, does not work. It will fire a few rounds after initial building, but then stop working. They will then no longer respond to control panel fire override

### Issue Reproduction

Using vanilla replacement weapons with click to fire does not work

### Expected Behavior

For the weapons to fire when using click to fire 

### Checklist

- [X] I have submitted as much information as possible
- [X] I have given the issue an accurate title

**Comment by TheMilso** [comment]
I am having the exact same issue.
Mine will fire then connected to my station via connector

**Comment by sstixrud** [comment]
Should be fixed
