### ISSUE TITLE
(Bug) (V2) API Methods Not Working For Getting Static Weapon and Turret IDs

### ISSUE THREAD

**Issue by MeridiusIX** [sstixrud/WeaponCore#312]
### Did you encounter this issue in Multiplayer or Singleplayer?

Singleplayer

### Issue Description

GetAllCoreTurrets() and GetAllCoreStaticLaunchers() do not appear to be populating weapon IDs anymore. GetAllCoreWeapons() is still getting all weapon IDs, I can confirm that.

This is making it a bit difficult to properly identify and manage weapons for NPCs.

I tested this with the Northwind Weapons and MWI Homing weapons. If you need to test after a potential fix, you can use the MES rewrite (https://steamcommunity.com/sharedfiles/filedetails/?id=2542599100) and the chat command /MES.Info.GetBlockDefinitions - the command will tell you if a block is a weaponcore turret or static gun based on the existence of its MyDefinitionId in the collections created by the methods that aren't working.

### Issue Reproduction

Use either of the methods GetAllCoreTurrets() and GetAllCoreStaticLaunchers() in the WeaponCore API (CoreSystems / V2)

### Expected Behavior

When providing collections as parameters to the methods, they should have been populated with MyDefinitionIDs for Turrets and Static Weapons

### Checklist

- [X] I have submitted as much information as possible
- [X] I have given the issue an accurate title

**Comment by sstixrud** [comment]
fixed
