### ISSUE TITLE
(Bug) Using DecayPerShot to destroy a weapon after it fires will instantly crashes weaponcore.

### ISSUE THREAD

**Issue by AryxErin** [sstixrud/WeaponCore#314]
### Did you encounter this issue in Multiplayer or Singleplayer?

Multiplayer (Dedicated Server)

### Issue Description

Having a weapon be "single use" via using DecayPerShot in order to destroy it on firing, results in an immediate weaponcore crash with the log message

"08-31-21_16-43-16-969 - Exception in SessionBeforeSim: System.NullReferenceException: Object reference not set to an instance of an object.
   at WeaponCore.Session.TerminalMonitor.ServerClean(WeaponComponent comp)
   at WeaponCore.Session.TerminalMonitor.Clean(Boolean purge)
   at WeaponCore.Session.TerminalMonitor.Monitor()
   at WeaponCore.Session.UpdateBeforeSimulation()"
   
   I'm reasonably convinced this is due to the gun being destroyed as code is called, due to the lack of a null check.

### Issue Reproduction

Use the Variable Warhead Single use Launcher in AWE on any game mode, as invalid found, it crashes weaponcore on firing.

### Expected Behavior

The weapon block should fire one projectile and then destroy itself.

### User Error Report

[1918681825.sbm_WeaponCore.zip](https://github.com/sstixrud/WeaponCore/files/7087067/1918681825.sbm_WeaponCore.zip)

### Checklist

- [X] I have submitted as much information as possible
- [X] I have given the issue an accurate title

**Comment by sstixrud** [comment]
fixed
