### ISSUE TITLE
(Bug) 300mm Cannons not able to load, fire or do anthing else. 

### ISSUE THREAD

**Issue by CosmicEcl07** [sstixrud/WeaponCore#321]
### Did you encounter this issue in Multiplayer or Singleplayer?

Multiplayer (Locally Hosted)

### Issue Description

Im using the 300mm northwind turrets and they are giving me numerous errors in the debug saying

TargetState: NotSet - Manual: false
Event: Reloading - Ammo :false
OverHeat: False 
CanSHoot: False - Charging: False
AiShooting False
MAgSize: 3 CurrentCharge 0(0)
ChargeTime: 0(1051700) - Delay 0
Charing: False(false) - Delay: 0

### Issue Reproduction

It Just happend in this world the first time we place a gun a orcs enemy flew over head (within the guns range)
And it didnt aim nor fire at the enemy.

### Expected Behavior

It Should have Aimed and fired at the drone *(if it matters it was using 300mm smart ammunition
![Capture](https://user-images.githubusercontent.com/90441645/132810349-25cf8c41-143f-41e6-9dc2-7820587baf25.JPG)
)

### User Error Report

[combat.log](https://github.com/sstixrud/WeaponCore/files/7141777/combat.log)

### Checklist

- [X] I have submitted as much information as possible
- [X] I have given the issue an accurate title

**Comment by sstixrud** [comment]
Should be fixed
