### ISSUE TITLE
(Bug) Ammos using smart guidance phase through parent ship

### ISSUE THREAD

**Issue by Blaylock1988** [sstixrud/WeaponCore#330]
### Did you encounter this issue in Multiplayer or Singleplayer?

Singleplayer

### Issue Description

Ammos like missiles when set to use a smart guidance do not detect collision with the ship that launched them. This means you can place homing missile launchers completely covered inside a ship and still fire them at enemies.

![image](https://user-images.githubusercontent.com/62247634/133941159-8badacad-abfe-4040-a9c8-1041eafe2cad.png)

### Issue Reproduction

Cover any homing missile launcher that has `MuzzleCheck = false`, and an ammo that has `Guidance = Smart`, set the weapon to fire, and observe missiles phasing through blocks.

Repeat the above with a rocket weapon that has `Guidance = None` and see the behavior change as they impact with parent grid as desired.

### Expected Behavior

Missiles with any guidance should impact the parent grid, just as they do when `Guidance = None`, and should not phase through blocks.

### Checklist

- [X] I have submitted as much information as possible
- [X] I have given the issue an accurate title

**Comment by Blaylock1988** [comment]
If this is actually working as expected, please note this behavior in the wiki here https://github.com/sstixrud/WeaponCore/wiki/Projectile-Guidance-Systems#smart

**Comment by sstixrud** [comment]
This is intended behavior.  Added note to wiki.
