### ISSUE TITLE
(Bug) Particle's ParticleLights property stop working when used in HardPointParticleDef (like Barrel1)

### ISSUE THREAD

**Issue by Blaylock1988** [sstixrud/WeaponCore#331]
### Did you encounter this issue in Multiplayer or Singleplayer?

Singleplayer

### Issue Description

As the title states, the ParticleLights of a particle does not show when the Particle is assigned to either Barrel1 or Barrel2 in the weapon's HardPointParticleDef. 

When testing the particle in other areas the light works as expected (such as in an ammo Hit particle).

### Issue Reproduction

Assign any particle, such as `MaterialHit_Metal` (keen Particle) to a HardPointParticleDef particle, observe no illumination of surrounding blocks (like a light block). 

Then assign the same particle to an Ammo Hit, and see the illumination work as designed.

### Expected Behavior

ParticleLights in a particle should always be allowed to work.

### Checklist

- [X] I have submitted as much information as possible
- [X] I have given the issue an accurate title

**Comment by sstixrud** [comment]
fixed
