### ISSUE TITLE
(Suggestion / Enhancement) Add ability to force turrets to not target the same block/projectile.

### ISSUE THREAD

**Issue by xavieraiden** [sstixrud/WeaponCore#345]
I've been having problems where during a meteor storm, every single PDW would open up on an individual meteorite, leaving all the others to hurtle towards me.
A possible fix/improvement to this would for there to be an option to force turrets (or weapons in general) to target different blocks/projectiles. 

If this is already a feature just shut the issue, preferably with instructions on how to do it (or a link to instructions)

Thanks

PS: I live in Australia so responses may be staggered

**Comment by sstixrud** [comment]
This is already configurable per mod
