### ISSUE TITLE
(Suggestion / Enhancement) 

### ISSUE THREAD

**Issue by vash1127** [sstixrud/WeaponCore#360]
already partially implemented on weapons using the turret block type and this would make a uniform/consistent way to use it

setter function for wcapi to set the desired azimuth and elevation of turrets

adds the ability to somewhat protect from insiding / sneaky allied tag players by forcing turrets to align with an object/region of space without relying on "having a target"

adds a simple convert for some older workshop scripts

tactical edge for kiting with script assisted aiming

**Comment by sstixrud** [comment]
not planned
