### ISSUE TITLE
Finding targeting delay issues with fast lasers.

### ISSUE THREAD

**Issue by AutoMcDonough** [sstixrud/WeaponCore#37]
Testing a point defense laser (PDX). 
-Picks 1st target immediately, then there is a 2+ second delay before it reacquires a target. There is an intermittent aspect to this, sometimes the game will load and it works beautifully.
 
-Seems to be ignoring priority; in config the projectiles are highest priority but get ignored when blocks can be targeted. It is possible that maybe there just aren't projectiles available when it looks because of the delay issue, but it should break lower priority target when higher priority one becomes available.

**Comment by sstixrud** [comment]
fixed
