### ISSUE TITLE
EMP Block Disabling Effect no longer working since WC 2 update

### ISSUE THREAD

**Issue by seth6g** [sstixrud/WeaponCore#373]
## Is this a multiplayer or singleplayer bug?
Both

## Describe the bug:
Prior to Weapon Core update EMP Turrets, and Gladius Turrets ( From the MA weapons pack) could disable blocks using an EMP effect. This effect would cause the block to be turned off for a set period of time simulating an overload condition in the block. This would cause it not to function during that period. Once the period had elapsed the block would turn back on. This effect was stable and working in the previous version of Weapon Core, however since the update this feature has not functioned. This issue was reported to the Author of the MA weapon pack who confirmed the issue is occurring as stated above, but could not find causes for it within their mod. They believe that the issue lay somewhere on the weapon core side of weapons processing. 

## Steps To Reproduce:
Use vessel equipped with EMP turrets, or Gladius turrets (With damage set to 0 as to avoid destroying the targeted block) to target and fire upon hostile grid (Recommend simple hostile grid such as single power source and energy weapon to better observer all components)

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:

**Comment by sstixrud** [comment]
fixed
