### ISSUE TITLE
projectiles ignore handplaced voxel

### ISSUE THREAD

**Issue by Beesoldier** [sstixrud/WeaponCore#378]
## Is this a multiplayer or singleplayer bug?
happens both in single and multiplayer

## Describe the bug:
slow projectiles of about 200m/s or lower pass through handplaced voxel which they obviously shouldnt

## Steps To Reproduce:
place voxel, use any slow missiles, shoot through voxel

## Expected behavior:
they should be stopped obviously

demonstation video with my own weapons
https://user-images.githubusercontent.com/69863437/143780988-cc39e010-a692-4379-a7b6-5dbcfea118f2.mp4
demonstation with MWIs homing missiles
![unknown](https://user-images.githubusercontent.com/69863437/143781070-31485730-22f8-4f8b-bedf-ed472488a91b.png)
showing off that the walls are indeed not trees, but mineable voxel
![unknown](https://user-images.githubusercontent.com/69863437/143780913-f18bf25d-97d6-473e-aa1b-30f2ed8368f4.png)

**Comment by sstixrud** [comment]
This is not a bug, but an optimization.  Hand placed voxels are not supported and will not be without improvements on keens side.
