### ISSUE TITLE
Vanilla replacements are not replacing, leaving duds.

### ISSUE THREAD

**Issue by AutoMcDonough** [sstixrud/WeaponCore#38]
The existing vanilla weapons in the world are not getting replaced with ones containing WC logic when loading up world containing the vanilla weapon replacement mod. Same for paste-in blueprints containing vanilla weapons. Projector build I have not tested but might be ok.

These vanilla weapons which are not "replaced" also do not perform as vanilla weapons, they are duds.

The only weapons which seem to function are the ones placed while the mod is active.

**Comment by TheWizardLizard** [comment]
Should be fixed with latest commits, still working out an issue with unnecessary cpu usage though

**Comment by TheWizardLizard** [comment]
also waiting on nuke to update his mod though that should be soon

**Comment by sstixrud** [comment]
Feature completed, adding tomorrow.
