### ISSUE TITLE
TravelSound is not functioning

### ISSUE THREAD

**Issue by Blaylock1988** [sstixrud/WeaponCore#388]
## Is this a multiplayer or singleplayer bug?
Both

## Describe the bug:
TravelSound no longer working. I tested MWI Homing, AWG WC Weapon pack (all of those guns have that shell whistle sound), as well as my own mod. Also tried loop and non-loop, and it made no difference

## Steps To Reproduce:
Fire any weapon that has a travel sound, observe no travel sound from the ammo.

## Expected behavior:
Ammos should play the TravelSound, looped or non-looped.

This appears to have been a bug in the past #78 and has come back

**Comment by sstixrud** [comment]
fixed
