### ISSUE TITLE
New AreaOfDamage does not use DamageScales

### ISSUE THREAD

**Issue by Blaylock1988** [sstixrud/WeaponCore#410]
## Is this a multiplayer or singleplayer bug?
Both

## Describe the bug:

In SessionDamageMgr.cs Line 557, aoeScaledDmg should be multiplied by damageScale.

Previously, AreaEffect included the damage scales. New AreaOfDamage does not, and this has massive implications, especially on small grids.

I tested this in offline and it works as desired.

## Expected behavior:

Damage scales should be used in area affects as it was a few days ago.

**Comment by sstixrud** [comment]
will be fixed in next patch
