### ISSUE TITLE
Hybrid ammo weapons can skip their charging time if you power cycle the weapon

### ISSUE THREAD

**Issue by Synirrr** [sstixrud/WeaponCore#411]
## Is this a multiplayer or singleplayer bug?
Both multiplayer and singleplayer

## Describe the bug:
When you place and load hybrid ammo into a weapon the weapon will load and charge it. However, once you fire the weapon you can power cycle the weapon to cancel the ammo's charge cycle meaning you just have to wait for a reload.

## Steps To Reproduce:
1. Fire weapon with hybrid ammo
2. Power cycle the weapon
3. Just wait for reload time instead of reload + charge time
4. Fire again

## Expected behavior:
1. Fire weapon with hybrid ammo
2. Power cycling resets charge time
3. Wait for reload and charge time
4. Fire the weapon again

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:
[1918681825.sbm_CoreSystems.zip](https://github.com/sstixrud/WeaponCore/files/7747018/1918681825.sbm_CoreSystems.zip)

**Comment by sstixrud** [comment]
fixed
