### ISSUE TITLE
(Suggestion / Enhancement)  Config Option: Default Option for Target Neutrals

### ISSUE THREAD

**Issue by Egglanoir** [sstixrud/WeaponCore#441]
**Is your feature request related to a problem? Please describe:**
Target Neutral in my opinion should have never been set to on by default. In the server I play on, it causes more issues than not. Like if I am building a ship beside someone who is in a different faction, its annoying that my weapons will target them the second I place them down.

**Describe the solution or feature you'd like:**
I would suggest adding a config option that will allow players and servers to set what the default should be.

**Comment by sstixrud** [comment]
Target Neutral is not on by default in survival worlds, only in creative.
