### ISSUE TITLE
Small grid Turret controller AI is Broken

### ISSUE THREAD

**Issue by Person4772** [sstixrud/WeaponCore#452]
## Is this a multiplayer or singleplayer bug?
Singleplayer: tested
Multiplayer: unknown

## Describe the bug:
Custom Turret controller (Small grid) is broken, Custom Turret Controller (Large Grid) works fine
Block will lose AI functionality even if switched on.
Caused by Weaponcore itself
No Weapon mods

## Steps To Reproduce:
Create a world with ONLY Weaponcore activated.
create a small ship with a small ship turret on top
activate AI and add an enemy grid nearby
AI will not target it or even respond
Disable Weaponcore in the MOD tab and reload the world
AI turret works as expected

## Expected behavior:
While the Weaponcore mod is active the Small grid Turret controller block will not Activate AI
While the Weaponcore mod is De-activated the turret controller works normally

### User Error Report (if Weapon-Specific) and log files
This Error is Weaponcore base.

**Comment by HoovySimulator2** [comment]
Huh, I have this same problem with a small grid turret on a large grid station. My ques is that as Weapon Core weapons use grouping to shoot, the custom turret AI doesn't know how to do that. I currently use the vanilla weapon replacement Weapon Core mod/addon, I will disable it and see if anything happens.

**Comment by Gampsi** [comment]
> Huh, I have this same problem with a small grid turret on a large grid station. My ques is that as Weapon Core weapons use grouping to shoot, the custom turret AI doesn't know how to do that. I currently use the vanilla weapon replacement Weapon Core mod/addon, I will disable it and see if anything happens.
> 
> Edit: Did what I said, and now the turret works. I'm gonna enable vanilla weapon replacement again as I wait for a possible fix.

Yeah the same happens to me. I'm using MES with surface occupation, the interior turret and missile launcher/gatling of those buildings won't attack me. I've tried in a creative world and apparently I can't put ammo inside them. (Using vanilla weapon replacement addon too).
