### ISSUE TITLE
CoreSystems hard crashing after update

### ISSUE THREAD

**Issue by gachiemane** [sstixrud/WeaponCore#465]
## Is this a multiplayer or singleplayer bug?
Single player

## Describe the bug:
When I load into my save game (an Agaris world with water enabled), I am getting the following error:

"Coresystems hard crashed during block init, shutting down
Send log files to server admin or submit a bug report to the mod author:
D:\SteamLibaray\steamapps\workshop\content\244850\1918681825 - AutoCannonTurret
Coresystems hard crashed during block init, shutting down
Send log files to server admin or submit a bug report to the mod author:
D:\SteamLibaray\steamapps\workshop\content\244850\1918681825 - AutoCannonTurret"

(Yes, the error message repeats twice)

I was playing earlier today prior to the update (which posted to steam at 7:16 pm EST) without issue.  Before submitting this error report, I took the steps to delete all the mod files and allow steam to reinstall them.  No effect.

## Steps To Reproduce:
I've created a save-as of my save file, and then removed ALL weapons mods, and loaded the game.  The save loads just fine.   

Then I added back in just the WeaponCore - 2.2(8) - Stable , and the error occurs. Numerous lines occur for the error.  I will attempt to include a screen shot but in the event it doesn't work, the error was as follows:

"Unable to find the specified file"
"Unable to find the specified file"
"Unable to find the specified file"
"Unable to find the specified file"
"Unable to find the specified file"
"Unable to find the specified file"
"Unable to find the specified file"
"Coresystems hard crashed during block init, shutting down
Send log files to server admin or submit a bug report to the mod author:
D:\SteamLibaray\steamapps\workshop\content\244850\1918681825 - AutoCannonTurret
"Coresystems hard crashed during block init, shutting down
Send log files to server admin or submit a bug report to the mod author:
D:\SteamLibaray\steamapps\workshop\content\244850\1918681825 - AutoCannonTurret

(Yes the message repeats twice)

I also removed BuildInfo as I read it can cause some problems, and it made no effect.

Curious, I created a totally new save in creative (Earth, space spawn) without WC at first.  I landed on the planet, placed one of each weapon type (large and small grid).  No mods, and no errors experienced.

After, I added in just WC 2.2(8) and got the following errors.

"Unable to find specified file"
"Unable to find specified file"
"Unable to find specified file"
"Unable to find specified file"
"Unable to find specified file"
"Unable to find specified file"
"Unable to find specified file"

(This sequence seems to always appear in 7s)

## Expected behavior:
The game loads without error messages.  WeaponCore functions.

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:
I'm not sure where I can zip and link a folder to (i don't have any domains that I host/can post files, but here is the contents of the debu file from today:

02-27-22_22-56-39-425 - Logging Started
02-27-22_22-56-39-492 - 25mm NATO is NOT enabled for client prediction
02-27-22_22-56-39-497 - 25mm NATO is NOT enabled for client prediction
02-27-22_22-56-39-498 - 25mm NATO is NOT enabled for client prediction
02-27-22_22-56-39-499 - 25mm NATO is NOT enabled for client prediction
02-27-22_22-56-39-525 - 200mm Missile is NOT enabled for client prediction
02-27-22_22-56-39-528 - 200mm Missile is NOT enabled for client prediction
02-27-22_22-56-39-530 - 200mm Missile is NOT enabled for client prediction
02-27-22_22-56-39-532 - 200mm Missile is NOT enabled for client prediction
02-27-22_22-56-39-534 - 200mm Missile is NOT enabled for client prediction
02-27-22_22-56-39-547 - 200mm Missile is NOT enabled for client prediction
02-27-22_22-56-39-549 - MR-50A is NOT enabled for client prediction
02-27-22_22-56-39-549 - 5.56x45mm is NOT enabled for client prediction
02-27-22_22-56-39-550 - Autocannon Shell is NOT enabled for client prediction
02-27-22_22-56-39-551 - Autocannon Shell is NOT enabled for client prediction
02-27-22_22-56-39-551 - WeaponAmmoData is null, check the block sbc/type for LargeBlockMediumCalibreTurret
02-27-22_22-56-39-563 - Assault Cannon Shell is NOT enabled for client prediction
02-27-22_22-56-39-564 - WeaponAmmoData is null, check the block sbc/type for SmallBlockMediumCalibreGun
02-27-22_22-56-39-566 - Assault Cannon Shell is NOT enabled for client prediction
02-27-22_22-56-39-566 - WeaponAmmoData is null, check the block sbc/type for SmallBlockMediumCalibreTurret
02-27-22_22-56-39-568 - Assault Cannon Shell is NOT enabled for client prediction
02-27-22_22-56-39-568 - WeaponAmmoData is null, check the block sbc/type for LargeBlockLargeCalibreGun
02-27-22_22-56-39-579 - Artillery Shell is NOT enabled for client prediction
02-27-22_22-56-39-580 - WeaponAmmoData is null, check the block sbc/type for LargeCalibreTurret
02-27-22_22-56-39-594 - Artillery Shell is NOT enabled for client prediction
02-27-22_22-56-39-595 - WeaponAmmoData is null, check the block sbc/type for LargeRailgun
02-27-22_22-56-39-608 - Large Railgun Slug is NOT enabled for client prediction
02-27-22_22-56-39-609 - WeaponAmmoData is null, check the block sbc/type for SmallRailgun
02-27-22_22-56-39-621 - Small Railgun Slug is NOT enabled for client prediction
02-27-22_22-56-49-956 - PlatformCrash: AutoCannonTurret - Your block subTypeId (AutoCannonTurret) Invalid barrelPart, I am crashing now Dave.
02-27-22_22-56-49-956 - PlatformCrash: AutoCannonTurret - Platform PreInit is in an invalid state: AutoCannonTurret
02-27-22_22-56-50-109 - PlatformCrash: AutoCannonTurret - Your block subTypeId (AutoCannonTurret) Invalid barrelPart, I am crashing now Dave.
02-27-22_22-56-50-110 - PlatformCrash: AutoCannonTurret - Platform PreInit is in an invalid state: AutoCannonTurret
02-27-22_22-57-43-572 - RemoveComp Weaponbase didn't have my comp: inDelayedStart: False - FoundAi:True - sameAi:True - sameTopEntity:True - inScene:False - marked:False - LastRemoveFromScene:0 - LastAddToScene:0 - Tick:0
02-27-22_22-57-43-574 - RemoveComp Weaponbase didn't have my comp: inDelayedStart: False - FoundAi:False - sameAi:False - sameTopEntity:True - inScene:False - marked:False - LastRemoveFromScene:0 - LastAddToScene:0 - Tick:0
[debug.log](https://github.com/sstixrud/WeaponCore/files/8150758/debug.log)

**Comment by sstixrud** [comment]
I am not seeing this error.  You are seeing it with no other mods loaded but weaponcore?  I would suggest following the steps on the steam page for clearing out your mod cache.

**Comment by gachiemane** [comment]
I had actually done the cache clear prior to submitting, but i did it again.  Preliminary tests on a creative only world show improvement.  Still working through all the details on my save though.

**Comment by sstixrud** [comment]
Not a coresystems issue.
