### ISSUE TITLE
GiveUpAfter = True & ClosestFirst = False failing to retarget after burst

### ISSUE THREAD

**Issue by Erebus-Alpha** [sstixrud/WeaponCore#466]
## Is this a multiplayer or singleplayer bug?
Tested on singleplayer

## Describe the bug:
Weapons with GiveUpAfter = true fail to give up and retarget another block after their burst is complete

## Steps To Reproduce:
1: Download AWE weapon pack (bug should also be replicable with any weaponcore weapon mod)

2: Make a local copy of the AWE weapon mod (bug should also be replicable with any weaponcore weapon mod)

3: Navigate to [user]/appdata/roaming/SpaceEngineers/Mods/[Local AWE Mod Copy Name]/Data/Scripts/CoreParts. Open AryxChaingunTurretAvalanche_Weapon.cs (bug should also be replicable with any weaponcore weapon, but is most obvious with rapid-fire weapons that do low damage)

4 Inside AryxChaingunTurretAvalanche_Weapon.cs: 
- Change ClosestFirst from true to false.
- Confirm that TopBlocks = 0
- Change ShotsInBurst from 60 to 10 (optional, but makes erroneous behavior more obvious)
- Confirm that GiveUpAfter = true
- Save the file

5: Start up Space Engineers. Select New Game > Custom Game > Red Ship (bug should also be replicable in any world). Select Mods, and add WeaponCore 2.2(8)-Stable, and the local copy of Aryx Weapon Enterprises. For convenience, set the world to creative mode.

6: Remove the turrets on the red ship & set all of the red ship's blocks to SPRT ownership

7: Install an 'Avalanche' turret on the station platform, with a clear line of sight to the now-hostile red ship.

## Expected behavior:
The turret should select a random targetable block on the Red Ship, fire a burst of 10 rounds, and then select another random targetable block on the red ship.

If the bug is successfully replicated, the turret should select a random targetable block on the Red Ship, and then refuse to retarget another block until its target is destroyed.

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:

https://filepost.io/d/EBuDrLMUcs

**Comment by sstixrud** [comment]
should be fixed
