### ISSUE TITLE
Subsystem Targeting Option Exclusion Failure

### ISSUE THREAD

**Issue by Erebus-Alpha** [sstixrud/WeaponCore#467]
## Is this a multiplayer or singleplayer bug?
Tested on singleplayer.

## Describe the bug:
When removing subsystems from the Subsystems = new [] list, they still appear in-game in the Pick SubSystem drop-down menu.

## Steps To Reproduce:
1: Make a local copy of any weaponcore weapon mod

2: Navigate to [users]/appdata/roaming/SpaceEngineers/mods/[local mod]/data/scripts/coreparts. Select the .cs file for any weapon.

3: Change its Subsystems = new [] entry to: Subsystems = new [] {Any} - removing all subsystem targeting entries except 'Any'. Then save the changes to the .cs file.

4: Start up Space Engineers. Start a new game. Select Mods, and add WeaponCore 2.2(8)-Stable, and the local copy of the mod containing the modded turret.

5: Place the modded weapon (with altered targetable subsystems) in the game world. For convenience's sake, it may help to place the modded weapon onto a powered grid.

6: Open the control panel in-game and select the recently-placed weaponcore weapon (with altered targetable subsystems). Scroll down to 'Pick SubSystem' and click the drop-down arrow.

## Expected behavior:
The only clickable option within 'Pick SubSystem' should be 'any'.

If the 'Pick SubSystem list includes Offense, Utility, Power, Production, Thrust, Jumping, and Steering, then the bug has been successfully replicated.

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:

https://filepost.io/d/EBuDrLMUcs

**Comment by BDCarrillo** [comment]
It seems like a "none" option is what you're seeking, that prohibits selecting any individual subsystems.  The default behavior (subsystem targeting off) is essentially like "any" and nothing is excluded.

**Comment by sstixrud** [comment]
This is intended.  There is no provision for disabling subsystem targeting.
