### ISSUE TITLE
Weapons fire un-expectedly in the toolbar config menu when setting up program block actions. 

### ISSUE THREAD

**Issue by Klous666** [sstixrud/WeaponCore#475]
## Is this a multiplayer or singleplayer bug?

Both

## Describe the bug:

When setting Programable Block on Actionbar "mouse controlled" weapons fire un-expectedly.

## Steps To Reproduce:
1) Have a ship with one or more "mouse control" weapons
2) Have a ship with a programable block
3) Enter the Cockpit.
4) Hit "G" to access the Toolbar config menu
5) Click and drag and programable block to the actionbar, any slot.  Select Run. Enter any Argument, click Confirm. 
6) Click and drag the programable block to the actionbar again.  Weapons fire un-expectedly
7) Click anywhere on the screen, weapons continue to fire unexpected, even thought the "g" menu is active. 

## Expected behavior:
Weapons shouldn't fire when on the Toolbar config menu is active. 
[Weapons firing unexpectedly on Toolbar config menu](https://youtu.be/7K5lSnhwG5I)

**Comment by BDCarrillo** [comment]
Should be resolved in next update

**Comment by sstixrud** [comment]
fixed
