### ISSUE TITLE
no weapons fire

### ISSUE THREAD

**Issue by limbitable** [sstixrud/WeaponCore#479]
## Is this a multiplayer or singleplayer bug?
singleplayer

## Describe the bug:
the weapons do not fire, for example the gatlings make the shooting animation, consume the ammunition but do not do any damage and have no sound of shooting.

## Steps To Reproduce:
just tried to shoot with a turret whatever.

## Expected behavior:
 consume the ammunition but do not do any damage and have no sound of shooting.

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:

**Comment by limbitable** [comment]
why did you close the report when you did not provide an answer?

**Comment by sstixrud** [comment]
You did not follow the bug reporting instructions and whatever your issue is is not a bug.    Sounds like you need to learn how to use the mod, join the discord where people can provide that help.
