### ISSUE TITLE
Turrets target the missile projectiles of weapons that are neutral to them

### ISSUE THREAD

**Issue by highlyunavailable** [sstixrud/WeaponCore#489]
## Is this a multiplayer or singleplayer bug?

Both.

## Describe the bug:

Turrets set to target projectiles engage projectiles from factions that are Neutral to them, even when Target Neutrals is **off**.

## Steps To Reproduce:

Create a world with just the WeaponCore vanilla weapons replacer mod installed.

Create 2 factions, A and B, and set both to auto-accept peace.
Request peace between A and B so that they are neutral to each other.

Place a Gatling turret on a reactor and assign it to Faction A. Turn off all targeting except Projectiles, and make sure Target Neutrals is off.

Place a Missile turret on a reactor and assign it to Faction B, facing but not directly able to hit the Faction A turret. Turn off all targeting so it faces forward, and make sure it is not able to target neutrals.

Set the Missile Turret to shoot and override targeting.

Observe that the Gatling turret engages and destroys the missiles.

## Expected behavior:

The Gatling turret ignores the missiles that are from a Neutral party, since Target Neutral is disabled.

### User Error Report (if Weapon-Specific) and log files

I have attached a world with this scenario pre-configured. Turn on the missile turret and observe the behavior noted.

[Incorrect Projectile Targeting.zip](https://github.com/sstixrud/WeaponCore/files/8821265/Incorrect.Projectile.Targeting.zip)

I also went spelunking in the code and was able to solve the problem in an inefficient(?) manner.

In AiTargeting.cs, in the method `AcquireProjectile`, if I do the following:

Store the attack neutrals setting at the top:
`var attackNeutrals = w.Comp.Data.Repo.Values.Set.Overrides.Neutrals;`

And check in the loop over targets:

```
MyDetectedEntityInfo entInfo;
if (!lp.Info.Ai.CreateEntInfo(w.Comp.TopEntity, lp.Info.Ai.AiOwner, out entInfo) || (!attackNeutrals && entInfo.Relationship == MyRelationsBetweenPlayerAndBlock.Neutral))
{
    continue;
}
```

Then the missile targeting behavior is as expected above. This is almost certainly inefficient and likely not the correct way to do it, but it _is_ possible.

**Comment by BDCarrillo** [comment]
The difficulty with making this change is that missiles from a neutral ship may or may not be targeting you, which would require additional checks per incoming projectile.  This gets messy if a neutral ship is targeting a nearby friendly, and your PD has the ability to engage.

**Comment by highlyunavailable** [comment]
The targeting checks are already made in the case of PDs that can only target missiles targeting you.

This issue makes missile weapons unusable in situations with many neutrals without very careful PD toggling by all members involved. If you have target neutrals off, and a neutral targets a friendly ship, the PD should _not_ engage the incoming missiles.

This should at least be an option to configure in the cs files, much like "can only target weapons targeting your grid" is.

**Comment by BDCarrillo** [comment]
This was actually an underlying bug where all smart projectiles were tracked excessively, and will be resolved in the next update.
