### ISSUE TITLE
Turrets damage own grid

### ISSUE THREAD

**Issue by nukeguard** [sstixrud/WeaponCore#50]
ZÆRO  7 hours ago 
Friendly turrets damage own or friendly grids (with option to deal friendly damage is off) - changing back to vanilla they do not damage - changing back - my grids start to take damage again by own turrets.
from comments in Vanilla replacement steam page

SelfDamage = false in both ammo configs

**Comment by nukeguard** [comment]
This is happening on my octobeam, but seems as though the line of sight is close to the grid, and my beams were grazing the grid enough to break it.

**Comment by AtomicHawk** [comment]
I had this issue as well with some of the MWI turrets when the target was level with the turrets.

**Comment by sstixrud** [comment]
fixed.
