### ISSUE TITLE
AutoCannon Turret Bug

### ISSUE THREAD

**Issue by DegroSaxx** [sstixrud/WeaponCore#501]
## Is this a multiplayer or singleplayer bug?

Singleplayer

## Describe the bug:

The bug causes the toilet to crash and the weapons stop working

## Steps To Reproduce:

They didn't solve the problem

## Expected behavior:

#Missing correctly identified ammunition

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:

[debug.log](https://github.com/sstixrud/WeaponCore/files/8994933/debug.log)

**Comment by BDCarrillo** [comment]
Please post your Keen log as well so we can see all the mods in use in that world.  There are a few hacked together weapon mods meant for private servers that interfere with vanilla weapons.

**Comment by BDCarrillo** [comment]
This can be caused by having two vanilla replacers, or a mod that partially replaces vanilla weapons (such as the Sigma Draconis root tooty shooty w/e).  This isn't a fundamental issue with WC.
