### ISSUE TITLE
Custom turret controller's select interface overriden

### ISSUE THREAD

**Issue by stacktrace-error** [sstixrud/WeaponCore#503]
## Is this a multiplayer or singleplayer bug?
Singleplayer, likely to be both though.

## Describe the bug:
The custom turret controller's weapon selection menu does not appear in its interface, probably due to WC's standard turret options taking their place.

## Steps To Reproduce:
- Place a turret controller
- Look for the weapon selection menu
- cucumber

## Expected behavior:
not this

### User Error Report (if Weapon-Specific) and log files
doesn't generate ¯\\\_(ツ)\_/¯

**Comment by BDCarrillo** [comment]
Not a bug or issue, weapon assignment is automatic for the WC CTC.  See [https://github.com/sstixrud/WeaponCore/wiki/Player-Tips#custom-turret-controller](https://github.com/sstixrud/WeaponCore/wiki/Player-Tips#custom-turret-controller)
