### ISSUE TITLE
weaponcore stop working in multiplayer after die or change sector-server

### ISSUE THREAD

**Issue by Godassss** [sstixrud/WeaponCore#506]
## Describe the bug: The weaponcore target system works fine, but everytime i die, the target system dont work, cant lock any grids
and i have to do /wc setdefaults and relog everytime.

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:  https://drive.google.com/file/d/1vMjDHmkHnknFGA09Ad30fBQ4uG9GKG_f/view?usp=sharing

**Comment by sstixrud** [comment]
This is not a WC problem, wc is unaware of when a sector changes and fixing this will need to happen with the mod/plugin controlling sector changes.
