### ISSUE TITLE
Missiles doing damage to the grid that fired them

### ISSUE THREAD

**Issue by EmperorEna** [sstixrud/WeaponCore#509]
## Is this a multiplayer or singleplayer bug?

Only tested in singleplayer

## Describe the bug:

When firing missiles at a target, they can fly back at you and if they hit you, they will deal damage to the grid that fired them. I have also had cases of missiles destroying the ship as they are fired. They are supposed to phase through the grid, but do not always do this.

This behavior can be seen in the video I have provided here: https://www.youtube.com/watch?v=oANpo_8Igec

## Expected behavior:

1. Phasing through the grid
or
2. Hitting the grid but doing no damage

Missiles should not be able to destroy the grid that fired them? I'd hate for this to be intended behavior, it makes them more harmful to you than the enemy, because your PD can't even shoot down your own missiles.

**Comment by sstixrud** [comment]
This is the new expected behavior.
