### ISSUE TITLE
Noticed the LargeRailgun has the Weaponcore ID string instead of my WCVanilla replacer ID string.

### ISSUE THREAD

**Issue by BadM0dder** [sstixrud/WeaponCore#510]
## Is this a multiplayer or singleplayer bug?
Both

## Describe the bug:
Darkstar is overriding my CubeBlock sbc, darkstar bls.

## Steps To Reproduce:
change the component list in a WCVanilla replacer mod, or the description or name in the sbc of the small grid railgun, large grid railgun, and small grid autocannon turret.

I can change all the other weapons but those.

## Expected behavior:
the railgun should show up as a weapon from my mod with my ID string, not from the weaponcore ID string.

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:

**Comment by sstixrud** [comment]
pilfit says not a bug
