### ISSUE TITLE
Add the optional ability to assign weapons to a custom turret controller.

### ISSUE THREAD

**Issue by Voidborn515** [sstixrud/WeaponCore#512]
**Is your feature request related to a problem? Please describe:**
If you say only want to make a single axis turret then the mod fails to add any attached weapons to the turret controller. Which reduces the usability of the feature and makes it frustratingly limited.

**Describe the solution or feature you'd like:**
Some form of weapon assignment based on vanilla that can be opted into allowing not only for greater freedom but also more consistent basic functionality.

**Comment by sstixrud** [comment]
WC CTC auto activates weapons placed on the assigned subgrid, this will not change.
