### ISSUE TITLE
Custome Turret Controller

### ISSUE THREAD

**Issue by StarExplorer22** [sstixrud/WeaponCore#513]
## Is this a multiplayer or singleplayer bug?

singleplayer 

## Describe the bug:

using WeaponCore breaks the CustomeTurret Controller. Unable to add a weapon to a block in the menu. There are no suitable options. Weapon checkboxes are removed.

## Steps To Reproduce:
open the Custome turret controller with any weapon core mod. The options added by the mod prevent the full use of the block.

## Expected behavior:
non-vanilla options and space to choice using weapons

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:
[Illustrative Screen](https://drive.google.com/file/d/1pwoJHQLcJuRhCtHvccTQ_Vqy4DTFSyEK/view?usp=sharing)

**Comment by ThiccMcButters** [comment]
I've been having the same issue, and nothing i've tried has fixed it.

**Comment by sstixrud** [comment]
WC CTC auto selects weapons placed on the subgrid, no need to manually configure.
