### ISSUE TITLE
No damage and more

### ISSUE THREAD

**Issue by ICHINOYA** [sstixrud/WeaponCore#514]
## Is this a multiplayer or singleplayer bug?

Singleplayer

## Describe the bug:
Any weapon from any mod, except vanilla has animation and sound of firing, is properly aimed, has an animation of hitting but does not deal any damage.
Vanilla Replacement Weapon also breaks all weapons - they stop taking ammo and nothing happens when you press Ctrl + R
For the test I used the Aryx Weapon Pack.

## Steps To Reproduce:

1. I cleared the Storage folder.
2. Made sure that all mods except WC and Aryx Weapon Pack removed
3. Started the game
4. Created a new game, including these 2 mods
5. Landed in the capsule and created a grid with a turret from the mod (It only uses energy) and the reactor.

## Expected behavior:

Shot the capsule and nothing but animation and sound happened, it remained completely unharmed (Also with other weapons)

Zip up that folder and link it here:
[Weapon Core_WeaponCore.zip](https://github.com/sstixrud/WeaponCore/files/9473617/Weapon.Core_WeaponCore.zip)

**Comment by sstixrud** [comment]
This isn't an issue with WC.
