### ISSUE TITLE
Weapon trying to hit an enemy through an allied grid

### ISSUE THREAD

**Issue by Abisius** [sstixrud/WeaponCore#515]
## Is this a multiplayer or singleplayer bug?
happened in singleplayer so far

## Describe the bug:
once upon a while weapons try to hit an enemy grid either static or moving through an allied grid that is completly blocking the los, not juts an accidential strafing shot but full on shoot through

## Steps To Reproduce:
repoduction wasnt succesfull so far reliably and it happened by chance, in the zip is a save just shortly before it happened to my the last time.

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:
dropbox link to the zip cause tis too big for github.
https://www.dropbox.com/s/1f5g8n07jcbjpyo/Report%20Allied%20weapons%20firing%20through%20allied%20grid.zip?dl=0

**Comment by sstixrud** [comment]
resubmit when you have a easy way to reproduce.

**Comment by Abisius** [comment]
i try to find a way as well as trying to get a save directly at the time it happens.
