### ISSUE TITLE
Fixed homing missile launchers do not fire at targets in range with no direct line of sight

### ISSUE THREAD

**Issue by lAimBotl** [sstixrud/WeaponCore#519]
**Is your feature request related to a problem? Please describe:**

Fixed homing missile launchers, that do not have a direct line of sight, 
do not fire on targets in range that they can hit, unless you force it to fire manually.

**Describe the solution or feature you'd like:**

A way to ignore Line of sight checks for a weapon, so that even if the launcher is on the other side of the ship,
they will still fire if a target is in range

**Additional context:**

**Comment by sstixrud** [comment]
This is not a problem.  You have other ways to achieve this.

**Comment by lAimBotl** [comment]
no method I have found works

**Comment by lAimBotl** [comment]
Not sure if this is a separate issue, but, I have "FireFull = true," and I found a way to stop it from firing the whole burst 
(which I assume is supposed to be "impossible" normally?), 
though it seems slightly related, since it does it if I "block" the line of sight of the weapon to the target
