### ISSUE TITLE
Toggle Mouse Shoot Disappearing

### ISSUE THREAD

**Issue by RazaPrime** [sstixrud/WeaponCore#52]
Happening on a non-dedicated MP world. Sometimes when loading into the world, the toggle mouse shoot button is no longer available, and the actionbar icons greyed out. Happening with weapons from various packs. Tried deleting the mod cache, and various mod load orders, none seem to alleviate the issue. Usually fixes itself after a world (or game) reload

**Comment by sstixrud** [comment]
fixed.
