### ISSUE TITLE
Railguns refuse to fire after being setup into a group for sequence fire.

### ISSUE THREAD

**Issue by VladislavLiubasiuk** [sstixrud/WeaponCore#521]
## Is this a multiplayer or singleplayer bug?

Singleplayer

## Describe the bug:

Vanilla Railguns refuse to fire after being assigned to a firing group, with sequence values put in place.

## Steps To Reproduce:

Build Vanilla Railgun (with the Vanilla Replacement mod active)
Assign firing group to each

## Expected behavior:

Railguns should support firing sequencing

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:

**Comment by VladislavLiubasiuk** [comment]
Unable to share the log file, since the specified folder doesn't have any after using CTRL+R for some reason

**Comment by sstixrud** [comment]
No useful information provided.   In addition this reported issue likely either the player not understanding how to configure sequence fire properly or the mod author having settings that prevents it.

**Comment by VladislavLiubasiuk** [comment]
... I literally used the tutorial video to do it.
https://www.youtube.com/watch?v=bRMUwAYCxuk&t=1s

**Comment by VladislavLiubasiuk** [comment]
[logs in question.zip](https://github.com/sstixrud/WeaponCore/files/9791148/logs.in.question.zip)
and those are the only files that get updated with CTRL+R.
