### ISSUE TITLE
Epic Bug!!!111!!!!11!!!

### ISSUE THREAD

**Issue by bucktt** [sstixrud/WeaponCore#522]
## Is this a multiplayer or singleplayer bug?

singleplayer as of now

## Describe the bug:

turrets or any weaponcore cannon/gun on a non-stationary grid refuses to shoot at some point in the game. which then forces me to reload the save

## Steps To Reproduce:

It happens at random, sometimes the weapons work, sometimes they don't (i.e manual aiming doesn't work, turrets don't move, don't shoot. but they reload once) . I tried to recreate it but it's hard to. Everything is fixed after a save reload

## Expected behavior:

normal gun behavior shooty shoot go boom bang

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:

**Comment by sstixrud** [comment]
This report is being closed because there is no actionable information in the report.
