### ISSUE TITLE
Turret placement bug

### ISSUE THREAD

**Issue by OwendB1** [sstixrud/WeaponCore#523]
## Is this a multiplayer or singleplayer bug?
Both

## Describe the bug:
Currently there is no second check being performed on RestrictionRadius collision for any already placed turrets. Any intersecting turrets will be lost upon restart or reload of save file instead of an immediate block happening.

## Steps To Reproduce:
1. Place down turret A with RestrictionRadius
2. Place down turret B without RestrictionRadius within the radius of turret A
3. Reload world save
4. Boom turret goes poof even though it let you place it.

## Expected behavior:
Immediate check so that either way around of placing gets blocked from happening.

**Comment by sstixrud** [comment]
This is not something I have time to look into.  If you want to submit a PR i'll accept it.
