### ISSUE TITLE
Weapons not changing ammo type

### ISSUE THREAD

**Issue by Hairy-McClairy** [sstixrud/WeaponCore#525]
## Is this a multiplayer or singleplayer bug?
Singleplayer

## Describe the bug:
Weapons refuse to switch ammo type, they will instantly switch back to default when changing ammo type.
I also have a screen recording, this has happened with every weaponcore-dependent mod I have and persisted after clearing cache.

## Steps To Reproduce:
Using a weapon mod (of weaponcore dependency) attempt to switch ammo types from the k menu or g menu in cockpit. 

## Expected behavior:
K menu will switch back to default instantly, G menu will appear normal in UI but not actually work - not a normal function.

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:
https://drive.google.com/drive/folders/149Mn-phEhMi3hnubwXIp-WE2PiVasS7w?usp=sharing

**Comment by sstixrud** [comment]
Ammo switching is working fine for me and others.  This is either a bug with a specific weapon mod you are using or you have a corrupt worldsave/mod download.  Create a new world and try again with just wc and try again... if it still fails follow the corrupt mod steps on the steam page.
