### ISSUE TITLE
Unable to find the specified file?????

### ISSUE THREAD

**Issue by Sky-441** [sstixrud/WeaponCore#526]
## Is this a multiplayer or singleplayer bug?

Both

## Describe the bug:

Hello, i got an issue going on with both my local test world and server thats displaying a small spam message sayin Unable to find the specified file since yesterday

## Steps To Reproduce:

-New game 
-Add Weaponcore Mod
-Start

## Expected behavior:

Multiple messages saying "Unable to find the specified file"

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:

**Comment by Sky-441** [comment]
Steps To Reproduce:

-New game
-Add Weaponcore mod
-Start

**Comment by Sky-441** [comment]
also i got reports of gat gun issue

**Comment by sstixrud** [comment]
Sounds like you have file or mod download corruption follow the steps on steampage to repair.
