### ISSUE TITLE
Swarmer Missiles Freezing game and no targeting. 

### ISSUE THREAD

**Issue by AaronNagy** [sstixrud/WeaponCore#528]
## Is this a multiplayer or singleplayer bug?
Both Single Player and on my DS hosted by HostHavoc

## Describe the bug:
Swarmer Missile freeze the game upon hitting target/voxel
I do have other weapons not targeting anything aswell and only Dumbfire with override, but for some reason it wont let me create a bug report.

## Steps To Reproduce:
Tried both on Singleplayer worlds and DS worlds on 2 different DS's and 2 different PCS on single player. So a total of 4 instances

## Expected behavior:
These weapons were working a week ago.

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:
[1918681825.sbm_CoreSystems.zip](https://github.com/sstixrud/WeaponCore/files/10172940/1918681825.sbm_CoreSystems.zip)

**Comment by sstixrud** [comment]
retest and report back
