### ISSUE TITLE
Exception in SessionSim

### ISSUE THREAD

**Issue by Grumbledore667** [sstixrud/WeaponCore#530]
## Is this a multiplayer or singleplayer bug?
Multiplayer

## Describe the bug:
After some time Weapons won`t deal damage anymore. 

`01-03-23_19-10-57-105 - Exception in SessionSim: System.NullReferenceException: Object reference not set to an instance of an object.
   at CoreSystems.Projectiles.Projectile.DestroyProjectile()
   at CoreSystems.Projectiles.Projectiles.UpdateState(Int32 end)
   at CoreSystems.Projectiles.Projectiles.SpawnAndMove()
   at CoreSystems.Session.Simulate()`

WeaponCore related mods used:

[MA WeaponCore](https://steamcommunity.com/sharedfiles/filedetails/?id=2023664724)
[Aryx Weapon Enterprises [WeaponCore]](https://steamcommunity.com/sharedfiles/filedetails/?id=2530716039)
[[Mexpex] MWI - Weapon Collection 1 [WeaponCore](21)](https://steamcommunity.com/sharedfiles/filedetails/?id=1920388300)
[[Mexpex] MWI - Weapon Collection 2 [WeaponCore] (8)](https://steamcommunity.com/sharedfiles/filedetails/?id=2082309225)
[[Mexpex] MWI - Homing Weaponry (23)](https://steamcommunity.com/sharedfiles/filedetails/?id=1919062467)

We have no clue what is causing it nor how to fix it. 
## Steps To Reproduce:
Can provide savegame if needed.

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:
[1918681825.sbm_CoreSystems.zip](https://github.com/sstixrud/WeaponCore/files/10347179/1918681825.sbm_CoreSystems.zip)

**Comment by sstixrud** [comment]
Interesting never seen this before. I did push an update that should make it impossible for this to happen.  reopen if its still an issue.
