### ISSUE TITLE
Artillery Turrets are not being targeted by vanilla weapon systems

### ISSUE THREAD

**Issue by Starseeker1990** [sstixrud/WeaponCore#532]
## Is this a multiplayer or singleplayer bug?
Single player
Unknown in multiplayer

## Describe the bug:
Artillery Turrets are not being targeted by vanilla weapon systems
unknown if other modded weapons are affected

## Steps To Reproduce:
Paste enemy ship in with a Artillery Turret and it will not be targeted by your grid other weapons on grid are targeted

## Expected behavior:
no idea what to write other than the artillery should be target properly

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:
[1918681825.sbm_CoreSystems.zip](https://github.com/sstixrud/WeaponCore/files/10663298/1918681825.sbm_CoreSystems.zip)

**Comment by sstixrud** [comment]
Will be fixed in the next update.

**Comment by Starseeker1990** [comment]
Thank you glad to know it wasnt just me? Also wondering when the next update will be? Just wondering?
