### ISSUE TITLE
Admin untargetable is broken

### ISSUE THREAD

**Issue by Kenetor** [sstixrud/WeaponCore#55]
setting yourself to untargetable is not obeyed by this mod

**Comment by Kenetor** [comment]
I was using MWI weaponcore edition (with weaponcore itself) within a local multiplayer game, to test the mod, i had to quickly add something to a ship in another faction, and it fired on me even though i admined set myself to untargetable.

**Comment by blitz2190** [comment]
Not possible given current access to gui, Use Ingore Safe Zone, you will also have to leave the range of the turrets if they are already targeting you
