### ISSUE TITLE
The red-box issue

### ISSUE THREAD

**Issue by Ackelimpa** [sstixrud/WeaponCore#556]
## Is this a multiplayer or singleplayer bug?

singleplayer

## Describe the bug:

When welding a weapon in survival mode, upon completion the weapon is unusable and a red box appears around it. I've tried gatling turret with Replace Vanilla Weapons mod as well as severall types of weapons from Aryx Weapon Enterprises. When accessing it via control panel none of the weaponcore info is available, nor any of the targeting options.

Reloading fixes the previously welded weapons, however building new weapons causes the issue to arise on the newly welded weapons.

## Steps To Reproduce:

Weld weapon to completion in survival

## Expected behavior:

A red box appears around the weapon as the weapon reaches a functional stage as a result of welding, my understanding based on steam comments is that placing it in creative does not elicit this behavior.

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:

[WeaponCore bug report.zip](https://github.com/sstixrud/WeaponCore/files/11806324/WeaponCore.bug.report.zip)

**Comment by sstixrud** [comment]
Fixed
