### ISSUE TITLE
WC based weapons NEVER incur any reputation loss, only cause hostilities

### ISSUE THREAD

**Issue by godfuckingdamnit** [sstixrud/WeaponCore#563]
## Is this a multiplayer or singleplayer bug?
Singleplayer

## Describe the bug:
WC weapons don't cause any standing drop with factions. I'm in a faction, and I can rip up enemies with my WC Aryx weaponry (which is also the most prolific weapon pack in space engineers) and no reputation lose incurs. Enemies don't even get hostile until you manage to damage their grid, but have no problems with you taking their shields down, though I don't know if this is relevant. However, you grind up an enemy's little armour block? Or shoot them with non-WC weaponry or vanilla? They get **furious.**

## Steps To Reproduce:
I have no clue, this seems to be a thing that happens only to me and I can't fucking find ANYONE EVER that has this issue. I can zip up my WC folder to you for comparison with your main file, but even on a clean world, this problem occurs.

## Expected behavior:
For enemies to incur reputation loss upon shooting at them (getting hostile happens, but nothing beyond that)

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:

**Comment by sstixrud** [comment]
fixed
