### ISSUE TITLE
Deleting small grid Custom Turret Controller with everything toggled off crashes game

### ISSUE THREAD

**Issue by admborkbork** [sstixrud/WeaponCore#569]
## Is this a multiplayer or singleplayer bug?
Single player tested with JUST WeaponCore and bug is reproducible.
Dedicated server multiplayer with several mods including WeaponCore and bug is reproducible.
The multiplayer server itself crashes when this bug is encountered, along with all connected clients.
I don't have access to create a dedicated multiplayer server with JUST WeaponCore to confirm if that is an issue as well, but I suspect it would be.

## Describe the bug:
After creating a custom turret, setting all AI settings to Off, saving and exiting back to desktop, then reloading, deleting the turret controller block (either via creative right-click or with a grinder) crashes the game with System.NullReferenceException error.

## Steps To Reproduce:
Create new empty world with only WeaponCore mod loaded
Construct a small grid of (e.g.) light armor just as a foundation to put stuff on
Add a battery
Add a small advanced rotor
Add a small hinge on top of rotor
Add a small conveyor on top of hinge
Add a gatling gun to side, attached to conveyor
Add a camera on top of conveyor
Add a custom turret controller to the foundation grid
Enter the control panel of the custom turret controller, add the rotor, hinge, and camera as usual, toggle "Enable AI" to off and all targeting options to off (e.g., "Target Neutrals" etc.)
Close out of the control panel
Save the world, exit to main menu, exit to desktop
--> Important --> If you don't exit all the way out, this crash doesn't happen
Re-launch Space Engineers, choose "Continue" to load the world
(optional) Verify that everything is still set to off in the Control Panel
Attempt to delete the Custom Turret Controller
Game crashes

## Expected behavior:
Game should not crash when deleting Custom Turret Controller, no matter what options are toggled

### User Error Report (if Weapon-Specific) and log files
[SpaceEngineers_20230823_212443444.log](https://github.com/sstixrud/WeaponCore/files/12425031/SpaceEngineers_20230823_212443444.log)

**Comment by BDCarrillo** [comment]
Resolved in latest patch
