### ISSUE TITLE
Custom Turret Controller Toolbar Actions Do Not Work

### ISSUE THREAD

**Issue by grayscale420** [sstixrud/WeaponCore#576]
## Is this a multiplayer or singleplayer bug?
Singleplayer

## Describe the bug:
When building a custom turret, the "setup actions" tab does not function properly.  You can add actions but regardless of the slot you put the action in, nothing triggers whether the turret locates a target or not.  For the purposes of testing, I only have Camera Panning and WeaponCore active (previously, I only had WeaponCore active) and previous tests with vanilla work fine, as expected.  

I haven't seen anyone talking about this particular issue anywhere online, so I'm unsure if what I'm reporting is an intended change or not.

## Steps To Reproduce:
- Prepare custom turret
- Set desired action(s)

## Expected behavior:
Action(s) should trigger.

### User Error Report (if Weapon-Specific) and log files
N/A

**Comment by BDCarrillo** [comment]
This is not a bug.  Custom actions in CTCs, cockpits, or automaton blocks based on "being targeted" do not function in WC.  https://github.com/sstixrud/CoreSystems/wiki/Player-Tips#custom-turret-controller
