### ISSUE TITLE
1.194 steamctg beam laser not showing

### ISSUE THREAD

**Issue by nukeguard** [sstixrud/WeaponCore#58]
Beams are not working for missile turret type, Beams: true, false, false, false, true
Beams are working for sorter type, Beams: true, false, false, false, true

Line: True, Trail: false on both Octobeam and Obelisk

secondary: cannot change weapon group in menu with mouse wheel, only 1st group selection is available.

I can test more on 1.194 steamctg

**Comment by nukeguard** [comment]
I also could not see beams in 1.193, idk, it worked fine yesterday with local weapon core

**Comment by sstixrud** [comment]
fixed.
