### ISSUE TITLE
A method to bypass charge time/amount in creative

### ISSUE THREAD

**Issue by Wortho27** [sstixrud/WeaponCore#59]
Currently it's fine for weapons that don't take ages to charge but if you have a big superweapon that takes a while to charge and you've balanced it for survival, it still takes the same amount to charge in creative.

I propose a variable CreativeChargeMultiplier put in the weapon.cs that will multiply reloadtime and charge amount by that value. If I put in 0.05f, that will reduce a 10 minute charge of 400 MWh to a 30 second charge of 20MWh.

This would make testing guns in creative a bunch easier where you don't have to wait ages

**Comment by sstixrud** [comment]
No plans to add this feature.
