### ISSUE TITLE
Change BattleCruiser to BattleShip target and add hints to help people identify purpose of icons

### ISSUE THREAD

**Issue by enenra** [sstixrud/WeaponCore#7]
- [ ] BattleCruisder target
- [ ] BattleShip target
- [ ] icon hints

**Comment by nukeguard** [comment]
Should I add text for hints?

**Comment by sstixrud** [comment]
I think so, but I think I will only show the hints for a few seconds when the someone first selects a target in for that game session.  Although I may make a UI key that enables all hints temporarily.

**Comment by nukeguard** [comment]
maybe a ui popup window with all info in that for targets and targeting?

**Comment by sstixrud** [comment]
that could work if theres a good time to display it

**Comment by nukeguard** [comment]
I still need to complete icon hints

**Comment by nukeguard** [comment]
I think all this info is in a guide, I don't remember if we decided to stick with the threat icons as is or change from number system, seems like no-one has said anything about it in weeks. The Battlecruiser is already changed to BattleShip
