### ISSUE TITLE
Not saving ModStorageComponent

### ISSUE THREAD

**Issue by B4Rme** [sstixrud/WeaponCore#71]
After latest WeaponCore update the following warning is thrown on a DedicatedServer:

`15:05:04.7801 [WARN]   Keen:    Not saving ModStorageComponent GUID: 75bbb4f5-4fb9-4230-beef-bb79c9811504, not claimed
15:05:04.7801 [WARN]   Keen:    Not saving ModStorageComponent GUID: 75bbb4f5-4fb9-4230-beef-bb79c9811504, not claimed
15:05:04.7801 [WARN]   Keen:    Not saving ModStorageComponent GUID: 75bbb4f5-4fb9-4230-beef-bb79c9811504, not claimed
15:05:04.7801 [WARN]   Keen:    Not saving ModStorageComponent GUID: 75bbb4f5-4fb9-4230-beef-bb79c9811504, not claimed
15:05:04.7801 [WARN]   Keen:    Not saving ModStorageComponent GUID: 75bbb4f5-4fb9-4230-beef-bb79c9811504, not claimed
15:05:04.7801 [WARN]   Keen:    Not saving ModStorageComponent GUID: 75bbb4f5-4fb9-4230-beef-bb79c9811504, not claimed
15:05:04.7958 [WARN]   Keen:    Not saving ModStorageComponent GUID: 75bbb4f5-4fb9-4230-beef-bb79c9811504, not claimed
15:05:04.7958 [WARN]   Keen:    Not saving ModStorageComponent GUID: 75bbb4f5-4fb9-4230-beef-bb79c9811504, not claimed
15:05:04.7958 [WARN]   Keen:    Not saving ModStorageComponent GUID: 75bbb4f5-4fb9-4230-beef-bb79c9811504, not claimed
15:05:04.7958 [WARN]   Keen:    Not saving ModStorageComponent GUID: 75bbb4f5-4fb9-4230-beef-bb79c9811504, not claimed`

it keeps spamming my DS Logs a second after Loading and the server gets Laggy

**Comment by B4Rme** [comment]
pull reqeust #72 fixes this issue. Tested on a Local Clean save (with and Without the fix)

**Comment by TheWizardLizard** [comment]
Assuming fixed due to #72

**Comment by TheWizardLizard** [comment]
My bad, request not pulled yet

**Comment by sstixrud** [comment]
merged.

**Comment by Ikeprof** [comment]
Still getting a wall of this during server save events.  Seems to extend the "save lag" duration significantly
