### ISSUE TITLE
[MP] Allied units shoot at each other

### ISSUE THREAD

**Issue by ApolloDensin** [sstixrud/WeaponCore#75]
Allying with a player faction or a npc faction still causes both sides to target each other with weapons and automatically fire on each other. An allied ship will appear over your base and will target you with their weapons, and our weapons will fire back

**Comment by sstixrud** [comment]
Need more information

**Comment by ApolloDensin** [comment]
Ally with a faction, either AI or player faction. The turrents will shoot at those players/ships even though they are white and neutral. We had a player who is allied approach our base to trade, our guns opened up on him. We have tried going to another npc base to trade with the economy mod, and the guns opened up on them

**Comment by sstixrud** [comment]
Please confirm this happens in single player and provide a world save.

**Comment by AtomicHawk** [comment]
I've had multiple ships (friendly) in close proximity with no issues of friendly fire - even with an enemy ship also in firing range. Friendly ships fired on the enemy but not each other. Can't provide input on NPC or other factions as I'm in an empty world. Single player creative mode.

**Comment by sstixrud** [comment]
Should be fixed.
