### ISSUE TITLE
[SP] Turret "Control" Very Imprecise

### ISSUE THREAD

**Issue by Tkdmaster** [sstixrud/WeaponCore#76]
In doing my single palyer testing with v46, I found that manual weapon control is very jittery and imprecise, here is 2 GIF's showing vanilla, and then v46+vanilla replacement.

Vanilla: https://gfycat.com/ImpossibleSoftFlycatcher
v46+replacement: https://gfycat.com/TinyGiftedFlyingfish

**Comment by sstixrud** [comment]
Should be fixed.
