### ISSUE TITLE
Turrets not abiding by target settings.

### ISSUE THREAD

**Issue by ForgottenLamb** [sstixrud/WeaponCore#77]
I've had this problem since before Frostbite was released. By default targeting of biologicals is disabled. However turrets still track and open fire on wolves. Cycling the option to enabled has the same effect and gain cycling back onto biological. Turrets seem to engage all targets, though I've not tested on neutral targets yet. I've also tested with "focus fire" enabled but turrets continue to fire at all targets.

**Comment by skyraze** [comment]
I can atest to this in my dedicated server.
it will targets anything that isnt faction related, including neutrals. it doesnt follow any of the settings given to them, and sometimes will keep firing even after shutting them off.

**Comment by skyraze** [comment]
[debugdevelop.log](https://github.com/sstixrud/WeaponCore/files/4423694/debugdevelop.log)

**Comment by sstixrud** [comment]
This should be fixed.
