### ISSUE TITLE
[Sugg.] Var to limit weapons based on grid size in addition to existing weapon limit variable

### ISSUE THREAD

**Issue by Wortho27** [sstixrud/WeaponCore#79]
In addition to the gridweaponcap var that exists, I propose you add a gridsizeweaponcap. This would work in the following way: as opposed to an absolute number like the existing var works, you would put in the amount of blocks in a grid where you could be allocated one extra weapon.

For example
GridSizeWeaponCap = 1000 
means you can place one weapon on a grid per 1000 blocks it has, rounded up. In the case both values were set, the weapon cap would be set at the smallest of the two, ie the current var acting as a minimum limit

**Comment by AtomicHawk** [comment]
I like the idea, but I'd want it as an optional option in the config file. It's great for servers and multiplayer, but in the single player realm it doesn't really make much sense to me (I don't play MP very often).

**Comment by sstixrud** [comment]
Dont plan on adding this.
