### ISSUE TITLE
Weaponfire Does Not Reach Target Grid

### ISSUE THREAD

**Issue by Xeno1177** [sstixrud/WeaponCore#83]
Dedicated server, MP
Mods: Defense Shields, Northwind, Octobeam, Vanilla Replace

Weaponfire from vanilla weapons as well as several Weaponcore compliant weapon mods does not actually reach the targeted ship and does no damage.

![20200331051844_1](https://user-images.githubusercontent.com/49629363/78301918-ae16f500-74ee-11ea-914d-562f2aef6cd3.jpg)

![20200331050806_1](https://user-images.githubusercontent.com/49629363/78301938-b838f380-74ee-11ea-86c2-49b9f1c4322c.jpg)

**Comment by sstixrud** [comment]
Need more information on how to produce this issue, ideally with a video.

**Comment by Xeno1177** [comment]
What would you like to see on the video?  Happy to help in any way I can.

**Comment by sstixrud** [comment]
The video should clearly show the issue and the steps to reproduce it.

**Comment by Xeno1177** [comment]
Here is a short video of the issue and the associated logs.  Let me know if I can improve the reporting or if there is something else you would like to see.

As a side note, the Vanilla Replacement weapons were not firing at all.  I showed they were enabled in the video and you can see them tracking the target.

[WeaponCoreTest.zip](https://github.com/sstixrud/WeaponCore/files/4453111/WeaponCoreTest.zip)

**Comment by blitz2190** [comment]
does the ship being fired at have a shield on on it?

**Comment by Xeno1177** [comment]
Yes, but it is down

**Comment by Xeno1177** [comment]
Update:
When turning off "all" Defense Shield blocks (not just down but off), weapons fire reaches and damages grid.

**Comment by sstixrud** [comment]
fixed
