### ISSUE TITLE
ammo trails effect doesn't play when it misses grid, only when hits something

### ISSUE THREAD

**Issue by AutoMcDonough** [sstixrud/WeaponCore#85]
Noticed with laser weapons. The beam line always draws like it should, but the trail (using for fade effect) only happens when the beam hits something. If fired off into space then I only get the line, no trail.

**Comment by TheWizardLizard** [comment]
I can confirm this:

[Video where the beam shoots off into the distance hitting nothing after it finishes](http://protogen.ga/p/JiOW0y0H6U.mp4)

[Video where the beam stops while still being able to hit blocks](http://protogen.ga/p/m86ZNORmbE.mp4)

**Comment by sstixrud** [comment]
Should be fixed.
