### ISSUE TITLE
Fixed weapon groups keep forgetting shoot settings.

### ISSUE THREAD

**Issue by AutoMcDonough** [sstixrud/WeaponCore#86]
Make weapon group, set mouse shoot to on.
Every time I exit/enter the cockpit or something even going into control menus or other things without even leaving the cockpit, the group settings have reverted back off.
These need to stay set. Should be able to have everything configured, paste the ship and go, all weapons working.

**Comment by TheWizardLizard** [comment]
I believe it was set this way initially because mouse shoot would happen inside the pause menu and terminals, at least for mouse shoot that is.

**Comment by sstixrud** [comment]
Please let me know if this is still an issue.

**Comment by AutoMcDonough** [comment]
Still happens for me.

**Comment by blitz2190** [comment]
this is intentional when you leave the cockpit it should set to disabled, it will no longer do so in menu

**Comment by AutoMcDonough** [comment]
i disagree! settings should be remembered.
also going into control menu resets them. very annoying.
