### ISSUE TITLE
WC turrets inactive on world load, identify target only after sitting in ship cockpit

### ISSUE THREAD

**Issue by AutoMcDonough** [sstixrud/WeaponCore#88]
What I am seeing in my test world is they will identify and shoot at pirate ship grid, then I save+close. When I reload, they are no longer actively seeking targets. As soon as I sit in the ship's cockpit seat, the turrets identify threat and start shooting. I have had cases where even sitting in the ship wasn't enough, had to use scrollwheel to get WC targeting reticle to pop in and turret action.

**Comment by sstixrud** [comment]
Should be fixed.
