### ISSUE TITLE
muzzlecheck should use block collisions instead of entire block space.

### ISSUE THREAD

**Issue by AutoMcDonough** [sstixrud/WeaponCore#89]
The purpose of this feature is to enable a better clearance check to avoid hitting your own ship with the weapon, with the mod author knowing this is a less performant option.
Currently it is kind of useless as identifying an entire blockspace often just results in the turret never firing. This is often half-blocks and armor slopes which appear to player as a non-issue, plenty of clearance to the gun barrels. Or other nearby turrets even.
Would like to see collisions used for friendly grids on this.

**Comment by sstixrud** [comment]
The actual issue had nothing to do with muzzle check.  Should be fixed now.  Only use muzzle check on weapons with multiple muzzles that are spread far apart.
