### ISSUE TITLE
Add toolbar shoot icon highlight and status textures

### ISSUE THREAD

**Issue by enenra** [sstixrud/WeaponCore#9]
Add toolbar shoot icon highlight and status textures to help people visually see that a weapongroup is still charging and/or a weapon in group is out of ammo.

**Comment by nukeguard** [comment]
is that going to require some code too? this shoot icon, do you mean like what keen does when out of ammo or reloading while controlling a turret?

**Comment by sstixrud** [comment]
Yes, I will write code that detects when the toolbar action was pressed, keep track of how long until the slowest weapon in the group will again be ready to fire and display the appropriate texture.  In addition I will monitor for any weapons in the group that run out of ammo and overlay a texture indicating this state.

**Comment by nukeguard** [comment]
so icons that say reloading and Firing delay?

**Comment by nukeguard** [comment]
find out if it's possible to use what keen does on the turret reload?

**Comment by nukeguard** [comment]
Reload cooldown/fire delay and remaining ammo icon sets completed Jan30

**Comment by nukeguard** [comment]
Text images of Reload and Recharging also completed for display above toolbar

**Comment by sstixrud** [comment]
Feature added
