### ISSUE TITLE
MWI Homing weapons continuously firing

### ISSUE THREAD

**Issue by AtomicHawk** [sstixrud/WeaponCore#92]
[debugdevelop.log](https://github.com/sstixrud/WeaponCore/files/4435292/debugdevelop.log)

As title says, the missiles and torpedoes are firing continuously regardless of whether Mouse Shoot is on or off. After all functional blocks on the target ship are destroyed the weapons continue to fire (note: MWI cannons stopped firing at this point) then eventually stopped targeting the enemy ship altogether and just fired straight out. 

Turning blocks on/off and reloading save did not fix the issue.

**Comment by AtomicHawk** [comment]
I guess I'll tag on another semi-related issue here instead of making a new thread. 

Opened the same world, pasted in an enemy ship, set it as target. Only the missiles and torpedoes fired at the target ship (again disregarding mouse shoot on/off). None of the cannons fired (or even moved) at all
After the ship was destroyed the missiles continued to fire in a straight line until turned off completely.

[debugdevelop.log](https://github.com/sstixrud/WeaponCore/files/4439475/debugdevelop.log)

**Comment by sstixrud** [comment]
This is expected missile behavior.

**Comment by AtomicHawk** [comment]
How is this expected behavior when they aren't obeying "Mouse Shoot" behavior?
