### ISSUE TITLE
TurnOn / TurnOff emissive trigger conditions not fully working

### ISSUE THREAD

**Issue by Wortho27** [sstixrud/WeaponCore#94]
Currently then TurnOn TurnOff conditions only update when placing the weapon, welding it to functional, or toggling the weapon itself on or off.

TurnOn should trigger when:

- weapon is receiving power and turned on but is broken or not built and welded to functional
- weapon is receiving power and is functional but is off and then turned on by toolbar
- weapon is functional and turned on with no power but gets powered
- weapon is placed on a grid and it has enough power (assuming functional and turned on on place)

TurnOff should trigger when:

- weapon becomes damaged to non functional
- weapon is turned off
- weapon stops receiving power, either by grid turn off or power completely gone

**Comment by sstixrud** [comment]
fixed
