### ISSUE TITLE
“Toggle Mouse Shoot”  not appearing for mixed weapon group

### ISSUE THREAD

**Issue by MacXimus** [sstixrud/WeaponCore#99]
I have made a mixed grouping of weapons on ship.  (This is a mixed group of gatlings and m2 destroyer launchers.  I have the vanilla replacements mod running.)
When I try to add that group to the toolbar no option appears for “Toggle Mouse Shoot” .  Only the various weapon on/off and shoot on/off options appear.
The “Toggle Mouse Shoot” appears on homogeneous groups (all gats, all launchers).

**Comment by blitz2190** [comment]
Unfortunately this has the same limitation as keen fixed weapons in that you can only combine group actions for the same block types, not fixable
